### ISSUE TITLE
Wrong connection string but sql.Open returns nil error nonetheless

### ISSUE THREAD

**Issue by AtakanColak** [sijms/go-ora#1]
I wanted to try this module out, and realized I hadn't passed any address parameters to the connection string. It still hadn't caused any errors. So when I tried the code below it still resulted with success(!).

```
package oracledb_test

import (
	"database/sql"
	"testing"

	_ "github.com/sijms/go-ora"
)

func TestGora(t *testing.T) {
	conn, err := sql.Open("oracle", "oracle://aa:AA@aa")
	if err != nil {
		t.Fatal(err.Error())
	}
	defer conn.Close()

	t.Log("success")
}
```

**Comment by AtakanColak** [comment]
Could you also provide an example connection string with IP address? I'm not exacly sure on how to make it. Thank you.

**Comment by sijms** [comment]
I am happy for you comment
you need to provide user:pass@server/service_name

**Comment by AtakanColak** [comment]
Just to be clear, its like MYUSER:MYPASS@127.0.0.1/SERVICE right?

**Comment by sijms** [comment]
yes

**Comment by sijms** [comment]
this is my mistake in readme file i write 
conn, err := sql.Open("oracle", "oracle://user:pass@dbname/service_name")
but it is actually means:
conn, err := sql.Open("oracle", "oracle://user:pass@server/service_name")
i change it now in readme file

**Comment by AtakanColak** [comment]
@sijms thank you, so remaining issue is why doesn't wrong connection string return any errors?

**Comment by sijms** [comment]
i will review and fix and inform you

**Comment by sijms** [comment]
issue fixed
