### ISSUE TITLE
cannot find credentials for server for Oracle Cloud ATP database

### ISSUE THREAD

**Issue by giridharanram** [sijms/go-ora#100]
Hi

I am not able to connect to oracle ATP database.I have downloaded wallet from Oracle cloud console.

Connection string used:
oracle://admin@adb.ca-toronto-1.oraclecloud.com:1522/**********_high.adb.oraclecloud.com?TRACE FILE=trace.log&WALLET=/Users/******/Downloads/Wallet

I have used host, port and service name from tnsnames.ora file in wallet.zip

I am using version v2.1.27 and go version 1.16
Error:
cannot find credentials for server: adb.ca-toronto-1.oraclecloud.com:1522, service:********_high.adb.oraclecloud.com,  username: admin

 @sijms  Please let me know if I am missing something here

**Comment by sijms** [comment]
can you go to function 
`func (w *wallet) getCredential(server, port, service, username string) (*walletCredential, error) {`
at line# 380
and add at the beginning of the code 
`fmt.Println(w.credentials)`
and see if your database information and username present or not

or just debug this function and see what happen

**Comment by sijms** [comment]
the absence of information may be due to 
1- the information is already absent
2- code problem related to search and find

**Comment by giridharanram** [comment]
Credentials slice is empty but username is present
<img width="1625" alt="image" src="https://user-images.githubusercontent.com/46867712/129504174-d0ce91ff-ce0e-48b8-9eff-a5e9357f5459.png">

**Comment by sijms** [comment]
for me every thing appear ok and wallet contain no credential

did you try to use the wallet with other client or program like sql developer?

**Comment by sijms** [comment]
try also to print temp3 at wallet.go line# 226 
it should contain something like this 
`Id: oracle.security.client.connect_string1`
or 
`Id: oracle.security.client.username1`
or 
`Id: oracle.security.client.password`
if you find any thing else please inform

**Comment by sijms** [comment]
you can use tool in oracle server to help you displaying the wallet content as follow
wallet directory should contain **ewallet.p12, cwallet.sso** files
```
orapki wallet display -wallet "path_to_wallet_directory"
```
output like this
```
Oracle PKI Tool : Version 12.2.0.1.0
Copyright (c) 2004, 2016, Oracle and/or its affiliates. All rights reserved.

Requested Certificates: 
User Certificates:
Subject:        CN=localhost
Subject:        CN=10.211.55.2
Oracle Secret Store entries: 
oracle.security.client.connect_string1
oracle.security.client.connect_string2
oracle.security.client.connect_string3
oracle.security.client.connect_string4
oracle.security.client.connect_string5
oracle.security.client.connect_string6
oracle.security.client.password1
oracle.security.client.password2
oracle.security.client.password3
oracle.security.client.password4
oracle.security.client.password5
oracle.security.client.password6
oracle.security.client.username1
oracle.security.client.username2
oracle.security.client.username3
oracle.security.client.username4
oracle.security.client.username5
oracle.security.client.username6
Trusted Certificates: 
Subject:        CN=10.211.55.2
Subject:        CN=localhost
```

**Comment by giridharanram** [comment]
> for me every thing appear ok and wallet contain no credential
> 
> did you try to use the wallet with other client or program like sql developer?

**Comment by giridharanram** [comment]
> did you try to use the wallet with other client or program like sql developer?

It is working with SQL developer and go app with gordor

<img width="778" alt="image" src="https://user-images.githubusercontent.com/46867712/129600199-010afe82-7d4d-46ac-9fb1-179990ef0141.png">

**Comment by sijms** [comment]
you have user name and password 
wallet support passwordless connection

**Comment by giridharanram** [comment]
> you can use tool in oracle server to help you displaying the wallet content as follow
> wallet directory should contain **ewallet.p12, cwallet.sso** files
> 
> ```
> orapki wallet display -wallet "path_to_wallet_directory"
> ```
> 
> output like this
> 
> ```
> Oracle PKI Tool : Version 12.2.0.1.0
> Copyright (c) 2004, 2016, Oracle and/or its affiliates. All rights reserved.
> 
> Requested Certificates: 
> User Certificates:
> Subject:        CN=localhost
> Subject:        CN=10.211.55.2
> Oracle Secret Store entries: 
> oracle.security.client.connect_string1
> oracle.security.client.connect_string2
> oracle.security.client.connect_string3
> oracle.security.client.connect_string4
> oracle.security.client.connect_string5
> oracle.security.client.connect_string6
> oracle.security.client.password1
> oracle.security.client.password2
> oracle.security.client.password3
> oracle.security.client.password4
> oracle.security.client.password5
> oracle.security.client.password6
> oracle.security.client.username1
> oracle.security.client.username2
> oracle.security.client.username3
> oracle.security.client.username4
> oracle.security.client.username5
> oracle.security.client.username6
> Trusted Certificates: 
> Subject:        CN=10.211.55.2
> Subject:        CN=localhost
> ```

orapki output :

```giridharanramasamy@Giridharan-MacBook-Pro bin % ./orapki wallet display -wallet /Users/giridharanramasamy/Downloads/Wallet_cannstock
Oracle PKI Tool : Version 12.2.1.3.0
Copyright (c) 2004, 2017, Oracle and/or its affiliates. All rights reserved.

Requested Certificates: 
User Certificates:
Subject:        CN=8700EC6372A3418FA38A3CF8FF7844F7.52EF8AFD6BC744BE8FD8086254CDF3B8,DNQ=V1
Trusted Certificates: 
Subject:        CN=DigiCert Global Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
Subject:        C=US,ST=California,L=Redwood Shores,O=Oracle Corporation Autonomous Data Warehouse Cloud Self-signed CA,CN=Autonomous Data Warehouse Cloud CA
Subject:        CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US
giridharanramasamy@Giridharan-MacBook-Pro bin % ```

**Comment by sijms** [comment]
can you use orapki tools from any oracle server and display the wallet content

**Comment by sijms** [comment]
as you see no credentials
only 
User certificates
Trusted Certificates

these used for secure TCP connection
but no credentials in the wallet

**Comment by giridharanram** [comment]
> you have user name and password
> wallet support passwordless connection

Yes I have username and password

```
sqlQuery := "oracle://admin/*****@********.oraclecloud.com:1522/*******_high.adb.oraclecloud.com"
	sqlQuery += "?TRACE FILE=trace.log"
	sqlQuery += "&WALLET=/Users/giridharanramasamy/Downloads/Wallet_*****"
	conn, err1 := sql.Open("oracle", sqlQuery)
```

**Comment by giridharanram** [comment]
> as you see no credentials
> only
> User certificates
> Trusted Certificates
> 
> these used for secure TCP connection
> but no credentials in the wallet


okay got it.I have the username and password.So the wallet is used only to initiate TCPS connection?Is this SSL support mentioned here https://github.com/sijms/go-ora/issues/87?
Have you tried to connect to Oracle cloud ATP database?

**Comment by sijms** [comment]
you can add credentials to this wallet by 
```
mkstore -wrl <wallet_location> -createCredential <db_connect_string> <username> <password>
```

**Comment by sijms** [comment]
for example
```
mkstore -wrl <wallet_location> -createCredentials "(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = myserver1)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = db11g)))    user    password
```

**Comment by sijms** [comment]
read readme file 
## version 2.1.23

**Comment by sijms** [comment]
> for example
> 
> ```
> mkstore -wrl <wallet_location> -createCredentials "(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = myserver1)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = db11g)))    user    password
> ```

note: to modify the wallet you need both files **ewallet.p12, cwallet.sso** in the wallet directory
mkstore is a server tool same like orapki

**Comment by giridharanram** [comment]
I have added credentials using mkstore.
```
Oracle PKI Tool : Version 12.2.1.3.0
Copyright (c) 2004, 2017, Oracle and/or its affiliates. All rights reserved.

Requested Certificates: 
User Certificates:
Subject:        CN=8700EC6372A3418FA38A3CF8FF7844F7.52EF8AFD6BC744BE8FD8086254CDF3B8,DNQ=V1
Oracle Secret Store entries: 
oracle.security.client.connect_string1
oracle.security.client.password1
oracle.security.client.username1
Trusted Certificates: 
Subject:        CN=DigiCert Global Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
Subject:        C=US,ST=California,L=Redwood Shores,O=Oracle Corporation Autonomous Data Warehouse Cloud Self-signed CA,CN=Autonomous Data Warehouse Cloud CA
Subject:        CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US
giridharanramasamy@Giridharan-MacBook-Pro bin % 
```

wallet  download from cloud has tnsnames.ora file which has "(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)"

Now it is failing with error
```
read tcp 192.168.1.3:49885->192.29.8.32:1522: read: connection reset by peer
```
This is probably ATP database is allowing only TCPS connection?

**Comment by sijms** [comment]
> > as you see no credentials
> > only
> > User certificates
> > Trusted Certificates
> > these used for secure TCP connection
> > but no credentials in the wallet
> 
> okay got it.I have the username and password.So the wallet is used only to initiate TCPS connection?Is this SSL support mentioned here #87?
> Have you tried to connect to Oracle cloud ATP database?

I didn't try ATP database before but I think it will need TCPS for connection
actually I am working to add support for TCPS

**Comment by sijms** [comment]
> I have added credentials using mkstore.
> 
> ```
> Oracle PKI Tool : Version 12.2.1.3.0
> Copyright (c) 2004, 2017, Oracle and/or its affiliates. All rights reserved.
> 
> Requested Certificates: 
> User Certificates:
> Subject:        CN=8700EC6372A3418FA38A3CF8FF7844F7.52EF8AFD6BC744BE8FD8086254CDF3B8,DNQ=V1
> Oracle Secret Store entries: 
> oracle.security.client.connect_string1
> oracle.security.client.password1
> oracle.security.client.username1
> Trusted Certificates: 
> Subject:        CN=DigiCert Global Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
> Subject:        C=US,ST=California,L=Redwood Shores,O=Oracle Corporation Autonomous Data Warehouse Cloud Self-signed CA,CN=Autonomous Data Warehouse Cloud CA
> Subject:        CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US
> giridharanramasamy@Giridharan-MacBook-Pro bin % 
> ```
> 
> wallet download from cloud has tnsnames.ora file which has "(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)"
> 
> Now it is failing with error
> 
> ```
> read tcp 192.168.1.3:49885->192.29.8.32:1522: read: connection reset by peer
> ```
> 
> This is probably ATP database is allowing only TCPS connection?

correct this is because of TCPS
I am working on it now to add this feature and nearly it will be available

when finish I will reply in the issue #87 you can see this

**Comment by sijms** [comment]
you can close this issue now

**Comment by giridharanram** [comment]
> > > as you see no credentials
> > > only
> > > User certificates
> > > Trusted Certificates
> > > these used for secure TCP connection
> > > but no credentials in the wallet
> > 
> > 
> > okay got it.I have the username and password.So the wallet is used only to initiate TCPS connection?Is this SSL support mentioned here #87?
> > Have you tried to connect to Oracle cloud ATP database?
> 
> I didn't try ATP database before but I think it will need TCPS for connection
> actually I am working to add support for TCPS

okay Thanks for your work let me know if I can be of any help.
If possible We can catch up in some call.
