### ISSUE TITLE
error handling with ORA codes

### ISSUE THREAD

**Issue by volker-raschek** [sijms/go-ora#103]
Hi, 
I would like to do error handling by reacting to the returned error codes from Oracle. 

I have created a short demo project here, in which several attempts are made to create a table. From the second call I would like to handle the code ORA00955, but I don't know how to get the code with the lib. 

Could you please take a look at the project or possibly extend the documentation?

https://github.com/volker-raschek/golang-purego-oracle

Here are the steps
 
```bash
git clone https://github.com/volker-raschek/golang-purego-oracle
cd golang-purego-oracle
make start-oracle-xe 
sleep 180 # wait some seconds until database is ready
make run
```

Volker

**Comment by sijms** [comment]
actual I return the error as a message come from the server. and still I didn't make a special error class for the project
you can take the error text and split it to get the code.
As there is still missing important feature I concentrate on adding it and didn't start making specific error class

the error message is like this
`ORA-01403 no data found`
also the error code is return in the network structure and it is present in class SummaryObject.RetCode under network namespace

**Comment by sijms** [comment]
I add OracleError class that carry error message from the server 
the class contain ErrCode and ErrMsg
