### ISSUE TITLE
Oracle RAC connection

### ISSUE THREAD

**Issue by odilik** [sijms/go-ora#104]
Is there a way to connect to an Oracle RAC with two servers in failover mode, as JDBC ?

jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=server1)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=server2)(PORT=1521))(FAILOVER=on)(LOAD_BALANCE=on))(CONNECT_DATA=(SERVICE_NAME=MYRAC)))

**Comment by sijms** [comment]
the problem I don't have oracle RAC to test this function
did you try connection with the driver and receive any error message?
if yes can you share the trace.log file?

**Comment by odilik** [comment]
without a  RAC i can use a fake servername (fakeserver) for testing with JDBC.
The JDBC driver establishes the connection to myserver
jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=fakeserver)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=myserver)(PORT=1521))(FAILOVER=on)(LOAD_BALANCE=on))(CONNECT_DATA=(SERVICE_NAME=MYSN)))

The JDBC driver establishes the connection to myserver
jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=myserver)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=fakeserver)(PORT=1521))(FAILOVER=on)(LOAD_BALANCE=on))(CONNECT_DATA=(SERVICE_NAME=MYSN)))

in GO
var url string = "oracle://myuser:mypassword@" + "(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=fakeserver)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=myserver)(PORT=1521))(FAILOVER=on)(LOAD_BALANCE=on))(CONNECT_DATA=(SERVICE_NAME=MYSN)))" + "?TRACE FILE=trace.log"
conn, err := sql.Open("oracle", url)
if err != nil {
	fmt.Printf("error : %v\r\n", err)


i have only the following ouput (no trace file) :

error : empty SID and service name

**Comment by sijms** [comment]
the above code will not working because driver suspect you supply an url with option like this
`oracle://user:pass@server/service?option=value`
ok I can make a url option to let you specify other servers to connect to when connection to main server failed.
this will be in connect function.
and when you receive connection error during reading & writing process you need to connect again

is that ok for you?

**Comment by odilik** [comment]
yes, thanks a lot !

**Comment by sijms** [comment]
I made changes and push it
please test and commit
for usage read readme file version 2.2.9

**Comment by odilik** [comment]
tests ok
you can close the issue
