### ISSUE TITLE
Passing type DateTime

### ISSUE THREAD

**Issue by RafaMnzs** [sijms/go-ora#106]
Hii...  i have a doubt, 

I have a query that I need to pass a date, but the result doesn't come, however when I update the dbever the result is shown. 

the result: **ORA-00933: SQL command not properly ended**

SELECT SUM(XX.VALORVLRNF) VENDA,
SUM((XX.VALORICMS+XX.VALORPIS+XX.VALORCOFINS)+(XXX.CMULTVLRNF-(XXX.CMULTCREDICMS+XXX.CMULTCREDPIS+XXX.CMULTCREDCOFINS)+XXX.CMULTIPI)) CUSTOS, 
SUM(XX.VALORVLRNF-((XX.VALORICMS+XX.VALORPIS+XX.VALORCOFINS)+(XXX.CMULTVLRNF-(XXX.CMULTCREDICMS+XXX.CMULTCREDPIS+XXX.CMULTCREDCOFINS)+XXX.CMULTIPI))) LUCRO 
FROM MRL_LANCTOESTOQUE XX, MRL_PRODUTOEMPRESA XXX, MAP_PRODUTO PXP
WHERE XX.SEQPRODUTO = XXX.SEQPRODUTO
AND XX.NROEMPRESA = XXX.NROEMPRESA
AND XX.SEQPRODUTO = PXP.SEQPRODUTO
AND XXX.SEQPRODUTO = PXP.SEQPRODUTO
AND XX.CODGERALOPER IN (SELECT XC.CODGERALOPER FROM MAX_CODGERALOPER XC WHERE XC.TIPCGO = 'S' AND XC.TIPUSO = 'E' AND XC.TIPDOCFISCAL = 'C') 
AND XX.DTAENTRADASAIDA = **'16-aug-2021'** // DATE 
AND XX.NROEMPRESA = 7;

**Comment by sijms** [comment]
remove ';' at the end of the stmt

**Comment by FrauElster** [comment]
This is very unintuitive. Took me 2 hours to find this behaviour. This should be changed
