### ISSUE TITLE
Special character # not parsed in password on go_ora/v2

### ISSUE THREAD

**Issue by MS-24** [sijms/go-ora#107]
Previously raised issue : https://github.com/sijms/go-ora/issues/48

Tried as suggested in above mentioned issue . Worked in older version but failed in V2. Is there any alternative?
Also are there are any other special characters could cause the same issue already identified?
Is the same problem identified for the encryption/vault methods?
Could you please provide clarifications so that I could implement this in my application?

Thanks in advance !!

**Comment by MS-24** [comment]
> Previously raised issue : #48
> 
> Tried as suggested in above mentioned issue . Worked in older version but failed in V2. Is there any alternative?
> Also are there are any other special characters could cause the same issue already identified?
> Is the same problem identified for the encryption/vault methods?
> Could you please provide clarifications so that I could implement this in my application?
> 
> Thanks in advance !!

More info on Error:
DB connection successful using sql.Open() 
Then the below code is failing with mentioned error.
**code** 
`sqlTxt := "select sysdate from dual"
	stmt, err1 := db.Query(sqlTxt)
	if err1 != nil {
		log.Print(fmt.Errorf("Unable to retrieve data: %v", err1))
		return
	}`
**The error was :**
` 2021/09/01 14:32:41 Unable to retrieve data: message code error: received code 23 and expected code is 8`

**Comment by sijms** [comment]
now you can do the following
```
urlOptions := map[string] string {
    "TRACE FILE": "trace.log",
}

// now you can pass any special character to the function in server, service, username, password or option value
// you can pass nil to urlOptions
databaseURL := go_ora.BuildUrl("server:port", "service", "user", "password", urlOptions)

conn, err := sql.Open("oracle", databaseURL)
```

**Comment by MS-24** [comment]
> urlOptions := map[string] string {
>     "TRACE FILE": "trace.log",
> }

Thanks for the response 
After making changes it is causing different issue.

My input: 
username  = myDBUSER
password  = passwrd#
hostnaem = myserverName
port          = 61910
servicename= myService

```
2021/09/03 11:52:18 oracle://myDBUSER:passwrd%23@myserverName%3A61910/myService?TRACE FILE=trace.log
2021/09/03 11:52:18 DB Connection is set
2021/09/03 11:52:18 Unable to retrieve data: parse "oracle://myDBUSER:passwrd%23@myserverName%3A61910/myService?TRACE FILE=trace.log": invalid URL escape "%3A"
```
Looks like it is adding escape character for ":" between "server:port" .

Thanks!!

**Comment by sijms** [comment]
I need to add extra input parameter for port

**Comment by sijms** [comment]
I add extra parameter for port you can test now it is working
