### ISSUE TITLE
TTC error: received code 50 during stmt reading

### ISSUE THREAD

**Issue by LawyZheng** [sijms/go-ora#108]
Thanks for go-ora.

I got this error `TTC error: received code 50 during stmt reading` when I use stmt.Query() for rows.
This happened in my production environment, so I couldn't get more details either.
What should I do?

Oracle Version: 10.2.0.4.0
go-ora Version: v2.2.2

**Comment by sijms** [comment]
can you tell me the form of your query and data type of your columns

**Comment by sijms** [comment]
also upgrade go-ora to latest version
