### ISSUE TITLE
Rounding error

### ISSUE THREAD

**Issue by simulot** [sijms/go-ora#11]
Hi,
I'm doing another test with the package:

```
SELECT count(*) FROM help
``` 

This show a rounding error:
```
go run .
Topics:  918.9999999999999
```

I was expecting 919.
Thanks for your work

**Comment by sijms** [comment]
use int or in64
ad don't use float

**Comment by simulot** [comment]
It was actually a string. 
Got it.

**Comment by simulot** [comment]
Sorry, 
Using an in64 this gives; 
```
sql: Scan error on column index 0, name "COUNT(*)": converting driver.Value type float64 ("918.9999999999999") to a int64: invalid syntax
exit status 4294967295
```

**Comment by sijms** [comment]
### this code is working without error
    conn, err := sql.Open("oracle", "connection string")
	if err != nil {
		fmt.Println(err)
		return
	}
    defer conn.Close()
    stmt, err := conn.Prepare("select count(*) from visits where visit_id between 1000 and 2100")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer stmt.Close()
	results, err := stmt.Query()
	if err != nil {
		fmt.Println(err)
		return
	}
	defer results.Close()
	var count sql.NullInt64
	for results.Next() {
		err = results.Scan(&count)
		if err != nil {
			fmt.Println(err)
			return
		}
	}
	fmt.Println("count: ", count)

**Comment by simulot** [comment]
It depends on the number....
I have tested following for testing a list of integers. The first value is scanned as a string, the second as an integer.

``` go
func main() {
	conn, err := sql.Open("oracle", "oracle://system:oracle@192.168.10.10/xe")
	OKorDie(err)
	defer conn.Close()

	stmt, err := conn.Prepare(`with inc (N) as (
			select 1 N from dual
			union all
			select N+1 N from inc where N <100
		) 
		select N, N as N2 from INC
		`)
	OKorDie(err)
	defer stmt.Close()

	rows, err := stmt.Query()
	OKorDie(err)
	defer rows.Close()

	for rows.Next() {
		var N string
		var N2 int64
		err = rows.Scan(&N, &N2)
		fmt.Println("N: ", N, " N2:", N2, "Err:", err)
	}
}
```

And this gives:
```
N:  1  N2: 1 Err: <nil>
N:  2  N2: 2 Err: <nil>
N:  3  N2: 3 Err: <nil>
N:  4  N2: 4 Err: <nil>
N:  5  N2: 5 Err: <nil>
N:  6  N2: 6 Err: <nil>
...
N:  60  N2: 60 Err: <nil>
N:  60.99999999999999  N2: 0 Err: sql: Scan error on column index 1, name "N2": converting driver.Value type float64 ("60.99999999999999") to a int64: invalid syntax
N:  62  N2: 62 Err: <nil>
N:  62.99999999999999  N2: 0 Err: sql: Scan error on column index 1, name "N2": converting driver.Value type float64 ("62.99999999999999") to a int64: invalid syntax
N:  64  N2: 64 Err: <nil>
N:  65  N2: 65 Err: <nil>
```

Using sql.NullInt64 doesn't help.

**Comment by sijms** [comment]
I make a commit that solve the problem which is:
when server send 0 for precision and 0 for scale I should make precision 38 and scale 0

**Comment by simulot** [comment]
Great, this works!
Thanks

**Comment by sijms** [comment]
sorry for writing on closed issue.
about this script:
```
 with inc (N) as (
	select 1 N from dual
	union all
	select N+1 N from inc where N <100
) 
select N, N as N2 from INC
```
you expect type int64

and this script:
`select 2*1/3 from dual`
you expect type float64

but actually the server deal same on both situation it send precision = 0 and scale = 0xFF
which is something like decimal ==> float64

**the idea is all this equation number (doesn't have a column description) will 
interpreted in oracle as decimal ==> float64 thus in you equation above you 
need to get the value with float64 and convert to int64**
