### ISSUE TITLE
[question] password in connection string

### ISSUE THREAD

**Issue by juev** [sijms/go-ora#111]
Hello,

I trying to use go-ora for query my database. But I cannot to connect.

I have password, which contains symbols like `:/{}()` and etc. And if I use connection string like:
```plain
"oracle://user:pass@server1/service"
```

with my password I got errors:
```plain
parse \"oracle://user:P\": invalid port \":P\" after host
```
or
```plain
parse \"oracle://user2:password\": invalid port \":password\" after host
```

How I can to use passwords in login string?? :(

**Comment by sijms** [comment]
did you use 
`go_ora.BuildUrl(server, port, service, user, password, nil)`

**Comment by juev** [comment]
Thank you very much!
