### ISSUE TITLE
Occasional critical errors

### ISSUE THREAD

**Issue by gorandumic** [sijms/go-ora#112]
Hi,

we experience **occasional** errors from the library from time to time when fetching large datasets in iterations:
![image](https://user-images.githubusercontent.com/75610359/135272863-2f303e50-dfa3-4908-b538-ae6ef85d752b.png)

or:
![image](https://user-images.githubusercontent.com/75610359/135272935-c6d758dc-e64f-4bde-8c9e-55e44c7ee50e.png)

Did you get anything like this? The dataset we're using has about 500k records, about 10 columns of regular types - some integers, some characters and a timestamp, nothing special.

Any thoughts? This is probably not something we would like to put in production in this stage, so any help would be appreciated.

**Comment by sijms** [comment]
I didn't get anything like this before but I will try same the condition many time to produce the error and see the cause

**Comment by gorandumic** [comment]
Nah, it's random. We didn't find any patterns in it, so I would say it's not related to data itself. 

Here's another one that keeps popping up:
![image](https://user-images.githubusercontent.com/75610359/135438507-76719042-c465-4633-82f3-14a30de1136e.png)

**Comment by sijms** [comment]
what value of prefetch_rows you use?

**Comment by gorandumic** [comment]
We tried it all, from 1000 to 10000

**Comment by sijms** [comment]
this is what I expect
I will use same prameter and see where is the problem and solve

**Comment by gorandumic** [comment]
ok, so it happens with high value of prefetch_memory. Anything higher than 100 causes serious instability to the driver(!). Value 50 proved to be optimal in our case:
prefetch_rows=5000&prefetch_memory=50

With this set, the performance is so far stable. Will keep you posted after a few days.

**Comment by sijms** [comment]
do you have any column with CLOB or BLOB?

**Comment by gorandumic** [comment]
See my original comment:
"some integers, some characters and a timestamp, nothing special."

**Comment by sijms** [comment]
I use code like this
```
func getResults(conn *sql.DB) error {
	rows, err := conn.Query(
		`SELECT result_id, visit_id, group_id, item_id, operation_id, result_data1,
result_data2, result_data3, result_data4, result_text, row_index, page_id, print_number, 
last_modification, method_id, reffered_to_id, add_date, status_id, panel_id, 
test_id, bill_id, pk_no, edit_by, signed_by, report_info_id
from results`)
	if err != nil {
		return err
	}
	var (
		result_id sql.NullInt64
		visit_id sql.NullInt64
		group_id sql.NullInt64
		item_id sql.NullInt64
		operation_id sql.NullInt64
		result_data1 sql.NullFloat64
		result_data2 sql.NullFloat64
		result_data3 sql.NullFloat64
		result_data4 sql.NullFloat64
		result_text sql.NullString
		row_index sql.NullInt64
		page_id sql.NullInt64
		print_number sql.NullInt64
		last_modification sql.NullTime
		method_id sql.NullInt64
		refferal_id sql.NullInt64
		add_date sql.NullTime
		status_id sql.NullInt64
		panel_id sql.NullInt64
		test_id sql.NullInt64
		bill_id sql.NullInt64
		pk_no sql.NullInt64
		edit_by sql.NullInt64
		signed_by sql.NullInt64
		//printed_result []byte
		report_info_id sql.NullInt64
	)
	index := 0
	for rows.Next() {
		err = rows.Scan(&result_id, &visit_id, &group_id, &item_id, &operation_id, &result_data1, &result_data2,
			&result_data3, &result_data4, &result_text, &row_index, &page_id, &print_number, &last_modification,
			&method_id, &refferal_id, &add_date, &status_id, &panel_id, &test_id, &bill_id, &pk_no, &edit_by,
			&signed_by, &report_info_id)
		if err != nil {
			return err
		}
		index ++
	}
	if rows.Err() == nil {
		fmt.Println("Number of results: ", index)
	}
	return rows.Err()
}
```
setting prefetch_rows from 1000 - 60000 no errors occur
result is like this
`Number of results:  2995388`
when I use 70000 and more I get this error from the server 
`ORA-03146: invalid buffer length for TTC field`
my server is 12.2 c

**Comment by sijms** [comment]
what is database charset

**Comment by gorandumic** [comment]
I sent you an email.

**Comment by sijms** [comment]
actually it support Prefetch row only no prefetch memory
according to official C# driver prefetch rows is calculated automatically from the following equation:

noOfRowsToFetch = (int) (m_fetchSize / (long) this.m_maxRowSize) + 1;

where m_fetchSize is fixed value = 0x20000
and maxRowSize is calculated from the following equation:

```
m_maxRowSize = m_maxRowSize + m_numOfLOBColumns * Math.Max(86, 86 + (int) lobSize) + m_numOfLONGColumns * Math.Max(2, longSize) + m_numOfBFileColumns * 86;
```

**_According to my testing:_**
setting of PrefetchRows to 1000 or less is better for stability
you can use higher values when working on local network and with small and medium size query
if you have LOB, CLOB, LONG or BFILE in you query PreFetchRows better to be 25

**Comment by gorandumic** [comment]
Agreed.  Tested on several occasions, PrefetchRows of 1000 is stable, however, the performance is obviously degraded. So yeah, for local databases it should be high, for remote ones it should be 1000 or less.

**Comment by LawyZheng** [comment]
The `TTC error` happened to me at once.
Any solution to fix it ?

**Comment by sijms** [comment]
can you write your SQL string and go code

**Comment by LawyZheng** [comment]
SQL string is like this : 
```
  SELECT /*+rule+*/ *
  FROM SV_WuJi_Instances
  WHERE StudyUid IN (
          SELECT max(StudyUid)
          FROM SV_WuJi_Instances
                  WHERE ACCESSIONNUMBER IN (Translate(:1 USING CHAR_CS))
          GROUP BY ACCESSIONNUMBER)
```

My go code is like this:

```
	stmt, err := db.Conn.Prepare(sqlString)
	if err != nil {
		log.Error("Prepare Sql Error -> ", err)
		return rdata, err
	}
	defer stmt.Close()

	rows, err := stmt.Query(args...)
	if err != nil {
		log.Error("Query Sql Error -> ", err)
		return rdata, err

	}
	defer rows.Close()

	for rows.Next() {
           ......
        }
```

**Comment by sijms** [comment]
the error that occur with High PrefetchRows value in 2 condition:
1- remote database or slow connection
2- query that contain lob like issue #123

you write above that the error occur once only is this correct?

**Comment by LawyZheng** [comment]
Actually, I mean it occurs when I connected to ONE database for ANY SQL query.
It's my productive environment database provided by third party.
So I can't get more information about the table structure or other details.

**Comment by gorandumic** [comment]
@LawyZheng 
Please answer these questions, this will help narrow down the possible cause:
- is your production database remote, meaning not in the same machine / network as the client application querying it (I would assume - yes)? What is the ping time to the server?

- do you use prefetch_rows parameter in connection string? 
If yes: what is the value of it, 
if not: try to set it to 50, 100, 1000 and see whether it fixes your problem.

- when you execute a query, is one of the columns BLOB or CLOB ? 
I would assume you know what you are querying or you can get this info from an administrator.

**Comment by LawyZheng** [comment]
@gorandumic 

Thanks for the reply.

Unfortunately, I'm only able to answer the second question right now.
I didn't use  prefetch_rows in my connection string, and I will try to use it in my next step.
BTW, is there any introduction about how to use it?

Concerning other questions, I can't get the answers either, since I don't have access right to my productive database.  But I will notify you as soon as I get this info from the administrator.

**Comment by gorandumic** [comment]
@LawyZheng and please include some screenshots to begin with to help us understand what exactly are you doing when you get TTC errors, what client are you using, is it:
your custom Go code executed locally
 or
you're using an application (for which you don't know what queries it sends to the database but gets TTC errors)
