### ISSUE TITLE
Method NewConnection takes a lot of CPU time

### ISSUE THREAD

**Issue by gorandumic** [sijms/go-ora#116]
I noticed that NewConnection (connection.go) method takes A LOT of CPU time. I profiled it, the problematic line is 
User, err := user.Current()

Did you happen to notice that too? 

So this is the outter statement I'm focusing on:
![image](https://user-images.githubusercontent.com/75610359/136708337-88ba0834-d578-4a38-b16c-3c9bd134cd30.png)

These are the profile results I got, seems CGO library is being called for retrieving the username and it takes forever:
![image](https://user-images.githubusercontent.com/75610359/136708421-6147787e-71cb-4206-bf52-2a5e9401f4e7.png)
![image](https://user-images.githubusercontent.com/75610359/136708429-008c6c73-3575-4b23-94bf-6e1a3ed5cec9.png)

The flame chart,  NewConnection calls user.Current which calls sync(*Once), etc .... :
![image](https://user-images.githubusercontent.com/75610359/136708434-76c3fab8-e98f-47d8-ad49-9af9ef09992d.png)

Is there any alternative for fetching the username?

**Comment by gorandumic** [comment]
Adding what I just found regarding the "user" package:

![Screenshot_20211010-222607_Chrome.jpg](https://user-images.githubusercontent.com/75610359/136712090-3a6e007a-53f2-4eef-abac-fd4a4d268dac.jpg)

**Comment by sijms** [comment]
from me calling NewConnection take 2.716336ms
system macOS 11.6

**Comment by gorandumic** [comment]
Right?? I also get values above 2sec. Too much. Just to fetch the username..

**Comment by gorandumic** [comment]
Ok, i conclude this is definitely not a driver issue, can be resolved by overriding the need for CGO libraries by using CGO_ENABLED = 0 flag when building your app. @sijms you can close this issue
