### ISSUE TITLE
driver doesn't support failover

### ISSUE THREAD

**Issue by luxiangqing** [sijms/go-ora#124]
the current connection is established on node 2. If the node is down, the connection cannot be automatically failover to node1, c client and jdbc can automatically failover

> test database error: write tcp client_ip:50615->node2_ip:1521: wsasend: An established connection was aborted by the software in your host machine.

**Comment by captain-corgi** [comment]
My boss is considering using this driver because it doesn't support failover yet. 
Do you have any plan for this issue? If yes, please let me know.
Thank you!

**Comment by najam-awan-db** [comment]
I am also super interested in this. on production env we have running database with failover once my code migrated to production it couldnt handle/parse the long wired connection string. one guy from prod team help us by changing the connection string to one database to make it work for now.

**Comment by sijms** [comment]
I will start working on this issue
but the problem I don't have oracle RAC or nodes to test 
I think first place to start is this code in  [session.go](https://github.com/sijms/go-ora/blob/7a873e685170c84fe1125bb8132951f3ec58dc0f/v2/network/session.go#L289)
```golang
for loop {
	host = connOption.GetActiveServer(false)
	if host == nil {
		return errors.New("no available servers to connect to")
	}
	addr := host.networkAddr()
	if len(session.Context.ConnOption.UnixAddress) > 0 {
		session.conn, err = dialer.DialContext(ctx, "unix", session.Context.ConnOption.UnixAddress)
	} else {
		session.conn, err = dialer.DialContext(ctx, "tcp", addr)
	}

	if err != nil {
		connOption.Tracer.Printf("using: %s ..... [FAILED]", addr)
		host = connOption.GetActiveServer(true)
		if host == nil {
			break
		}
		continue
	}
	connOption.Tracer.Printf("using: %s ..... [SUCCEED]", addr)
	connected = true
	loop = false
}
```

the line 
```golang
host = connOption.GetActiveServer(false)
if host == nil {
       return errors.New("no available servers to connect to")
}
```
if failover is active this line should always return a host by cycle hosts over and over
is this correct?

**Comment by sijms** [comment]
I add support for failover please test and write your feedback

**Comment by najam-awan-db** [comment]
Problem is our oracle rack this is available only in prod and if its exploding in prod next release might take 1 or 2 weeks.
