### ISSUE TITLE
How to set “NLS_LANGUAGE“ ?

### ISSUE THREAD

**Issue by yxsh** [sijms/go-ora#13]
Application's runtime-environment had “NLS_LANGUAGE“ flag, but It did't work.

**Comment by sijms** [comment]
no need to set NLS_LANGUAGE

**Comment by yxsh** [comment]
golang default charset is utf-8,
Oracle database is the other (GBK,ISO etc...) 
So the query results are "??????" ,that is error。
shell:
export $NLS_LANG=AMERICAN_AMERICA.ZHS16GBK
works well on the other oracle client(sqlplus).
 
thx.

**Comment by sijms** [comment]
sorry for late answer I was so busy

in my driver you can see the following:
**first** when you call open function the function will get charset from the server

`conn.strConv = converters.NewStringConverter(conn.tcpNego.ServerCharset)`

**second** when you get string from the server it will be converted

    case NCHAR:
      dataSet.currentRow[x] = stmt.connection.strConv.Decode(temp)

decode function simply convert bytes come from the server to utf-8 according to conn.tcpNego.ServerCharset
thus no need to set NLS_LANG

if the problem persist this means error in conversion function and to detect this I need the actual NLS_LANG and sample bytes return from the server to test the conversion

**Comment by yxsh** [comment]
charset code is 852（0×354),
converters.NewStringConverter miss it.
which the bytes shoud I provide? 

thx.

**Comment by sijms** [comment]
I add commit that contain support for you charset 

please test and feedback

**Comment by yxsh** [comment]
This code is not very good,
English words are normal and Gbk (852) characters are incorrect.
Use this tool: 
github.com/axgle/mahonia 
transform gbk to utf-8. It works fine.
But exec update sql , the data is also incorrect.

thx.

**Comment by sijms** [comment]
sorry I make a mistake  i search for code page 852 
but your charset is:

zhs16gbk | GBK 16-bit Simplified Chinese

I will change the code and message you here

**Comment by sijms** [comment]
I change the code so you can make encode and decode outside the driver for unsupported charset like this
you receive the string data in scan then convert to bytes
```
var text string
 scan(&text)
 temp = []byte(text)
```

and use temp in the library above to get the correct string

**Comment by yxsh** [comment]
well done

**Comment by sijms** [comment]
note parameter sent to database is sent with charset 871 = utf8 thus no need to convert parameters

**Comment by sijms** [comment]
Hi yxsh
I add support for CHARSET 852  zhs16gbk you can test and feedback

**Comment by yxsh** [comment]
Hi, 
the clob type was worked fine. 
char,varchar and varchar2 should be converted (gbk -> utf-8).
