### ISSUE TITLE
runtime panic: out of memory

### ISSUE THREAD

**Issue by majj** [sijms/go-ora#138]
in [session.go](https://github.com/sijms/go-ora/blob/master/v2/network/session.go) line: body := make([]byte, length)
`
			var length uint32
			if session.Context.handshakeComplete && session.Context.Version >= 315 {
				length = binary.BigEndian.Uint32(head)
			} else {
				length = uint32(binary.BigEndian.Uint16(head))
			}
			length -= 8
			body := make([]byte, length)  // <--
			index := uint32(0)

`

when accidentally get a wrong length(4294967296 = 0x100000000) to make a slice, the runtime panic:

runtime: VirtualAlloc of 4294967296 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw({0x7e8fb4, 0xc096de4000})
        e:/go/src/runtime/panic.go:1198 +0x76
runtime.sysUsed(0xc0030d2000, 0x100000000)
        e:/go/src/runtime/mem_windows.go:83 +0x1c9
runtime.(*mheap).allocSpan(0xf0be20, 0x80000, 0x0, 0x1)
        e:/go/src/runtime/mheap.go:1268 +0x3a5
runtime.(*mheap).alloc.func1()
        e:/go/src/runtime/mheap.go:913 +0x69
runtime.systemstack()
        e:/go/src/runtime/asm_amd64.s:383 +0x4e

goroutine 1 [running]:
runtime.systemstack_switch()
        e:/go/src/runtime/asm_amd64.s:350 fp=0xc0007e0b60 sp=0xc0007e0b58 pc=0x4
61380
runtime.(*mheap).alloc(0x0, 0x29183f00, 0x0, 0x0)
        e:/go/src/runtime/mheap.go:907 +0x73 fp=0xc0007e0bb0 sp=0xc0007e0b60 pc=
0x425c93
runtime.(*mcache).allocLarge(0x8, 0xfffffff8, 0x10, 0x1)
        e:/go/src/runtime/mcache.go:227 +0x89 fp=0xc0007e0c10 sp=0xc0007e0bb0 pc
=0x416509
runtime.mallocgc(0xfffffff8, 0x7614e0, 0x1)
        e:/go/src/runtime/malloc.go:1082 +0x5c5 fp=0xc0007e0c90 sp=0xc0007e0c10
pc=0x40cda5
runtime.makeslice(0xc0000ca098, 0xc001198270, 0x0)
        e:/go/src/runtime/slice.go:98 +0x52 fp=0xc0007e0cb8 sp=0xc0007e0c90 pc=0
x4496b2
github.com/sijms/go-ora/v2/network.(*Session).readPacket.func1()
        C:/Users/....../go/pkg/mod/github.com/sijms/go-ora/v2@v2.2.15/n
etwork/session.go:459 +0x105 fp=0xc0007e0d70 sp=0xc0007e0cb8 pc=0x6e2b65
github.com/sijms/go-ora/v2/network.(*Session).readPacket(0xc0000e4600)
        C:/Users/....../go/pkg/mod/github.com/sijms/go-ora/v2@v2.2.15/n
etwork/session.go:506 +0x54 fp=0xc0007e0e08 sp=0xc0007e0d70 pc=0x6e2174
github.com/sijms/go-ora/v2/network.(*Session).read(0xc0000e4600, 0x3)
        C:/Users/....../go/pkg/mod/github.com/sijms/go-ora/v2@v2.2.15/n
etwork/session.go:381 +0x39 fp=0xc0007e0e60 sp=0xc0007e0e08 pc=0x6e1c79
github.com/sijms/go-ora/v2/network.(*Session).GetClr(0xc0000e4600)

**Comment by sijms** [comment]
what is the cause of wrong length

**Comment by majj** [comment]
SQL="SELECT A.* FROM \n(SELECT
 C.*, ROWNUM RN FROM BAAN.TWHINA114307 C WHERE \"T$ITEM\" IN ('         Q1840820
FDD') and ROWNUM <= 6000) A \nWHERE A.RN >= 3001 "

Oracle Database：

select * from v$version;

Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
PL/SQL Release 12.1.0.2.0 - Production
"CORE	12.1.0.2.0	Production"
TNS for Linux: Version 12.1.0.2.0 - Production
NLSRTL Version 12.1.0.2.0 - Production


----------------------------
The runtime panic happened several times with OOM, and one time it got 4GB memory but no error and further response.

Thanks！

**Comment by sijms** [comment]
### Don't use `*`
replace 
`SELECT * FROM TABLE`
with 
`SELECT col1, col2, col3 FROM TABLE`

**Comment by majj** [comment]
There are more then 25000 tables in the Application and many of the tables have more then 250 columns，we just want to dump the data from Oralce to parquet files and then load them to Hive.

When we dumped 20 million records, the runtime panics happened 1-5 times.

Is this the same issue with 'the packet received is not data packet' ?

'the packet received is not data packet' happened too when we test the client.

**Comment by majj** [comment]
This is probably caused by a bad network. The frequency of OOM varies greatly from system to system.

**Comment by sijms** [comment]
you tell me a lot of issue can you divide them to easily investigate them.
if you have a lot of rows (20 million) then you need to set `PREFETCH_ROWS=value` this value < 1000

**Comment by majj** [comment]
Thanks! It could be the same issue with #112. after I changed PREFETCH_ROWS from 3000 to 100, it's work well. even set to 150, it panic.

there isn't BLOB or CLOB column in the table. and all those issues caused by the same table query, just with different paging.

but one strange thing:

application 1/Oracle1(Linux) and application 2/Oracle2(Windows) locate in different server room.

when exporting data, both have the same PREFETCH_ROWS =3000 to fetch.

- the ora client got about 25-50% runtime panic(OOM or suddenly memory allocated : 500M，1G，2G，4G
 ) per table query with application 2/Windows even in the same server room.

- but for application 2(linux), the two server rooms are 10+ kilometers apart, but it only got less then 5% runtime panic.

May this be an OS related matter?

--
application 1: TNS for Linux: Version 12.1.0.2.0 - Production
application 2: TNS for 64-bit Windows: Version 12.2.0.1.0 - Production

**Comment by sijms** [comment]
the client is talking to oracle through network interface
network interface may varies from version to version but not related to operating system of the server
when i test client get large data over slow network with high values of prefetch_rows I am facing **read block** and the program stuck.

you get error in interpreting packet content. I feel something strange (a bug or something) about this.
if you can containment the error in some queries and make an example code that induce the error may be we will find the bug

**Comment by sijms** [comment]
close due to repeat #112
