### ISSUE TITLE
Connection String

### ISSUE THREAD

**Issue by basement199** [sijms/go-ora#14]
Thanks for this work.  

 I'm using another package today to connect to Oracle.   Here is how I  connect:

oraProd := "user/password@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=dbs001.cores.com)(PORT=53701))(CONNECT_DATA=(SID=DBSPROD)))"

db, err := sql.Open("oci8", oraProd)

Can you give me the syntax I would use to construct the connection string for your package?

thanks,

**Comment by fleshin** [comment]
Try simething like this:  user:passwd@dbs001.cores.com:53701/DBSPROD

**Comment by sijms** [comment]
read the description in code page

**Comment by basement199** [comment]
thanks,
