### ISSUE TITLE
Column type wrongly reported by method ColumnTypeDatabaseTypeName

### ISSUE THREAD

**Issue by Tracnac** [sijms/go-ora#140]
Hi Samy,

Found a small bug.
The dataset method ColumnTypeDatabaseTypeName and ParameterInfo.DataType report wrong column type for nchar, varchar2 and nvarchar2.

For this table the type return by this method are: CHAR, CHAR, NCHAR, NCHAR witch is not the reflect of the table.

Thanks Yvan

```sql
	create table t_char ( col1 char(32), col2 nchar(32), col3 varchar2(32), col4 nvarchar2(32));
	insert into t_char values ('char','nchar','varchar2','nvarchar2');
        commit
```

Test program:

```go
package main

import (
	"fmt"
	"os"

	go_ora "github.com/sijms/go-ora/v2"
)

func main() {
	var (
		err error
	)

	var MsgErrorDie = func(msgText string, msgError error) {
		if msgError != nil {
			fmt.Println(msgText, msgError)
			os.Exit(1)
		}
	}

	DB, err := go_ora.NewConnection("oracle://tracnac:tracnac@192.168.122.90/xepdb1")
	MsgErrorDie("URL error: ", err)

	err = DB.Open()
	MsgErrorDie("DB open error: ", err)
	defer DB.Close()

	// create table t_char ( col1 char(32), col2 nchar(32), col3 varchar2(32), col4 nvarchar2(32));
	// insert into t_char values ('char','nchar','varchar2','nvarchar2');
	// commit
	
	stmt := go_ora.NewStmt("select col1,col2,col3,col4 from t_char", DB)
	defer stmt.Close()

	rows, err := stmt.Query_(nil)
	MsgErrorDie("Query error: ", err)
	defer rows.Close()

	for k, v := range rows.Columns() {
		fmt.Println(v, rows.ColumnTypeDatabaseTypeName(k))
	}
}

```

Output:
```
[tracnac@blackhole test(char:2/36)]$ go run test.go 
COL1 CHAR
COL2 CHAR
COL3 NCHAR
COL4 NCHAR
[tracnac@blackhole test(char:2/36)]$
```

**Comment by sijms** [comment]
not a bug this is the data coming from the server
please note that oracle server see **_varchar2_** and _**nvarchar2**_ data types as one data type = **_NCHAR_** = 1 and the difference is in column metadata value called **_CharsetForm_** in case of _**varchar2**_ = 1 and **_nvarchar2_** = 2

also char and nchar = CHAR = 96 is same as above

**Comment by Tracnac** [comment]
Happy new year.

Thanks for the explanation, maybe it may be better to deal with this from the method side, we expect to have the correct Oracle type without going deeper into the dataset struct, what do you think ?

Yvan

**Comment by sijms** [comment]
Happy new year.

In real world I think no need to differentiate between `varchar2` and `nvarchar2` because they are translated to same data type `string` in go.
if you pass a parameter to driver you can tell it what type of string you pass by casting it to `go_ora.NVarChar` in case of `nvarchar2`
