### ISSUE TITLE
ORA-28041: Authentication protocol internal error

### ISSUE THREAD

**Issue by lcvvvv** [sijms/go-ora#143]
Connect to Oracle using SID

```
conn, err := sql.Open("oracle", "oracle://user:pass@192.168.100.11:1521/ORCL?SID=ORCL
```

Response:
```
ORA-28041: Authentication protocol internal error
```

I using navicat connect is ok
<img width="689" alt="图片" src="https://user-images.githubusercontent.com/49975427/149055546-3fbd1eb6-8d0b-40c4-948f-1a3ac80bafda.png">

**Comment by sijms** [comment]
this is not related to SID 
may be password expire
