### ISSUE TITLE
string to long to a CLOB field

### ISSUE THREAD

**Issue by FJM-Slade** [sijms/go-ora#146]
Hi,

I have a table in an Oracle DB (version Oracle Database 19c Enterprise Edition Release 19.0.0.0.0).
The type of one the fields is a CLOB.

When I'm trying to insert a string with a length that exceeds more than 8200 (approximately) I get a 
"ORA-01461: can bind a LONG value only for insert into a LONG column". if I split the value and put a string with an inferior value all works fine.

For the insertion I'm putting the payload (in a string) of the result of dummy method GET [https://jsonplaceholder.typicode.com/albums]

var connStr
conn, err := goOra.NewConnection(connStr)
err = conn.Open()
inserting := "INSERT INTO my_table (txt_c_lob) values (:parm1) "
stmt := goOra.NewStmt(inserting, conn)
str := <value from https://jsonplaceholder.typicode.com/albums >
stmt.AddParam("parm1", str, len(str), goOra.Input)
_, err = stmt.Exec(nil)

then it occurs the:
"ORA-01461: can bind a LONG value only for insert into a LONG column"

I don't know for sure, but I think that the problem is in the command.go, in setting the defaultStmt struct.

Thanks

**Comment by sijms** [comment]
this error means that you try to insert a value that is bigger than the column capacity
ok no problem I add an example that create table with CLOB then insert the value from your example file then drop the table
please test in your environment and compare the code with your code

**Comment by FJM-Slade** [comment]
Yes, I've done a workaround by splitting the string in chunks each one with the max allowed size.
With each chunk I've customised the statement with a concat function (...  concat (:parm1, parm2) ).
My alert here is because using other drivers/platforms like jdbc this size issue, with the same string length, wasn't a problem.

**Comment by sijms** [comment]
I cannot understanding what you mean by increasing the size of the string?
if you need to create a string with specific size in go 
`strings.Repeat("0", 8000)`
the error:
`"ORA-01461: can bind a LONG value only for insert into a LONG column"`
is not related to the size of the parameter you pass but the column size in the oracle table.
as you see in the example I can insert the data in the file with one call of `conn.Exec`

**Comment by FJM-Slade** [comment]
Thanks for your answer but I think there is a problem with the size parameter.

Your example works fine with one CLOB field. So I done the following:

1. created the table with an extra clob field:
`sqlText := `CREATE TABLE GOORA_TEMP_VISIT(
	VISIT_ID	number(10)	NOT NULL,
	VISIT_DATA  CLOB,
	VISIT_DATA2  CLOB,
	PRIMARY KEY(VISIT_ID)
	)``

2.  then in the insertData function, changed the first parameter : 

`import goOra "github.com/sijms/go-ora/v2"`

...

`func insertData(connStr string) error {
	t := time.Now()
	val, err := ioutil.ReadFile("clob.json")
	if err != nil {
		println(len(val))
		return err
	}

	conn2, _ := goOra.NewConnection(connStr)
	conn2.Open()
	str2 := "string2"

	stmt := goOra.NewStmt(`INSERT INTO GOORA_TEMP_VISIT(VISIT_ID, VISIT_DATA, VISIT_DATA2) VALUES(1, :str1, :str2)`, conn2)
	stmt.AddParam("str1", string(val), len(val), goOra.Input)
	stmt.AddParam("str2", str2, len(str2), goOra.Input)
	
	_, err = stmt.Exec(nil)
	if err != nil {
		return err
	}
	fmt.Println("1 row inserted: ", time.Now().Sub(t))
	return nil
}`
3. This execution returns the same error "ORA-01461: can bind a LONG value only for insert into a LONG column", 
4. To fix this the value in the second parameter if I put a value greater 2334 and it will work:
   `stmt.AddParam("str2", str2, 2335, goOra.Input)`

**Comment by sijms** [comment]
yes I try your code and now get the issue I will investigate and inform you

**Comment by sijms** [comment]
sorry man I get the problem
you need to pass []byte not string for any lob object
this the correct code will be
```golang
stmt.AddParam("str1", val, len(val), goOra.Input)
stmt.AddParam("str2", []byet(str2), len(str2), goOra.Input)
```
please try and inform me

**Comment by sijms** [comment]
I don't know your database charset can you try the above code passing string as uff-8 encoding the read the CLOB to see if there is any difference

**Comment by sijms** [comment]
sorry I make a mistake in my first example and passing []byte as clob parameter and I should pass string as you do

I make an update to the example file:
1-  fix the previous issue
2- add second lob column
3- make first insert into 2 clob columns using sql/database driver
4- make second insert into 2 clob columns using direct call of the driver
5- retrieve data to see if data return correctly

**Comment by sijms** [comment]
please test the example again and inform me

**Comment by sijms** [comment]
note also after some testing I do: 
the following code will give the error
```golang
val, err := ioutil.ReadFile("clob.json")
if err != nil {
    return err
}

_, err = conn.Exec(`INSERT INTO GOORA_TEMP_VISIT(VISIT_ID, VISIT_DATA, VISIT_DATA2) VALUES(1, :1, :2)`,
		val, "string2")
```
note I use val as []byte and second value string = "string2"
but if I correct it with `string(val)` no error happen

**Comment by FJM-Slade** [comment]
Used you new test function (insertData2()) and I'm having the same issue with the length of string 2:

1 - with the len(val2) (==7) : 

![image](https://user-images.githubusercontent.com/39168902/149806603-5fba07f3-1f0d-475d-a2ae-d5f61bf7adc4.png)

 

2 - Changing the **len(val2)** to **len(val)** (==9333) it works:

![image](https://user-images.githubusercontent.com/39168902/149807087-2a2171f2-4742-49cd-9003-1d8450684f90.png)

**Comment by sijms** [comment]
what is your database charset

**Comment by FJM-Slade** [comment]
> what is your database charset

NLS_NCHAR_CHARACTERSET	AL16UTF16
NLS_CHARACTERSET	AL32UTF8

**Comment by sijms** [comment]
I create database with same parameter and get the issue and fix

you can test now it works

**Comment by FJM-Slade** [comment]
I'm getting the same error.
In debug, the 2nd parameter has the value:
![image](https://user-images.githubusercontent.com/39168902/149832563-c9993d3f-479c-47d5-9068-37714bda19d8.png)

![image](https://user-images.githubusercontent.com/39168902/149832910-00d93261-b282-4020-9b92-24744d43257d.png)

**Comment by sijms** [comment]
update package please
I make a commit that fix the error your image data show that you don't get the fixation

**Comment by sijms** [comment]
I make new release v2.2.20

**Comment by sijms** [comment]
please note that size parameter in function AddParam is important for output direction only input parameter size is calculated from data entered thus you can safely put it -1

**Comment by sijms** [comment]
now you can get Blob and Clob as output parameters
please review clob example file for new changes

**Comment by FJM-Slade** [comment]
Just install v2.2.22. Every case is working fine and as expected!
Thanks for your support! 
Keep on the good job in this project!

**Comment by sijms** [comment]
you are welcome
