### ISSUE TITLE
sometimes execute sql without data

### ISSUE THREAD

**Issue by fishman001** [sijms/go-ora#153]
select NAME,state ,total_MB / 1024 total_MB,round(USABLE_FILE_MB / 1024) free_MB  from v$asm_diskgroup;
I execute the sql times via go-ora, sometimes got no data.
but it run well on db server.

![image](https://user-images.githubusercontent.com/52991319/150456679-8b2b2862-ff98-4669-b2d5-f91984e99c75.png)

**Comment by sijms** [comment]
for me it return empty dataset on the server and client

**Comment by sijms** [comment]
can you write your code

**Comment by sijms** [comment]
also please note if no data means no data come from the server and you can check trace.log file and confirm if there is data return from the server or not

**Comment by sijms** [comment]
does you test from other client?
