### ISSUE TITLE
Whether ipv6 is supported?

### ISSUE THREAD

**Issue by fishman001** [sijms/go-ora#155]
I try to connect db with ipv6 but faild.
when I use connetion string like "oracle://username:password@fe80::250:56ff:fea0:b9cb:1521/orcl", it return "dial tcp: lookup fe80 on xxxx:xx: server misbehaving ".

when I use BuildUrl function get the url like "oracle://oracle:oracle@fe80%3A%3A250%3A56ff%3Afea0%3Ab9cb:1521/orcl", it return "parse \"oracle://username:password@fe80%3A%3A250%3A56ff%3Afea0%3Ab9cb:1521/orcl\": invalid URL escape \"%3A\""

**Comment by sijms** [comment]
yes I will fix

**Comment by sijms** [comment]
fixed 
you can do one of the following
```go
url := go_ora.BuildUrl("::1", 1521, "service", "user", "password", nil)
url = "oracle://user:password@[::1]:1521/service"
```
