### ISSUE TITLE
failed if any param after a large CLOB

### ISSUE THREAD

**Issue by mocukie** [sijms/go-ora#156]
Hi,

I'm using the v2.2.25, when i insert or update a large clob field, got the ORA-01461/ORA-01483.
This problem can be reproduced with `examples/clob/`

```go
val, err := ioutil.ReadFile("clob.json")
if err != nil {
  return err
}

//large clob
v := go_ora.Clob{String: string(val) + string(val) + string(val) + string(val) + string(val)} 
```

suceeded:
```go
_, err = conn.Exec(`INSERT INTO GOORA_TEMP_VISIT(VISIT_ID, VISIT_DATA) VALUES(1, :1)`, v)
_, err = conn.Exec(`INSERT INTO GOORA_TEMP_VISIT(VISIT_ID, VISIT_DATA ) VALUES(:1, :2)`, 1, v)
_, err = conn.Exec(`UPDATE GOORA_TEMP_VISIT set  VISIT_DATA = :1 where VISIT_ID = 1`, v)
```

failed:
```go
_, err = conn.Exec(`INSERT INTO GOORA_TEMP_VISIT(VISIT_DATA, VISIT_ID) VALUES(:1, :2)`, v, 1) //ORA-01461
_, err = conn.Exec(`INSERT INTO GOORA_TEMP_VISIT(VISIT_ID, VISIT_DATA,VISIT_DATA2,VISIT_DATA3) VALUES(1, :1, :2, :3)`, v, "hi", []byte("hii")) //ORA-01461
_, err = conn.Exec(`UPDATE GOORA_TEMP_VISIT set  VISIT_DATA2 = :1 where VISIT_ID = :2`, v, 1) //ORA-01483
```

Database info
|     |     |
-|-
VERSION|19c
NLS_NCHAR_CHARACTERSET|AL16UTF16
NLS_CHARACTERSET|AL32UTF8

**Comment by sijms** [comment]
yes I get the error with
```golang
v := go_ora.Clob{String: string(val) + string(val) + string(val) + string(val) + string(val)}
```
but when I reduce it to
```golang
v := go_ora.Clob{String: string(val) + string(val) + string(val)}
```
no error

I will investigate and inform you

**Comment by sijms** [comment]
the problem solved. now input parameter for CLOB and BLOB is working with any data size

**Comment by sijms** [comment]
oracle accept varchar2 as input for CLOB, raw as input for BLOB and nvarchar2 as input for NCLOB as long as the size of this input is < data limit which is 32767 
thus when you pass 
```Golang
// size = 9333 * 3 = 27999
v := go_ora.Clob{String: string(val) + string(val) + string(val)}
```
but when we reach 4 time
```Golang
// size = 9333 * 4 = 37332 ---> error
v := go_ora.Clob{String: string(val) + string(val) + string(val) + string(val)}
```
at this situation we need to pass these data as LOB (create temporary LOB in the server -> copy data to them -> make insert -> free memory)
