### ISSUE TITLE
OS Authentication Linux not working

### ISSUE THREAD

**Issue by gyanpatel** [sijms/go-ora#158]
How to connect to externally identified password
**e.g.  password will be externally identified for unix user 
:>sqlplus /

SQL*Plus: Release 11.2.0.4.0 Production on Wed Feb 2 12:43:35 2022

Copyright (c) 1982, 2013, Oracle.  All rights reserved.

Connected to:
Oracle Database 11g 

SQL>**

tried without giving password but it did not work.

**Comment by sijms** [comment]
do you try to connect with `sys:any_password@server/service`

**Comment by gyanpatel** [comment]
I am not connecting using sys .. it's a different user.
oracle://user:any_password@host:1521/service -- gives error.
2022/02/02 21:09:47 unable to Ping DB ORA-01017: invalid username/password; logon denied

**Comment by gyanpatel** [comment]
validate() this function may be the issue. 
Oracle connection works just with "/" if db user is externally authenticated and login is happening from within the db server.
e.g. below is a valid connection :
sqlplus /

SQL*Plus: Release 11.2.0.4.0 Production on Wed Feb 2 22:02:50 2022

Copyright (c) 1982, 2013, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g

SQL>


the same works from sqlplus from a shell script or a Pro*C program. 
"/" should be a valid oracle connection string.

**Comment by sijms** [comment]
I will investigate the issue and inform you

**Comment by gyanpatel** [comment]
Thank you.

**Comment by sijms** [comment]
I add this feature now 
but I test it only on windows

can you make test in linux and tell me the result

thanks

**Comment by sijms** [comment]
I have oracle over docker I try many time os authentication on linux and Mac with failure
following this tutorial [Os Auth](https://oracle-base.com/articles/misc/os-authentication)

**Comment by gyanpatel** [comment]
Will you add this feature soon ? Will be a great help.

**Comment by sijms** [comment]
Are you test it for linux?

**Comment by sijms** [comment]
My problem is that I am using pluggable database which doesn't support OS Authentication

Test the driver latest version on your environment and tell me the result please

**Comment by sijms** [comment]
you it is valid to pass without user and password

**Comment by sijms** [comment]
I think it is using unix socket for IPC

**Comment by sijms** [comment]
I test unix socket I can send packet through it but still logon denied
the only working thing is
```bash
sqlplus / as SYSDBA
```
any changes like `sqlplus /@SID as SYSDBA` or `sqlplus /@server/service as SYSDBA` is not working with me at all

**Comment by sijms** [comment]
closed for long time no response

**Comment by gyanpatel** [comment]
Sorry I am unable to help on this. Trying to resolve this might be very helpful to others .

**Comment by gyanpatel** [comment]
Did you try db connection on database server itself for this ? This is scenario is only if we are connecting within the database server itself.

**Comment by genweihua** [comment]
I want to use this, see this,I can test it。I find  godror，this can connect database as / as sysdba,https://github.com/godror/godror/issues/54,may be can help you?

**Comment by sijms** [comment]
would you test the connection from inside the server using unix socket
