### ISSUE TITLE
DB connection failure: encryption service algorithm: 6 still not supported

### ISSUE THREAD

**Issue by litaochen** [sijms/go-ora#159]
When I try to connect to the database using the driver, I see this error:
"advanced negotiation error: encryption service algorithm: 6 still not supported"

Database  (on AWS RDS, Oracle 12.0) config:
- SQLNET.ENCRYPTION_SERVER: REQUIRED
- SQLNET.ENCRYPTION_TYPES_SERVER: RC4_256, AES256, AES192, ....

On the application server "sqlnet.ora" config:
- SQLNET.ENCRYPTION_SERVER = required
- SQLNET.ENCRYPTION_TYPES_SERVER = AES256

On the application server, set the environment variable "TNS_ADMIN" to point to the directory that contains "sqlnet.ora"

Did I miss anything?

**Comment by litaochen** [comment]
BTW: I am with go-ora version v2.3.0

**Comment by sijms** [comment]
the driver not using sqlnet.ora and TNS_ADMIN
the error message because that the driver is not support any RC4 encryption
if you put AES256 as the first option in the server it will work 

I will try to add RC4 encryption support later

**Comment by sijms** [comment]
I will also add some url configuration that work instead of sqlnet.ora and tns_admin

**Comment by sijms** [comment]
yes this is what I will do:
1- I will send to the server only the supported algorithm
2- let user select his preferred algorithm through database URL option

what happen here is that the client send an empty option thus server will select one from its side which is the first one in the list

I will leave the issue open until I finish the work and inform you

**Comment by litaochen** [comment]
any update?

**Comment by sijms** [comment]
coming soon I am now working on supporting OS authentication

**Comment by sijms** [comment]
fixed now.
you can test it
