### ISSUE TITLE
passing array of string as parameter

### ISSUE THREAD

**Issue by hmmftg** [sijms/go-ora#161]
Hi
how can we pass array of for example string for IN clause?

**Comment by hmmftg** [comment]
For example if we have this code:

	package main

	import (
		"fmt"
		"log"

		"database/sql"

		_ "github.com/sijms/go-ora/v2"
	)

	func main() {
		db, err := sql.Open("oracle", "oracle://scout:tiger@127.0.0.1:1521/?SID=orcl")
		if err != nil {
			log.Fatal(err)
		}

		stmt, err := db.Prepare("SELECT table_name FROM all_tables WHERE owner in (:1, :2, :3)")
		if err != nil {
			log.Fatalln(err)
		}
		defer stmt.Close()
		rows, err := stmt.Query("XDB", "ORDSYS", "DBSNMP")
		if err != nil {
			log.Fatalln(err)
		}

		list := make([]string, 0)
		for rows.Next() {
			var result string
			err := rows.Scan(&result)
			if err != nil {
				log.Fatalln(err)
			}
			list = append(list, result)
		}

		fmt.Println(list)
	}

can we replace `:1,:2,:3` with something like `?` and pass slice of string as argument to `Query`?
currently we write a string concat function to build `'data1','data2','data3'` and it look so old-school way

**Comment by sijms** [comment]
sorry for my late replay
you need to pass an array as a parameter
this feature still not supported I will try to add it as soon as I finish OS authentication

for now you can make it as fmt.Sprintf() and strings.Join()

**Comment by sijms** [comment]
I think it will not be easy as I read in documentation oracle permit 2 way of array
1- define array of values in the parameter --> very easy but work only with insert statement
2- create a type table or array -->  create a stored procedure that accept this new type and if you work with select I think you need to return a cursor

still I didn't test the second way but I ask if you have work with this in the other drivers?

**Comment by sijms** [comment]
add add new release that support oracle associative array [input/output] with an example
I try to make it as simple as possible 

with this feature you can do `in(values)` implementation with oracle
