### ISSUE TITLE
Connection through oracle connection manager

### ISSUE THREAD

**Issue by dekke046** [sijms/go-ora#168]
Hi,

We usually connection through an Oracle Connection Manager, so the JDBC Url looks like:

```
username/password@"(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=OFF)(FAILOVER=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=ocmhost1)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbserver1)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=ocmhost2)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbserver1)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=ocmhost1)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbserver2)(PORT=1521))
(ADDRESS=(PROTOCOL=TCP)(HOST=ocmhost2)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbserver2(PORT=1521)))(CONNECT_DATA=(UR=A)(SERVER=DEDICATED)(SERVICE_NAME=db1.a.database))(SOURCE_ROUTE=yes))"
```

```
(DESCRIPTION=
(ADDRESS_LIST=
(LOAD_BALANCE=OFF)
(FAILOVER=ON)
(ADDRESS=(PROTOCOL=TCP)(HOST=ocmhost1)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbserver1)(PORT=1521))
(ADDRESS=(PROTOCOL=TCP)(HOST=ocmhost2)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbserver1)(PORT=1521))
(ADDRESS=(PROTOCOL=TCP)(HOST=ocmhost1)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbserver2)(PORT=1521))
(ADDRESS=(PROTOCOL=TCP)(HOST=ocmhost2)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbserver2)(PORT=1521)))
(CONNECT_DATA=
(UR=A)
(SERVER=DEDICATED)
(SERVICE_NAME=db1.a.database)
)
(SOURCE_ROUTE=yes)
)
```
Will this be possible with go-ora? anybody have any suggestions?

**Comment by dekke046** [comment]
> actually I use the url parameter to build this description and send to server so I will add url option to pass this string and I will use regex to extract server, port, service

That will be really nice, then basically the JDBC URL's can be used almost as-is.

**Comment by dekke046** [comment]
> actually I use the url parameter to build this description and send to server so I will add url option to pass this string and I will use regex to extract server, port, service

But is this going to work?
When looking at connection_string.go and function newConnectionStringFromUrl:

```
	if q != nil {
		for key, val := range q {
			switch strings.ToUpper(key) {
			//case "DATA SOURCE":
			//	conStr.DataSource = val
			case "SERVICE NAME":
				ret.ServiceName = val[0]
```
You change the case to upper, thats fine, but how do you match the _ underscore sign?
Perhaps I overlooked your code too quickly for replacing _ with a whitespace. Currently I specify it as SERVICE_NAME

**Comment by sijms** [comment]
I make new release to add this feature.
just use function `go_ora.BuildJDBC(user, pass, connStr, urlOptions)`
I make a brief description about usage in readme file

can you test it and inform me about the result

**Comment by sijms** [comment]
what I am doing is read url parameter and store it in `ConnectionOption` object then use this information to make network connection and send `(description=...` string which is build also from ConnectionOption

when you send `(description=...` as a parameter I will do the reverse ==> read data from `(description=...` and store it in `ConnectionOption` then make network connection and send the entered `(description=...` string

**Comment by dekke046** [comment]
> I make new release to add this feature. just use function `go_ora.BuildJDBC(user, pass, connStr, urlOptions)` I make a brief description about usage in readme file
> 
> can you test it and inform me about the result

I think we are almost there, but not yet :-)
Taking the bare minimum tot make a db connection:

```
func main() {
	connStr := `(DESCRIPTION=
	(ADDRESS_LIST=
	   (LOAD_BALANCE=OFF)
	   (FAILOVER=ON)
	   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost1)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost1)(PORT=1521))
	   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost2)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost1)(PORT=1521))
	   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost1)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost2)(PORT=1521))
	   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost2)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost2)(PORT=1521))
	)
	(CONNECT_DATA=
	(UR=A)
	(SERVER=DEDICATED)
	(SERVICE_NAME=s4019.a.database)
	)
	(SOURCE_ROUTE=yes)
	)`
	databaseUrl := go_ora.BuildJDBC("USERBAME", "PASSWORD", connStr, nil)
	conn, err := sql.Open("oracle", databaseUrl)
	if err != nil {
		fmt.Println(err)
		return
	}
	err = conn.Ping()
	if err != nil {
		fmt.Println(err)
		return
	}

}
```
The response when running:
`no address passed in connection string`

The way we need to connect to Oracle databases due to corporate policies is via an OCM, the response I am seeing now is from the OCM itself.

![image](https://user-images.githubusercontent.com/12866158/157450938-61285b32-df49-447f-ab34-e654dcc05761.png)

I guess we are reaching out to one of the CMHOSTs but not to the DB itself.

**Comment by sijms** [comment]
`no address passed in connection string` this error message come from the client line# 160 connect_option.go
means failed to get server information from passed `(description...`
can you run this code and see if it give error?
```golang
connStr := `(DESCRIPTION=
	(ADDRESS_LIST=
	   (LOAD_BALANCE=OFF)
	   (FAILOVER=ON)
	   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost1)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost1)(PORT=1521))
	   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost2)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost1)(PORT=1521))
	   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost1)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost2)(PORT=1521))
	   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost2)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost2)(PORT=1521))
	)
	(CONNECT_DATA=
	(UR=A)
	(SERVER=DEDICATED)
	(SERVICE_NAME=s4019.a.database)
	)
	(SOURCE_ROUTE=yes)
	)`
	op := &network.ConnectionOption{}
	fmt.Println(op.UpdateDatabaseInfo(connStr))
	fmt.Println(op.Servers)
```

**Comment by sijms** [comment]
about the picture the driver should get list of servers from connect string then try to connect to them one by one until get successful connection

**Comment by dekke046** [comment]
> `no address passed in connection string` this error message come from the client line# 160 connect_option.go means failed to get server information from passed `(description...` can you run this code and see if it give error?
> 
> ```go
> connStr := `(DESCRIPTION=
> 	(ADDRESS_LIST=
> 	   (LOAD_BALANCE=OFF)
> 	   (FAILOVER=ON)
> 	   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost1)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost1)(PORT=1521))
> 	   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost2)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost1)(PORT=1521))
> 	   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost1)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost2)(PORT=1521))
> 	   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost2)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost2)(PORT=1521))
> 	)
> 	(CONNECT_DATA=
> 	(UR=A)
> 	(SERVER=DEDICATED)
> 	(SERVICE_NAME=s4019.a.database)
> 	)
> 	(SOURCE_ROUTE=yes)
> 	)`
> 	op := &network.ConnectionOption{}
> 	fmt.Println(op.UpdateDatabaseInfo(connStr))
> 	fmt.Println(op.Servers)
> ```

The output:
```
<nil>
[{TCP cmhost1 1521} {TCP dbhost1 1521} {TCP cmhost2 1521} {TCP dbhost1 1521} {TCP cmhost1 1521} {TCP dbhost2 1521} {TCP cmhost2 1521} {TCP dbhost2 1521}]
```

**Comment by dekke046** [comment]
> `no address passed in connection string` this error message come from the client line# 160 connect_option.go means failed to get server information from passed `(description...` can you run this code and see if it give error?
> 
> ```go
> connStr := `(DESCRIPTION=
> 	(ADDRESS_LIST=
> 	   (LOAD_BALANCE=OFF)
> 	   (FAILOVER=ON)
> 	   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost1)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost1)(PORT=1521))
> 	   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost2)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost1)(PORT=1521))
> 	   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost1)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost2)(PORT=1521))
> 	   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost2)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost2)(PORT=1521))
> 	)
> 	(CONNECT_DATA=
> 	(UR=A)
> 	(SERVER=DEDICATED)
> 	(SERVICE_NAME=s4019.a.database)
> 	)
> 	(SOURCE_ROUTE=yes)
> 	)`
> 	op := &network.ConnectionOption{}
> 	fmt.Println(op.UpdateDatabaseInfo(connStr))
> 	fmt.Println(op.Servers)
> ```

But using fully qualified domain names its empty:

```
		   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost1.ocm.net)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost1.db.net)(PORT=1521))
		   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost2.ocm.net)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost1.db.net)(PORT=1521))
		   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost1.ocm.net)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost2.db.net)(PORT=1521))
		   (ADDRESS=(PROTOCOL=TCP)(HOST=cmhost2.ocm.net)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=dbhost2.db.net)(PORT=1521))
```

Then its empty:
```
no address passed in connection string
[]
```

**Comment by sijms** [comment]
no problem I will update the function that extract server information

**Comment by sijms** [comment]
do you update the driver to 2.4.8

**Comment by dekke046** [comment]
> do you update the driver to 2.4.8

Yes :-)

**Comment by dekke046** [comment]
> no problem I will update the function that extract server information

It looks the regex at line 90 in connect_option.go will not extract FQDN's:
```r, err := regexp.Compile(`(?i)\(\s*HOST\s*=\s*(\w+)\s*\)`)```

**Comment by dekke046** [comment]
> I make new release and update regex

I changed it locally at two places:

```
r, err := regexp.Compile(`(?i)\(\s*HOST\s*=\s*(\S+)\s*\)`)
r, err := regexp.Compile(`(?i)\(\s*SERVICE_NAME\s*=\s*(\S+)\s*\)`)
```
Then the result is:
```
<nil>
[{TCP cmhost1.ocm.net)(PORT=1521) 1521} {TCP dbhost1.db.net)(PORT=1521) 1521} {TCP cmhost2.ocm.net)(PORT=1521) 1521} {TCP dbhost1.db.net)(PORT=1521) 1521} {TCP cmhost1.ocm.net)(PORT=1521) 1521} {TCP dbhost2.db.net)(PORT=1521) 1521} {TCP cmhost2.ocm.net)(PORT=1521) 1521} {TCP dbhost2.db.net)(PORT=1521)) 1521}]
```
That looks much better :-)

Now when trying to actually make an connection:
```
	databaseUrl := go_ora.BuildJDBC("USERNAME", "PASSWORD", connStr, nil)
	conn, err := sql.Open("oracle", databaseUrl)
	if err != nil {
		fmt.Println(err)
		return
	}
	err = conn.Ping()
	if err != nil {
		fmt.Println(err)
		return
	}
```
The result is:
`dial tcp: lookup dbhost2.db.net)(PORT=1521)): no such host
`

It cannot directly connect to such dbhosts, it **needs** to connect through the Oracle Connection Manager, but it looks like its trying to make a direct connection.

**Comment by sijms** [comment]
Sure it will make direct connection to the host specified in the `(ADDRESS=` statement 
I think you need to do the following
connect to OCM host:port and pass your own connection string?

if OCM host:port is present in connection string try to put as first `(ADDRESS=`

**Comment by sijms** [comment]
can you pass this option
```golang
urlOption := map[string]string {
    "TRACE FILE": "trace.log",
}
databaseUrl := go_ora.BuildJDBC("USERNAME", "PASSWORD", connStr, urlOption)
```
this will create trace file that show what happen during connection

**Comment by sijms** [comment]
if the Oracle Connection Manager  present in the address list thus the program will try to connect to it and you can find this in the log file

**Comment by sijms** [comment]
I fix reading service, SID and instances if they contain `.` or `-` 
now you can do:
1- use **BuildJDBC** and here the program will read connection information from connection string and will try to connect to servers one by one (order in connection string)
2- use **BuildUrl** and pass urlOptions contain connStr as follow:
```Golang
urlOptions := map[string]string {
    "connStr":  "(description=.....",
}
databaseUrl := go_ora.BuildUrl(primary_server /*can be empty*/, port, user, password, service/*should be empty*/, urlOptions)
```
the difference here is that you can specify primary server to connect to with port 
note:
    * other servers used in connection string will be added after primary server and the program will try to make connection to them after primary server fail
    * service in BuildUrl should be empty as service information will be load from connection string

**Comment by dekke046** [comment]
> I fix reading service, SID and instances if they contain `.` or `-` now you can do: 1- use **BuildJDBC** and here the program will read connection information from connection string and will try to connect to servers one by one (order in connection string) 2- use **BuildUrl** and pass urlOptions contain connStr as follow:
> 
> ```go
> urlOptions := map[string]string {
>     "connStr":  "(description=.....",
> }
> databaseUrl := go_ora.BuildUrl(primary_server /*can be empty*/, port, user, password, service/*should be empty*/, urlOptions)
> ```
> 
> the difference here is that you can specify primary server to connect to with port note: * other servers used in connection string will be added after primary server and the program will try to make connection to them after primary server fail * service in BuildUrl should be empty as service information will be load from connection string

Using the following code:
```
	op := &network.ConnectionOption{}
	fmt.Println(op.UpdateDatabaseInfo(connStr))
	fmt.Println(op.Servers)

	urlOptions := map[string]string{
		"TRACE FILE": "trace.log",
		"connStr":    connStr,
	}
	databaseUrl := go_ora.BuildUrl("", 1521, "USERNAME", "PASSWORD", "", urlOptions)
	conn, err := sql.Open("oracle", databaseUrl)
	if err != nil {
		fmt.Println(err)
		return
	}

	err = conn.Ping()
	if err != nil {

		fmt.Println(err)
		return
	}
```

The response:
```
<nil>
[{TCP ocmhost1.ocm.net 1521} {TCP dbhost1.db.net 1521} {TCP ocmhost2.ocm.net 1521} {TCP dbhost1.db.net 1521} {TCP ocmhost1.ocm.net 1521} {TCP dbhost2.db.net 1521} {TCP ocmhost1.ocm.net 1521} {TCP dbhost2.db.net 1521}]
Not data packet
```

I can provide you with the trace.log, but prefer to send it directly to you if needed ;-)

**Comment by dekke046** [comment]
> ok send the server and service read correctly and connection done but response is not as expected

Sent.
:-)

**Comment by sijms** [comment]
yes I receive your email I will examine the file and inform you

**Comment by sijms** [comment]
I see the file:
1-  the server using packet encryption encryption 
2- connection proceed well until reach authentication. the client send packet as usual by the server respond with empty data packet which is abnormal
because the data is encrypted I need to ask you question? are you using OS Auth?
also I note something form you code above
```Golang
// third parameter in BuildUrl is service name which should be ""
// but you pass "USERNAME"
// the operand before urlOptions is password which is empty
// when you pass an empty password this means you need to connect 
// through OS Auth and this explain what happen in log file
databaseUrl := go_ora.BuildUrl("", 1521, "USERNAME", "PASSWORD", "", urlOptions)
	conn, err := sql.Open("oracle", databaseUrl)
```
if the above is the code used to produce this log file then do one of the following
1- use `BuildJDBC` as you didn't pass and primary server in `BuildUrl`
2- correct `BuildUrl` calling as follow 
```golang
databaseUrl := go_ora.BuildUrl("", 1521, "",  "USERNAME", "PASSWORD", urlOptions)
	conn, err := sql.Open("oracle", databaseUrl)
```

**Comment by dekke046** [comment]
> I see the file: 1- the server using packet encryption encryption 2- connection proceed well until reach authentication. the client send packet as usual by the server respond with empty data packet which is abnormal because the data is encrypted I need to ask you question? are you using OS Auth? also I note something form you code above
> 
> ```go
> // third parameter in BuildUrl is service name which should be ""
> // but you pass "USERNAME"
> // the operand before urlOptions is password which is empty
> // when you pass an empty password this means you need to connect 
> // through OS Auth and this explain what happen in log file
> databaseUrl := go_ora.BuildUrl("", 1521, "USERNAME", "PASSWORD", "", urlOptions)
> 	conn, err := sql.Open("oracle", databaseUrl)
> ```
> 
> if the above is the code used to produce this log file then do one of the following 1- use `BuildJDBC` as you didn't pass and primary server in `BuildUrl` 2- correct `BuildUrl` calling as follow
> 
> ```go
> databaseUrl := go_ora.BuildUrl("", 1521, "",  "USERNAME", "PASSWORD", urlOptions)
> 	conn, err := sql.Open("oracle", databaseUrl)
> ```

using BuildJDBC:
```
	urlOptions := map[string]string{
		"TRACE FILE": "trace.log",
	}

	databaseUrl := go_ora.BuildJDBC("USERNAME", "PASSWORD", connStr, urlOptions)
	conn, err := sql.Open("oracle", databaseUrl)
	if err != nil {
		fmt.Println(err)
		return
	}
```
The response is:
`Can't ping connection: missing port in address`

But the port is specified in the "(description=....." connStr, I would expect it will grab from there.

Using BuildUrl:

```
	query := "SELECT BANNER FROM v$version"

	urlOptions := map[string]string{
		"TRACE FILE": "trace.log",
		"connStr":    connStr,
	}

	databaseUrl := go_ora.BuildUrl("dbhost1.db.net", 1521, "", "USERNAME", "PASSWORD", urlOptions)
	conn, err := sql.Open("oracle", databaseUrl)
	if err != nil {
		fmt.Println(err)
		return
	}
```

I get a proper response:
`BANNER:  Oracle Database 19c EE Extreme Perf Release 19.0.0.0.0 - Production
`
So a hit here :-)
But, if dbhost1.db.net is not available will it then automatically switch to dbhost2.db.net as specified in connStr?

**Comment by sijms** [comment]
yes a list of servers is build from `ADDRESS_LIST` with same order

you tell me you get proper response:- means problem solved?

**Comment by dekke046** [comment]
> yes a list of servers is build from `ADDRESS_LIST` with same order
> 
> you tell me you get proper response:- means problem solved?

Yes when using BuildUrl and specifying the primary server is works, so we can close the issue.

Using BuildJDBC, it doen NOT work:
`Can't ping connection: missing port in address`

**Comment by sijms** [comment]
I think no need for BuildJDBC I will remove in the future

**Comment by dekke046** [comment]
Then I will stick to BuildUrl.

Lets close the issue.

Thanks for your support!

**Comment by sijms** [comment]
I change BuildJDBC to be a shortcut like this
```Golang
func BuildJDBC(user, password, connStr string, options map[string]string) string {
	if options == nil {
		options = make(map[string]string)
	}
	options["connStr"] = connStr
	return BuildUrl("", 0, "", user, password, options)
}
```

test it if it is ok or not

**Comment by dekke046** [comment]
> I change BuildJDBC to be a shortcut like this
> 
> ```go
> func BuildJDBC(user, password, connStr string, options map[string]string) string {
> 	if options == nil {
> 		options = make(map[string]string)
> 	}
> 	options["connStr"] = connStr
> 	return BuildUrl("", 0, "", user, password, options)
> }
> ```
> 
> test it if it is ok or not

This is the way to go!
Now its I can just drop-in the conStr and there is no need to select a primary server.

It tested OK
