### ISSUE TITLE
Leaking open cursors when not using prepared statements

### ISSUE THREAD

**Issue by sugovsek** [sijms/go-ora#169]
I just recently switched to `v2` and started getting `maximum open cursors exceeded` errors. I'm using `database/sql.DB.Query` via `jmoiron/sqlx.DB.Queryx`. When tested using prepared statements (as is also shown in the readme), cursor count stays normal.

I've done some code digging, but found nothing interesting yet. Before I go further, I'd like to know if (and why) prepared statements are recommended (or required).

Version: v2.4.4
Oracle version: 18.3

**Comment by sijms** [comment]
yes you are correct
here is the code for ExecContext
```golang
func (conn *Connection) ExecContext(ctx context.Context, query string, args []driver.NamedValue) (driver.Result, error) {
	stmt := NewStmt(query, conn)
	defer func() {
		_ = stmt.Close()
	}()
	return stmt.ExecContext(ctx, args)
}
```
the Stmt is closed before function return
but I can't do it for Query because this will stop fetching

to solve the problem I will add `stmt.Close` in `DataSet.Close` thus
```Golang
rows, err := conn.Query(sqlText)
if err != nil {
    return err
}
defer func() {
   // here close will close also the stmt
    err = rows.Close()
}()
for rows.Next() {
    err = rows.Scan(...)
    if err != nil {
        return err
    }
}
return rows.Err()
```

**Comment by sijms** [comment]
I make new release that fix the issue

**Comment by sugovsek** [comment]
Tested and confirming this has fixed the issue. Thank you!

**Comment by sijms** [comment]
can you test again for v2.4.11 I make some modification

**Comment by sugovsek** [comment]
Tested and everything seems to work.
