### ISSUE TITLE
`error reading clob data` when value contains an emoji

### ISSUE THREAD

**Issue by sugovsek** [sijms/go-ora#171]
https://github.com/sijms/go-ora/blob/c5b62002b2113e879c49c3b446ece8558a209360/v2/command.go#L828
`dataSize`: `5`

https://github.com/sijms/go-ora/blob/c5b62002b2113e879c49c3b446ece8558a209360/v2/command.go#L845
`873`

https://github.com/sijms/go-ora/blob/c5b62002b2113e879c49c3b446ece8558a209360/v2/command.go#L846
`true`

https://github.com/sijms/go-ora/blob/c5b62002b2113e879c49c3b446ece8558a209360/v2/command.go#L855
`resultClobString`: 😶‍🌫

`len(resultClobString)`: `11`

https://github.com/sijms/go-ora/blob/c5b62002b2113e879c49c3b446ece8558a209360/v2/command.go#L857
`len([]rune(resultClobString))`: `3`

**Comment by sijms** [comment]
I think better to remove this `if condition` for CLOB

**Comment by sijms** [comment]
I publish release and comment  
```golang
// dataSize = number of characters not number of bytes
if dataSize != int64(len([]rune(resultClobString))) { 
    return nil, errors.New("error reading clob data")
}
```

**Comment by sugovsek** [comment]
Thanks again for a quick response!
