### ISSUE TITLE
Cannot reuse statements since 2.4.7

### ISSUE THREAD

**Issue by ueffel** [sijms/go-ora#172]
Since go-ora version 2.4.7 once prepared statements cannot be reused for multiple queries. It errors out with `ORA-01001: invalid cursor`.

Example:

```go
func must(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	db, err := sql.Open("oracle", "oracle://user:pw@server:/service")
	must(err)
	defer db.Close()
	stmt, err := db.Prepare("select :s from dual")
	must(err)
	defer stmt.Close()

	rows, err := stmt.Query("hi")
	must(err)

	var s string
	for rows.Next() {
		err = rows.Scan(&s)
		must(err)
		log.Println(s)
	}
	must(rows.Err())
	rows.Close()

	rows2, err := stmt.Query("hello")
	must(err) // panic: ORA-01001: invalid cursor
	for rows2.Next() {
		err = rows2.Scan(&s)
		must(err)
		log.Println(s)
	}
	must(rows2.Err())
	rows2.Close()
}
```

In version 2.4.6 and below this was working.

> Prepare creates a prepared statement for later queries or executions. Multiple queries or executions may be run concurrently from the returned statement. The caller must call the statement's Close method when the statement is no longer needed.

from https://pkg.go.dev/database/sql#DB.Prepare

**Comment by ueffel** [comment]
That is not the solution.
Prepared statements should be cachable and reusable regardless of any result sets. Statements are prepared against the connection pool, so even if the connection of a prepared statements is closed, it should automatically re-prepared with a new connection. This what the `database/sql` package provides.

**Comment by sijms** [comment]
now working you can test it

**Comment by ueffel** [comment]
It seems to be OK in 2.4.11. Thanks for the quick fix :)

**Comment by coderlindacheng** [comment]
this problem  still exist
