### ISSUE TITLE
SSL certificate verification support

### ISSUE THREAD

**Issue by chookly314** [sijms/go-ora#174]
Hi,

Does the library support SSL certificate verification? I have gone through the examples but I haven't seen any connection string with `SSL Verify=true`. I am getting a `X509.UnknownAuthorityError` error when trying that configuration, but I am not sure if it is an issue with the database certificate or if it is related to the client.

Thanks in advance.

**Comment by sijms** [comment]
the error is coming from this line which is related to tls package
```golang
if !connOption.SSLVerify {
	config.InsecureSkipVerify = true
}
session.sslConn = tls.Client(session.conn, config)
```

this is the documentation for `config.InsecureSkipVerify`
```golang
// InsecureSkipVerify controls whether a client verifies the server's
// certificate chain and host name. If InsecureSkipVerify is true, crypto/tls
// accepts any certificate presented by the server and any host name in that
// certificate. In this mode, TLS is susceptible to machine-in-the-middle
// attacks unless custom verification is used. This should be used only for
// testing or in combination with VerifyConnection or VerifyPeerCertificate.
InsecureSkipVerify [bool](https://pkg.go.dev/builtin#bool)
```

**Comment by chookly314** [comment]
thanks for the answer. I am using a self-signed certificate, but I also added it to the client's OS trust store (I copied it to `/usr/local/share/ca-certificates/` and run `update-ca-certificates` as I am working on Ubuntu). I will double check the configuration again in case that I did a mistake along the way.

**Comment by sijms** [comment]
self-signed certificate will not work with `SSL Verify=true`
you need to set it to false or register your server with Online Certificate Authority (ex. Let's Encrypt) 
this is not driver issue

**Comment by chookly314** [comment]
I see. Thanks for your help!
