### ISSUE TITLE
oracle connection hanging 

### ISSUE THREAD

**Issue by majj** [sijms/go-ora#176]
connect info: oracle://erpread:***@192.168.18.61:1521/ERPLN?TRACE FILE=ora_trace.log
ping error:read tcp 10.14.15.54:52804->192.168.18.61:1521: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
7:35PM ERR o4.go:48 > error: &net.OpError{Op:"read", Net:"tcp", Source:(*net.TCPAddr)(0xc000090000), Addr:(*net.TCPAddr)(0xc000090030), Err:(*os.SyscallError)(0xc00008c220)} pkg=main
7:35PM ERR o4.go:49 > stacktrace: goroutine 1 [running]:
runtime/debug.Stack()
        E:/Program Files/Go/src/runtime/debug/stack.go:24 +0x65
main.main.func1()

it hanged when "Data Type Negotiation":

ora_trace.log:

2022-03-22T19:32:41.5854: Server Charset: 852
2022-03-22T19:32:41.5854: Server National Charset: 2000
2022-03-22T19:32:41.5904: Data Type Negotiation
2022-03-22T19:32:41.5904: 
Write packet:
00000000  00 00 0a 65 06 00 00 00  00 00 02 54 03 54 03 03  |...e.......T.T..|

But a few days ago, everything was OK.

Other Oracle clients are running normally.

---
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
PL/SQL Release 12.1.0.2.0 - Production
"CORE 12.1.0.2.0 Production"
TNS for Linux: Version 12.1.0.2.0 - Production
NLSRTL Version 12.1.0.2.0 - Production

**Comment by sijms** [comment]
I seems to be a connection problem "interruption" and the client is not support failover issue #124 
but you can do it by using Context and timeout and reconnect when interrupt or timeout
refer to example **context** and readme file for **version 2.4.1**

**Comment by sijms** [comment]
I will close the issue because of repeat

**Comment by majj** [comment]
one more question: if application using server-side TAF and only provide the main DB node IP，how to find the available server?
Thanks.

**Comment by sijms** [comment]
with server failover when you connect to failed server it will send redirect packet to the client this redirect packet contain connection information for another server in the RAC so client will be redirected to another server
