### ISSUE TITLE
Question about String to CLOB conversion

### ISSUE THREAD

**Issue by chookly314** [sijms/go-ora#177]
Hi,

I am using a Go generic persistence layer that works accross multiple SQL technologies, and I am trying to add Oracle support. As the code that connects to the database is the same regardless of the database (Oracle, Postgres, etc.), it relies on the sql package interface.

To keep the code as SQL technology agnostic as possible, I would like to avoid using the `go_ora.Clob` type (as it is Oracle specific), and keep using `string` instead when working with attributes that are mapped to Oracle CLOB. Some other SQL database drivers request the schema associated with the table that is being queried, so that Go types are mapped to the ones as defined in the schema, regardless of the Go type that was provided. I have gone through the examples and I don't think that is possible with the driver ([taking a look to the code](https://github.com/sijms/go-ora/blob/2da977b31ac60e3d434f16a7ad756f969c290b0a/v2/parameter_encode.go#L134) it seems like Go to Oracle types mapping are done depending on the Go types only), but I would like to ask if there is a way (maybe a configuration flag) that makes the driver map Go strings to VARCHAR or CLOB dynamically, instead of always converting them to `NCHAR` (as in the code fragment I linked above).

Thanks in advance.

**Comment by sijms** [comment]
you can pass string input parameter for CLOB type and []byte for BLOB type but the restricted to size 0x7FFF
value more than this need to be wrapped in CLOB and BLOB

**Comment by chookly314** [comment]
Sorry for reopening the issue, but I would like to add a proposal: would it be acceptable if the driver handles a string greater than 0x7FFF characters as a CLOB (converting from string to CLOB in that case)?

If the string is greater than 0x7FFF, then the write operation on the database would fail even if it was sent as a VARCHAR, so the driver would be only trying its best to make the operation succeed. As the returned error would be different (because it would be trying to write a CLOB into a VARCHAR column, and not a VARCHAR that exceeds its max size), that error could be wrapped to provide extra details to resolve the ambiguity.

**Comment by sijms** [comment]
ok I will see and inform you

**Comment by sijms** [comment]
you code is very good and thank you for your contribution.
I actually merge it to the project
but there is small problem
the code will work correctly for input parameter but for output parameter there will be an issue as follow:
I take one part for demonstration
```golang
case *string:
	if value == nil {
		par.encodeString("", connection.strConv, size)
	} else {
		if len(*value) > converters.MAX_LEN_NVARCHAR2 {
			valToClob := fromStringToClob(*value)
			return par.encodeValue(&valToClob, size, connection)
		}
		par.encodeString(*value, connection.strConv, size)
	}
```
when you recall encodeValue with different data type. and as you see the first line of encodeValue
```golang
var err error
par.Value = val
```
you make change in `par.Value`
`par.Value` is the place to save user var thus when data come from oracle I can deliver it to user correctly using par.Value

**Comment by sijms** [comment]
I add `par.Direction == Input` to the condition to avoid change par.Value for Output direction

**Comment by chookly314** [comment]
oh, I didn't realize that code was also being used for output values. Thank you for accepting the PR and fixing that.
