### ISSUE TITLE
 In oracle 19c the driver cannot connect

### ISSUE THREAD

**Issue by jmptrader** [sijms/go-ora#179]
I run with diferent versions : 12c / 18c.  the all test programs work very well.

In the case of 19c , the driver fails to connect, I get the following error:

Can't ping connection read tcp xx.xx.xx.xx:51456->yy.yy.yy.yy:1521: 

wsarecv: An existing connection was forcibly closed by the remote host.

What could be happening.?

**Comment by sijms** [comment]
create trace log and see at which point the connection was closed

**Comment by jmptrader** [comment]
Thanks!
 After several tests, I conclude that it is a network connection instability problem, between my Windows client PC and the remote server with the database.
