### ISSUE TITLE
ORA-06502: PL/SQL: numeric or value error

### ISSUE THREAD

**Issue by 1580739389** [sijms/go-ora#18]
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/sijms/go-ora"
)

func main() {
	fmt.Println("main")

	db, err := sql.Open("oracle", "oracle://scott:tiger@127.0.0.1:1521/orcl")
	defer db.Close()
	if err != nil {
		fmt.Println("[sql.Open ERR]:", err)
		return
	}

	err = db.Ping()
	if err != nil {
		fmt.Println("[db.Ping ERR]:", err)
		return
	}
}

[db.Ping ERR]: ORA-06502: PL/SQL: numeric or value error
ORA-06512: at line 16

**Comment by sijms** [comment]
I run you code no error come

please get the last update of the package

**Comment by 1580739389** [comment]
last update
go-ora@v0.0.0-20201108135513-712ea4f3d160

**Comment by 1580739389** [comment]
The problem is still

**Comment by 1580739389** [comment]
go version go1.15 windows/amd64
oracle version Release 11.2.0.1.0 Production

**Comment by sijms** [comment]
go to file connection.go
and comment statement at line 286
```
_, err = conn.GetNLS()
if err != nil {
	return err
}
```
and see if error happen

**Comment by 1580739389** [comment]
Not an error
thank you

**Comment by ljyf5593** [comment]
i have the seem error, may be comment the code ?

**Comment by 1580739389** [comment]
go to file connection.go
and comment statement at line 286

_, err = conn.GetNLS()
if err != nil {
	return err
}
and see if error happen

**Comment by ljyf5593** [comment]
comment the code and error not happen, but in this way will be modify this pkg, Is this the right way to do ?

**Comment by sijms** [comment]
the error tell at line 16
`SELECT VALUE into :p_nls_timestamp from nls_session_parameters where PARAMETER='NLS_TIMESTAMP_FORMAT';`
can you make query in database 
`SELECT VALUE FROM nls_session_parameters WHERE PARAMETER='NLS_TIMESTAMP_FORMAT';`
and see what is the result because it suppose to be string

**Comment by 1580739389** [comment]
in my database it is
DD-MON-RR HH.MI.SSXFF AM

**Comment by ljyf5593** [comment]
in my database it is seem
DD-MON-RR HH.MI.SSXFF AM
![image](https://user-images.githubusercontent.com/960459/99219083-e0bff480-2816-11eb-904c-6a39f7e30df4.png)

**Comment by ljyf5593** [comment]
I have two database, the left one have the error, but the right one no error
![image](https://user-images.githubusercontent.com/960459/99219949-a6efed80-2818-11eb-8d81-0ed0d64fdef7.png)

**Comment by sijms** [comment]
ZHS16GBK is not supported by the driver 
return to issue #13 
because you will face problems during bytes-->string conversion
