### ISSUE TITLE
BuildJDBC error

### ISSUE THREAD

**Issue by max-pub** [sijms/go-ora#180]
hi,

thanks for you great work of implementing a pure go oracle library!

unfortunately i'm having issues connecting.

the following code:

```go
databaseUrl := go_ora.BuildJDBC(user,pass, `(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(COMMUNITY=TCP)(PROTOCOL=TCP)(HOST=aaa.bbb.com)(PORT=1521)))(CONNECT_DATA=(SID=MYSID)))`, options)

conn, err := sql.Open("oracle", databaseUrl)
if err != nil {
	fmt.Println("connection ERROR:", err)
} else {
	fmt.Println("connection SUCCESS:", conn)
}


err = conn.Ping()
if err != nil {
	fmt.Println("PING ERROR:", err)
} else {
	fmt.Println("PING SUCCESS:")
}
```

results in 

```
connection SUCCESS: &{0 0xc00009a108 0 {0 0} [] map[] 0 0 0xc00008a0c0 false map[] map[] 0 0 0 0 <nil> 0 0 0 0 0x82cce0}
PING ERROR: no address passed in connection string
```

the same connection string works in other environments.
so i assume its a connection-string-parsing-error? unable to extract the address-part?

i'm also wondering about the "successfull connection" when i cannot ping or query afterwards.

am I missing something?

**Comment by sijms** [comment]
are you using last version of the driver?

**Comment by max-pub** [comment]
> the problem in COMMUNITY=TCP if you remove it will work

that works, thank you!

**Comment by sijms** [comment]
I add COMMUNITY=value to the parser so you can use it without problem
