### ISSUE TITLE
"missing port in address" after upgrade from v2.2.25 to v2.4.11

### ISSUE THREAD

**Issue by dpajkovic** [sijms/go-ora#181]
I create the URL using the BuildURL same as before:

```golang
oracleUrl := go_ora.BuildUrl("server1.example.com", 6236, "service", "user", "password", map[string]string{"SERVER": "server2.example.com, server3.example.com"})
```

and get the same sort of URL as before (checking the logs) `oracle://user:password@server1.example.com:6236/service?SERVER=server2.example.com&SERVER=server3.example.com`, but after doing

```golang
conn, err := sql.Open("oracle", oracleUrl)
err = conn.Ping()
```

the error I get is "address server2.example.com: missing port in address".

Has the format of the URL or of the connection options map changed between minor versions? How should I construct the URL?

**Comment by sijms** [comment]
the problem is not in BuildUrl but in `SERVER` option
the difference between 2 versions is that I use build in function `net.SplitHostPort(srv)` in newer version this function expected host:port so to solve the problem do the following:
```Golang
oracleUrl := go_ora.BuildUrl("server1.example.com", 6236, "service", "user", "password", map[string]string{"SERVER": "server2.example.com:, server3.example.com:"})
```

**Comment by dpajkovic** [comment]
Thanks, it worked great!
