### ISSUE TITLE
query panic

### ISSUE THREAD

**Issue by GodShuning** [sijms/go-ora#186]
![image](https://user-images.githubusercontent.com/26109408/163091425-2bc63e00-b647-4258-ba9c-6a525f09a919.png)

**Comment by GodShuning** [comment]
SELECT ROWID FROM "DVSYS"."COMMAND_RULE$" OFFSET 0 ROWS FETCH NEXT 1000 ROWS ONLY

**Comment by sijms** [comment]
Fixed

**Comment by GodShuning** [comment]
thanks
