### ISSUE TITLE
Is connection pooling not fully implemented?

### ISSUE THREAD

**Issue by eugene-vodyanko** [sijms/go-ora#188]
Hi.

Do I understand correctly that connection pooling is not fully implemented?
That is, the reuse of sessions in Oracle is not forced?
Or am I mistaken and there is a way to set retention and multiple reuse of DBMS connection?

Thanks.

**Comment by sijms** [comment]
the package doesn't implement connection pooling but connection pooling is support in sql/database standard package.
about reusing session I don't know if it possible. The original c# driver (the main source I use) when use connection pooling it will not reuse session but make new connect steps (connect -> accept -> advanced negotiations -> tcp negotiations -> data negotiations -> authentication)

**Comment by eugene-vodyanko** [comment]
Thank you for the clarification!
Special thanks for the promptness.

P.S. Just in case, I note that the excessive rotation of sessions in the DBMS was eliminated by setting using db.SetMaxIdleConns(N), where N = MaxOpenConns.
