### ISSUE TITLE
password parse err

### ISSUE THREAD

**Issue by 1580739389** [sijms/go-ora#19]
[db.Ping ERR]: parse "oracle://lzusjzl:Lzu!7N1I%rjV@127.0.0.1:1521/lzudatatest": invalid URL escape "%rj"

**Comment by sijms** [comment]
i think you need to do some modification to this url
try to put "" for password 
or try %%rjV

**Comment by 1580739389** [comment]
We hope to improve url parsing

**Comment by sijms** [comment]
this is library function of golang how to improve?
you search internet for how to write escape character in url
