### ISSUE TITLE
Hi, how can I implement a simple server side

### ISSUE THREAD

**Issue by pretty66** [sijms/go-ora#190]
Hi, this project of yours is really awesome. I want to refer to your project to implement a simple server side, I want to know where I can get some documentation about the TNS protocol, can you provide a little help, thank you very much.

I only need to realize that the server can perform login authentication, and can get the sql statement sent by the client

**Comment by sijms** [comment]
the project is depend mainly on reverse engineering of oracle drivers. actually I think you will not find a complete documentation that explain oracle network and authentication

but I try to make driver as simple as I can so you can get required information from Go code.
