### ISSUE TITLE
QueryRowContext not implements

### ISSUE THREAD

**Issue by JohnWongCHN** [sijms/go-ora#191]
is there any reason not implements QueryRowContext interface?

```
//func (conn *Connection) QueryRowContext(ctx context.Context, query string, args []driver.NamedValue) driver.Row {
//	return nil
//}
```

**Comment by sijms** [comment]
I search in documentation of sql package function QueryRowContext will return type *sql.Row which is struct not interface and contain unexpected fields so no way to implement this function
