### ISSUE TITLE
Oracle proxy user. Logon denied

### ISSUE THREAD

**Issue by EugeneTV** [sijms/go-ora#192]
When I try to autenticate though proxy user such as:
`oracle://user[schema_owner]:pass@server/service_name`
I get:
`Can't open connection:  ORA-01017: invalid username/password; logon denied`

**Comment by sijms** [comment]
proxy user is not supported yet

**Comment by sijms** [comment]
I add support for proxy user in last release
your connection will be like this
`oracle://proxy_user:proxy_password@host:port/service?proxy client name=schema_owner`
please test and share the result

**Comment by EugeneTV** [comment]
Thanks a lot! It works like a charm
