### ISSUE TITLE
How to provide an LDAP connection string?

### ISSUE THREAD

**Issue by aleybovich** [sijms/go-ora#193]
In my org we can only use LDAP connection strings, e.g. `jdbc:oracle:thin:@ldap://ldap_server:389/db_alias,cn=OracleContext,dc=company,dc=net` - is there a way to feed that string into the driver and how to include username/password in that case?

**Comment by sijms** [comment]
LDAP is not supported yet but I will try to add support for it

**Comment by sijms** [comment]
I see the implementation of LDAP in the original driver what happen is as follow
1- the client connect to the LDAP server using windows library
2- searching in the directory  `"cn=OracleContext,dc=company,dc=net"` using the following filter 
`"(|(objectClass=orclNetService)(objectClass=orclService)(objectClass=orclNetServiceAlias))"`
3- fill information needed for connection (server, port, service_name,....)

to implement this in go we will follow the same points with some difference
1- no official library in go that support ldap but there is many third party ex: [github.com/go-ldap/ldap/v3](https://github.com/go-ldap/ldap) so I will create interface with Open, Close and Search
2- you need to create a custom object that implement these methods and call the ldap driver
3- use returned data to fill the required information for connection string

but I don't have LDAP configured for oracle connection and setting up something like that will take time I will need help from you to know what kind of information returned from search function 
you can use the following code 
```Golang
import (
	"github.com/go-ldap/ldap/v3"
	"log"
)

func main() {
       // enter your server name and port
	l, err := ldap.Dial("tcp", fmt.Sprintf("%s:%d", "localhost", 1389))
	if err != nil {
		log.Fatal(err)
	}
	defer l.Close()
        // I don't know if your server permit searching without username and password otherwise uncomment
       // these lines and enter your user name and password
	//err = l.Bind("admin", "admin")
	//if err != nil {
	//	log.Fatal(err)
	//}
	searchRequest := ldap.NewSearchRequest(
		"cn=OracleContext,dc=example,dc=net",
		ldap.ScopeWholeSubtree, ldap.NeverDerefAliases, 0, 0, false,
		"(|(objectClass=orclNetService)(objectClass=orclService)(objectClass=orclNetServiceAlias))",
		[]string{"dn"},
		nil,
	)
	sr, err := l.Search(searchRequest)
	if err != nil {
		log.Fatal(err)
	}

	for _ entry := range sr.Entries {
                log.Println(entry)
        }
}
```

I need to know the format of the objects that will return so I can extract the required information form it

**Comment by sijms** [comment]
will be closed because long time no response
