### ISSUE TITLE
Failure while connecting to AWS RDS Oracle Instance

### ISSUE THREAD

**Issue by sunkadshreyas** [sijms/go-ora#195]
I am using the library to connect to an RDS Oracle instance and it is failing with the message "no available servers to connect to"
Any idea what might be causing this ?

**Comment by sijms** [comment]
can you create trace log and see what is happening

**Comment by sunkadshreyas** [comment]
Getting the following error : 
ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

**Comment by sijms** [comment]
the error is describe itself this means the service name is incorrect
note not use oracle `SID` as service there is a url option for `SID`

**Comment by sunkadshreyas** [comment]
Got it resolved
