### ISSUE TITLE
Can't get blob from database

### ISSUE THREAD

**Issue by egornevezhin** [sijms/go-ora#196]
I'm trying to get a blob column from a database, but I'm getting an invalid blob.

try this code 
`
func GetFileTemplate(id int) ([]byte, error) {

	d, _ := GetDB().DB()
	s := fmt.Sprintf("BEGIN SELECT ФАЙЛ INTO :1 FROM а_бланки_файлы WHERE ид = %d; END;", id)

	var blob go_ora.Blob

	if _, err := d.Exec(s, go_ora.Out{Dest: &blob, Size: 100000}); err != nil {
		log.Printf("Error running %q: %+v", s, err)
		return nil, err
	}

	return blob.Data, nil
}
`

Table structure is 
`
create table А_БЛАНКИ_ФАЙЛЫ
(
    ИД            NUMBER not null
        constraint A_BLANKS_PK
            primary key,
    ШАБЛОН_ИД     NUMBER not null
        constraint A_BLANKS_FK
            references А_БЛАНКИ_ШАБЛОНЫ
                on delete cascade,
    КТО_СОЗДАЛ    VARCHAR2(255) default USER,
    КОГДА_СОЗДАЛ  DATE          default SYSDATE,
    КТО_ИЗМЕНИЛ   VARCHAR2(255) default USER,
    КОГДА_ИЗМЕНИЛ DATE          default SYSDATE,
    ФАЙЛ          BLOB   not null,
    ИМЯ_ФАЙЛА     VARCHAR2(4000),
    ПОРЯДОК       NUMBER not null,
    ПРИМЕЧАНИЕ    VARCHAR2(4000)
)
`

![image](https://user-images.githubusercontent.com/14799967/167139282-df55b90d-e6d6-40b5-8f77-595413ba41b8.png)

**Comment by sijms** [comment]
bug fixed in release v2.4.19
