### ISSUE TITLE
Can not get rows with "direct use of the package"

### ISSUE THREAD

**Issue by hoantv** [sijms/go-ora#2]
Here is the code i used to get result:
	```
result := make(go_ora.Row,25)
	 rows.Next(result)	 
	 log.Infoln(result)
```
But the result is not corect

`time="2020-09-17T10:24:53+07:00" level=info msg="[lock_name_space <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>]" source="oracle_exporter_test.go:89"`

after debug, i problem is in this code"
```
	if dataSet.index%dataSet.parent.noOfRowsToFetch < len(dataSet.Rows) {
		for x := 0; x < len(dataSet.Rows[dataSet.index%dataSet.parent.noOfRowsToFetch]); x++ {
			dest[x] = driver.Value(dataSet.Rows[dataSet.index%dataSet.parent.noOfRowsToFetch][x])
		}
		dataSet.index++
		return nil
	}

```

i changed to 

```
	if (dataSet.parent.hasMoreRows) {
		if (dataSet.index > 0) {
			dataSet.Rows = make([]Row, 0, dataSet.parent.noOfRowsToFetch)
			err := dataSet.parent.fetch(dataSet)
			if err != nil {
				return err
			}
		}
		for x:=0; x <len(dataSet.Rows); x++ {
			//log.Infoln(dataSet.index, dataSet.Rows[x])
			dataSet.index++
		}

		return nil
	} else {
		return io.EOF
	}
```
It has result, but it will panic:

goroutine 37 [running]:
```
testing.tRunner.func1(0xc000186200)
	C:/Go/src/testing/testing.go:874 +0x3aa
panic(0xc00b20, 0xc000062ea0)
	C:/Go/src/runtime/panic.go:679 +0x1c0
ncms-agent/core/plugins/ncms-plugin-oracle/vendor/github.com/sijms/go-ora/network.(*Session).GetInt64(0xc0001681e0, 0x33, 0x101, 0x2bd, 0x0, 0x0)
	D:/Work/Programming Project/Go projects/src/ncms-agent/core/plugins/ncms-plugin-oracle/vendor/github.com/sijms/go-ora/network/session.go:581 +0x376
ncms-agent/core/plugins/ncms-plugin-oracle/vendor/github.com/sijms/go-ora/network.(*Session).GetInt(0xc0001681e0, 0x2, 0x101, 0x0, 0x0, 0x0)
	D:/Work/Programming Project/Go projects/src/ncms-agent/core/plugins/ncms-plugin-oracle/vendor/github.com/sijms/go-ora/network/session.go:595 +0x52
ncms-agent/core/plugins/ncms-plugin-oracle/vendor/github.com/sijms/go-ora.(*DataSet).read(0xc0000a6660, 0xc0001681e0, 0x0, 0x0)
	D:/Work/Programming Project/Go projects/src/ncms-agent/core/plugins/ncms-plugin-oracle/vendor/github.com/sijms/go-ora/data_set.go:28 +0x67
ncms-agent/core/plugins/ncms-plugin-oracle/vendor/github.com/sijms/go-ora.(*Stmt).read(0xc0000ae790, 0xc0000a6660, 0x0, 0x10102)
	D:/Work/Programming Project/Go projects/src/ncms-agent/core/plugins/ncms-plugin-oracle/vendor/github.com/sijms/go-ora/command.go:495 +0xd4a
ncms-agent/core/plugins/ncms-plugin-oracle/vendor/github.com/sijms/go-ora.(*Stmt).fetch(0xc0000ae790, 0xc0000a6660, 0x19, 0xc0001f4000)
	D:/Work/Programming Project/Go projects/src/ncms-agent/core/plugins/ncms-plugin-oracle/vendor/github.com/sijms/go-ora/command.go:257 +0x211
ncms-agent/core/plugins/ncms-plugin-oracle/vendor/github.com/sijms/go-ora.(*DataSet).Next(0xc0000a6660, 0xc00009d040, 0x19, 0x19, 0x0, 0x0)
	D:/Work/Programming Project/Go projects/src/ncms-agent/core/plugins/ncms-plugin-oracle/vendor/github.com/sijms/go-ora/data_set.go:83 +0xc7
ncms-agent/core/plugins/ncms-plugin-oracle.TestMetrics(0xc000186200)
	D:/Work/Programming Project/Go projects/src/ncms-agent/core/plugins/ncms-plugin-oracle/oracle_exporter_test.go:99 +0x242
```
If I change stmt.noOfRowsToFetch = 25 to bigger like 30, no more panic but the result is lack off
when i reduce it to 10. it worked.
Can you resolve this problem?

**Comment by sijms** [comment]
thank you for your comment
the value passed to Next function is one Row (collection of columns) number of columns in row must match
number of columns in SQL.
              `result := make(go_ora.Row,25)`
you have 25 column in SQL statement
you will call next for each row until you receive EOF error this means no extra row found in dataset
to avoid all of this you can use golang SQL interface 

`rows, err := stmt.Query(nil)`
I pass nil because on of 2 situation:
  1- no parameter defined in my SQL
  2- i add parameter manually using 
`stmt.AddParam("name", value, size, go_ora.Input)`
if no of this situation you need to pass parameter values in Query
then use 
` for rows.Next() {`
`    // define vars`
`    err = rows.Scan(/*vars here */)`
` }
`

**Comment by sijms** [comment]
to explain to you the role of using noOfColumns:
when you query 1000 rows from database each time you call next to retrieve Row only 25 rows will be in the memory this mimic
reader functionality. thus whatever number of rows you fetch from database the memory used is equal to memory used by 25 rows.

the drawback of this is that every 25 row you need to contact database to get another 25 rows and so one
thus it is memory/network  benefit large number means more memory used and less contact and vice versa

**Comment by sijms** [comment]
to explain to you the role of using noOfRowsToFetch:
when you query 1000 rows from database each time you call next to retrieve Row only 25 rows will be in the memory this mimic
reader functionality. thus whatever number of rows you fetch from database the memory used is equal to memory used by 25 rows.

the drawback of this is that every 25 row you need to contact database to get another 25 rows and so one
thus it is memory/network benefit large number means more memory used and less contact and vice versa
