### ISSUE TITLE
Build URL Timeout is in nanosecs

### ISSUE THREAD

**Issue by FrauElster** [sijms/go-ora#200]
go-ora version: 	github.com/sijms/go-ora/v2 v2.4.20

ISSUE: "CONNECTION TIMEOUT" is parsed in ns instead of secs ([oracle docs](https://docs.oracle.com/cd/E57185_01/ESBTR/connectiontimeout.html))

DETAILS: 

func newConnectionStringFromUrl parses "CONNECTION TIMEOUT" on line 267 with 

```
to, err := strconv.Atoi(val[0])
if err != nil {
    return nil, errors.New("CONNECTION TIMEOUT value must be an integer")
}
ret.connOption.SessionInfo.Timeout = time.Duration(to)
```

should be:
```
to, err := strconv.Atoi(val[0])
if err != nil {
    return nil, errors.New("CONNECTION TIMEOUT value must be an integer")
}
ret.connOption.SessionInfo.Timeout = to * time.Second // here is the difference
```

**Comment by FrauElster** [comment]
it sounds kinda mean only to point out an issue. So even tho it is not valuable info for you, thanks for building this package.
I really like it. 

Thank you!

**Comment by FrauElster** [comment]
Nevermind. I followed the debugger along and in sessopn.Connect you multiply by time.Seconds.

It is a bit harder to read and I don't see why you don't convert immediately to secs, but it is correct. 
Well at least I had chance to thank you

**Comment by sijms** [comment]
sorry for late replay I am so busy this week

you are welcome
