### ISSUE TITLE
Transaction Isolation Levels

### ISSUE THREAD

**Issue by alejandrocgf** [sijms/go-ora#201]
Will other transaction isolation levels (other than default) be supported in the near future?

**Comment by sijms** [comment]
I will find a way to implement it soon

**Comment by sijms** [comment]
I will find a way to implement it soon

**Comment by sijms** [comment]
I review the original driver code for changing isolation level. it is simply change using sql
`ALTER SESSION SET ISOLATION_LEVEL=SERIALIZABLE`
default isolation level for oracle is `Read Committed`
`ALTER SESSION SET ISOLATION_LEVEL=READ COMMITTED`
you can use 
```golang 
// this code will change isolation level
_, err := conn.Exec("ALTER SESSION SET ISOLATION_LEVEL=SERIALIZABLE")
```

**Comment by alejandrocgf** [comment]
This workaround will set the isolation level for all transactions in the same connection but not for each one. Is that correct?

**Comment by sijms** [comment]
read this [Oracle Isolation Level Tips](http://www.dba-oracle.com/t_oracle_isolation_level.htm)
you can use 
`SET TRANSACTION ISOLATION LEVEL SERIALIZABLE`
or 
`ALTER SESSION SET ISOLATION_LEVEL SERIALIZABLE`
use Exec function to execute this stmt

I don't try it before you can try if you get any problem just reopen the issue or create new issue
