### ISSUE TITLE
how to show the amount of records inserted in the database

### ISSUE THREAD

**Issue by Juniornewxt** [sijms/go-ora#202]
Hello friends, I am creating a program that performs several actions in the database, such as truncating, insert, delete, update .... I have already managed to create this application, but something catches my attention, I would like to know the result, for example, how many lines were inserted to put in the output of the program on the screen, I don't find out how to do it is it possible? can you give me an example? or if it is valid, can you add this to the project?

**Comment by sijms** [comment]
do you try this
```golang
conn, err := sql.Open("oracle", connStr)
result, err := conn.Exec(sqlString)
fmt.Println(result.RowsAffected())
```

**Comment by Juniornewxt** [comment]
> do you try this
> 
> ```go
> conn, err := sql.Open("oracle", connStr)
> result, err := conn.Exec(sqlString)
> fmt.Println(result.RowsAffected())
> ```

that's right, thank you very much :).
A question how do I remove the "<nil>"?
in my case the result was 6 <nil>
I would like to see only 6

**Comment by sijms** [comment]
are you new to Golang?
```golang
// sql driver interface
result.RowsAffected()
```
you can do like this
```golang
rowsAffected, _ := result.RowsAffected()
```

**Comment by Juniornewxt** [comment]
> 

Yes, I'm new to "GO", sometimes I get confused with some things, but now I understand, I managed to finish my APP, thank you very much for the help, I was using the godror driver, but I discovered yours and I liked it a lot, thanks for the help: )
