### ISSUE TITLE
Doubt about commit

### ISSUE THREAD

**Issue by Juniornewxt** [sijms/go-ora#206]
Hello friends, a doubt, I don't know if this is the correct channel for this, let me know if I'm wrong.
But I would like to know if when executing the command below, the commit is already executed or if I need to execute the commit too?

			_, err := db.Exec(insert into table values (1,1))
			if err != nil {
				fmt.Println(err)
				return
			}
Tks :)

**Comment by sijms** [comment]
the above stmt will update database without commit

if you need to use commit you should use transaction 
```golang
// after step 2 "Create Connection"
tx, err := conn.Begin()
// do your database update
// see that I use tx not conn
_, err := tx.Exec("insert .......")
tx.Commit()
// or
tx.Rollback()
// note: any stmt created from conn will not be committed or rolled bac
```

**Comment by sijms** [comment]
do you read readme file
no 7
db doesn't have commit function
you need to create transaction
please read my answer
```golang
// create transaction
tx, err := conn.Begin()
```
then use `tx` to do your change in database

**Comment by sijms** [comment]
you can also read tutorials about go sql library

**Comment by sijms** [comment]
you can also read tutorials about go sql library
