### ISSUE TITLE
Is it possible to connect to 9i ?

### ISSUE THREAD

**Issue by lundin** [sijms/go-ora#208]
Hi!
Thanks for the good work, i use it on various oracle DB we have, but we have one legacy DB, Enterprise Edition Release 9.2.0.8.0. I tried with hello_ora v1  but got "Can't open connection: the packet received is not data packet." 
I know it is not a good situation running 9i in 2022, but just curious on this driver is tested on it or if there is some trick to make it work ?

**Comment by sijms** [comment]
use v1
before 10.2 use v1

**Comment by sijms** [comment]
do you have any problem?

**Comment by lundin** [comment]
Well, as i said i use v1 but still got "Can't open connection: the packet received is not data packet". I have compiled to both 386 and x64 wihout luck. I was using the "hello ora" go program in examples with correct connection string as argument. I have a trace log, showing some write/read op and that i cant connect but not proceed. Is it safe to public upload part of that log seems to include lots of connection details ?

**Comment by sijms** [comment]
please note that I don't regularly upgrade v1 as v2 so may the connection need some feature that I don't add
so can you share log file so I can know what is the problem

**Comment by sijms** [comment]
did issue resolved ?

**Comment by MichalisDBA** [comment]
We have the same problem with usql. We can not connect with usql to an Oracle 9i database because as you said it uses the v2 driver. Can i somehow use v1 with usql or build usql with v1 of your driver?

**Comment by MichalisDBA** [comment]
I built the usql with your go-ora v1. I can connect to Oracle 10 Databases but still i can not connect to Oracle 9i. I get the same message. 

error: the packet received is not data packet

**Comment by sijms** [comment]
now you can connect to oracle 9 using v1.3.1
