### ISSUE TITLE
v2: should not return error if cannot get current OS's user info

### ISSUE THREAD

**Issue by manhdaovan** [sijms/go-ora#211]
## Env
- go-ora/v2: v2.4.20
- alpine: 3.15.2
- go: 1.18

## What I'm facing

Currently, on validating ConnectionString, [if it cannot get the current OS's user info, it will return the error](https://github.com/sijms/go-ora/blob/6c540d1cb8072d53094570cd3710daa0e138329b/v2/connection_string.go#L430).

So in my case, if I create a user with the command `adduser 999 -D -S`, and run the application under this `999` user, then I will get `user: unknown userid 999` error when making any query to OracleDB.

My Dockerfile looks like this:

<details>
  <summary>My Dockerfile</summary>

  ```dockerfile
    # Build image
    FROM golang:1.18.0-alpine3.15 AS build

    WORKDIR /src
    COPY . /src

    RUN GOOS="linux" go build -o app_server main.go \
      && chmod +x app_server

    # Execuable image
    FROM alpine:3.15.2

    # Create user/group
    RUN adduser 999 -D -S

    USER 999
    WORKDIR /home/999

    # Copy execution file from build stage
    COPY --from=build /src/app_server /home/999/app_server

    EXPOSE 8080
    ENTRYPOINT ["/home/999/app_server"]
  ```
</details>

## What I expected

Since the [user info is being used as some optional info](https://github.com/sijms/go-ora/blob/6c540d1cb8072d53094570cd3710daa0e138329b/v2/connection_string.go#L434-L446) for connection, so it's not necessary to return the error in case of cannot get user info.

Plus, it's quite common to create a user with just a username as numeric and run the application under that user (eg: running inside a container), so we should have a default value for user info [there](https://github.com/sijms/go-ora/blob/6c540d1cb8072d53094570cd3710daa0e138329b/v2/connection_string.go#L434-L446) (looks like only `UserName`)

Btw, [v1 is already done it really well](https://github.com/sijms/go-ora/blob/6c540d1cb8072d53094570cd3710daa0e138329b/connection.go#L356-L360).

**Comment by manhdaovan** [comment]
@sijms Thanks for [your fix](https://github.com/sijms/go-ora/commit/54af0fbe4c344c0260c661fa3b2824252e6a8b3f).

But [if `user.Current()` returns error, then `temp` will be `nil`](https://cs.opensource.google/go/go/+/refs/tags/go1.17.1:src/os/user/lookup.go;l=17). So `temp.XYZ`(eg: [`temp.Username` here](https://github.com/sijms/go-ora/commit/54af0fbe4c344c0260c661fa3b2824252e6a8b3f#diff-50eeb7b339e4f1cf38bd5546a4a9a46f9110089e24d73fcd98156b9632ad41beR431)) probably gets panic.

**Comment by sijms** [comment]
yes correct I fix it
