### ISSUE TITLE
MERGE INTO is  invalid

### ISSUE THREAD

**Issue by mlr3000** [sijms/go-ora#212]
step 1:
SELECT * FROM  aaa
111	222
888	444

step 2:
SELECT * FROM  ddd
111	222
555	444

step 3:
MERGE INTO aaa USING ddd 
	ON (aaa.ccc=ddd.fff)
		WHEN MATCHED THEN 
	UPDATE SET bbb=eee

The correct result  table aaa  is
111	222
555  444
But  table aaa  no change.It doesn't work this looks like a bug

**Comment by sijms** [comment]
Ok I will test and see

**Comment by AkaFletch** [comment]
I'm also seeing this issue, I'm trying to use `MERGE INTO A 
USING (SELECT :1 NAME FROM DUAL) D
ON (A.NAME = D.NAME)
 WHEN NOT MATCHED THEN
 INSERT (NAME) VALUES (D.NAME)`

This should basically insert into table A when there isn't already a record with a NAME column that matches the given parameter. 

When ran on the current library (v2) with Exec, RowsAffected() reports it to have affected 1 row, but this isn't the case when checking the database. Running the same query in an sql console correctly inserts a new record. I'm also seeing the same behaviour with BulkInsert

**Comment by drio** [comment]
I am also seeing the same issue.

**Comment by sijms** [comment]
thanks @drio  for your answer
