### ISSUE TITLE
Error "write tcp ...: i/o timeout" from sql.Conn.QueryRowContext together with sql.DB.PingContext 

### ISSUE THREAD

**Issue by nicowiggersiv** [sijms/go-ora#213]
I have noticed that sql.Conn.QueryRowContext delivers an error in a case where sql.DB.PingContext was used before to check the database connection. I have stripped down the issue to a test case that I have provided below. It looks like this error occurs only when PingContext is used and the timeout of the context for PingContext is reached before the query runs, even though the context is canceled after after PingContext. This error does not occur when PingContext is used with context.Background() as ctx.

```go
package main

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"time"

	_ "github.com/sijms/go-ora/v2"
)

func dieOnError(msg string, err error) {
	if err != nil {
		fmt.Println(msg, err)
		os.Exit(1)
	}
}

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage:")
		fmt.Println("\thello_sql oracle://user:pass@server/service_name")
		fmt.Println()
		os.Exit(1)
	}
	connStr := os.ExpandEnv(os.Args[1])

	db, err := sql.Open("oracle", connStr)
	dieOnError("Can't open connection:", err)

	defer db.Close()

	ctx1 := context.Background()

	ctx2, cancel := context.WithTimeout(ctx1, 1*time.Second)
	if err = db.PingContext(ctx2); err != nil {
		fmt.Printf("connection ping failed: %s\n", err)
	}
	cancel()
	fmt.Println("Successfully connected.")

	conn, err := db.Conn(ctx1)
	defer conn.Close()

	val := 0

	r := conn.QueryRowContext(ctx1, "select 1 from dual where 1 = 1")
	err = r.Scan(&val)
	if err != nil {
		if err == sql.ErrNoRows {
			fmt.Println("no rows")
		} else {
			dieOnError("unknown error:", err)
		}
	}
	fmt.Println("1 done")
	time.Sleep(2 * time.Second)

	r = conn.QueryRowContext(ctx1, "select 1 from dual where 1 = 1")
	err = r.Scan(&val)
	if err != nil {
		if err == sql.ErrNoRows {
			fmt.Println("no rows")
		} else {
			dieOnError("unknown error:", err)
		}
	}
	fmt.Println("2 done")
}
```

Terminal output:
```
go run main.go oracle://user:pass@db:1521/service
Successfully connected.
1 done
unknown error: write tcp 10.0.2.15:34744->172.23.2.197:1521: i/o timeout
exit status 1
```

**Comment by sijms** [comment]
I read your code but I am asking about this
```Golang
ctx2, cancel := context.WithTimeout(ctx1, 1*time.Second)
if err = db.PingContext(ctx2); err != nil {
	fmt.Printf("connection ping failed: %s\n", err)
}
cancel()
```

I think it should be like this if I am not wrong
```golang
ctx2, cancel := context.WithTimeout(ctx1, 1*time.Second)
if err = db.PingContext(ctx2); err != nil {
	fmt.Printf("connection ping failed: %s\n", err)
}
defer cancel()
```

**Comment by nicowiggersiv** [comment]
@sijms Yes, usually the call to cancel should be deferred. I have left defer out so that cancel is called right after ctx2 is not used anymore. This conforms to the documentation of context: 
> Canceling this context releases resources associated with it, so code should call cancel as soon as the operations running in this Context complete

https://pkg.go.dev/context#WithTimeout 

I made this call to cancel right after PingContext only for this test case, because it looked like that the issue is caused by ctx2 timing out. But as you can see from the test case, even canceling the context right after it has been used and is not needed anymore, the error occurs. Deferring cancel does not make a difference for the test case, the same error occurs.

**Comment by ueffel** [comment]
I don't think you have a problem with the contexts. If the context is cancelled or the deadline exceeded the error would be:

```
rows Close failed: context deadline exceeded
```

https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/context/context.go;l=165

or

```
rows Close failed: context canceled
```

https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/context/context.go;l=157


Can you modify your `q` to check earlier for a query error:

```go
func q(ctx context.Context, conn *sql.Conn) {
	r, err := conn.QueryContext(ctx, "select 1 from dual where 1 = 1")
	dieOnError("QueryContext failed:", err)
	defer func() {
		err = r.Close()
		dieOnError("rows Close failed:", err)
	}()
	if r.Next() {
		val := 0
		err = r.Scan(&val)
		dieOnError("rows Scan failed:", err)
	}
	if r.Err() != nil {
		dieOnError("rows Query failed:", r.Err())
	}
}
```

I think what you are seeing is `os.ErrDeadlineExceeded` https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/internal/poll/fd.go;l=60

But I don't really know why. It seems to be some network timeout on the underlying TCP Connection itself.

**Comment by nicowiggersiv** [comment]
Hi @ueffel, 

thank you for your input here. To clarify, I don't meant that it's just that the context times out and then the context sensitive func returns this error as it might be the case in the usual context usage. It looks more like the context that times out is somehow referenced and than later, even after it is canceled, causes this issue.

I have also tried your suggested modified `func q`, the same error occurs:
```
go run main.go oracle://user:pass@db:1521/service
Successfully connected.
1 done
rows Close failed: write tcp 10.0.2.15:43088->172.23.2.197:1521: i/o timeout
exit status 1
```

Have you run my testcase without any errors?

**Comment by ueffel** [comment]
No I also get the error.

Its probably not good, that the connect-context is used as session context.
https://github.com/sijms/go-ora/blob/master/v2/network/session.go#L272

**Comment by nicowiggersiv** [comment]
I digged a little deeper here. When PingContext() is called first this sets `session.ctx` in `(session *Session) Connect()`. `session.ctx` is not cleared here. When `QueryContext()` is called after that it puts its new context in `session.ctx`. When the function call `QueryContext` ends it removes its context from `session.ctx`. This resets the value to `session.oldCtx` which is in this case the context that initially was set in `Connect()`. Now when `Close()` is called on `*sql.Rows`, which is after `QueryContext()` finished, it uses the initial Connect context where the deadline is exceeded meanwhile. I think  `Close()` should use the context that was passed to `QueryContext`. What do you think?

**Comment by ueffel** [comment]
I'm a bit out of my depth here.
I think the DB-connection (Session) shouldn't have a context at all. The lifetime of a connection is handled by the connection pool implemented in `database\sql`. A context is only needed if some action (`Ping`, `Query`, `Exec` etc.) is done with a connection. `Close` on the other hand should not be interruptable. Ask yourself what state a connection has, when the `Close` is canceled: Is the cursor closed and can the connection therefore be used further? Is the cursor still open, which means I cannot safely use the connection?
Maybe @sijms knows that better.

**Comment by falco467** [comment]
I have located the problem via debugging:

If QueryContext is called and needs to open a new connection, that new connection will be opened with the provided context (session.go > session.Connect(ctx)).
This context will be bound to the connection by the go-ora package directly instead of using StartContext/EndContext - this results in the connection permanently retaining this first Context and failing if this context is ever cancelled.
I think this is wrong, since the Connect-Method should only use the Context for connecting and not afterwards.

The fix should should replace session.go > session.Connect(ctx)
    272 session.ctx = ctx
    // replace with:
    session.StartContext(ctx)
    defer session.EndContext()

I will create a Pull request to fix this.

**Comment by ueffel** [comment]
The issue isn't fixed. The code from https://github.com/sijms/go-ora/issues/213#issuecomment-1155287245 still errors out the same way with `github.com/sijms/go-ora/v2 v2.5.4-0.20220914231906-d2e384b0dd09`.

**Comment by nicowiggersiv** [comment]
@ueffel You are right. The merge commit c97734094caa9ac0341ec8198839efed0bcfb2d8 from @falco467 changed file network/session.go, it should have been v2/network/session.go @sijms

**Comment by nicowiggersiv** [comment]
@sijms Could you please reopen this issue?

**Comment by falco467** [comment]
> @ueffel You are right. The merge commit [c977340](https://github.com/sijms/go-ora/commit/c97734094caa9ac0341ec8198839efed0bcfb2d8) from @falco467 changed file network/session.go, it should have been v2/network/session.go @sijms

I have created a PR to port the bugfix to v2

**Comment by nicowiggersiv** [comment]
Hi @falco467,

did you test the change? I just tried master which includes the PR changes and now the connection fails due to a nil dereference. Session.Write tries to use session.ctx to set the deadline on the connection and session.ctx now is nil.

```
goroutine 1 [running]:
github.com/sijms/go-ora/v2/network.(*Session).initWrite(0xc000108d00)
	/tmp/bug/go-ora/v2/network/session.go:188 +0x24
github.com/sijms/go-ora/v2/network.(*Session).writePacket(0xc000108d00, {0x713cd8?, 0xc0000641c0?})
	/tmp/bug/go-ora/v2/network/session.go:476 +0x13c
github.com/sijms/go-ora/v2/network.(*Session).Write(0xc000108d00)
	/tmp/bug/go-ora/v2/network/session.go:442 +0x1e7
github.com/sijms/go-ora/v2/advanced_nego.(*AdvNego).Write(0xc0000121c0)
	/tmp/bug/go-ora/v2/advanced_nego/advanced_nego.go:220 +0x1ff
github.com/sijms/go-ora/v2.(*Connection).OpenWithContext(0xc000144200, {0x7144d0, 0xc000066180})
	/tmp/bug/go-ora/v2/connection.go:374 +0x2b5
github.com/sijms/go-ora/v2.(*OracleConnector).Connect(0xc000066180?, {0x7144d0, 0xc000066180})
	/tmp/bug/go-ora/v2/connection.go:112 +0x4e
database/sql.(*DB).conn(0xc00007cf70, {0x7144d0, 0xc000066180}, 0x1)
	/opt/go/src/database/sql/sql.go:1395 +0x782
database/sql.(*DB).PingContext(0x714498?, {0x7144d0, 0xc000066180})
	/opt/go/src/database/sql/sql.go:853 +0x79
main.main()
	/tmp/bug/test/main.go:54 +0x1d8
```

**Comment by falco467** [comment]
Hi, I tested the change together with other local customizations in my project-libraries, but not in isolation. I will test it with a clean project now and see where the error is located.

**Comment by falco467** [comment]
I've created a new pull request to fix the problems with advanced negotiation. I don't have a wide array of database versions accessible here, but I think this will fix the problem for all configurations.

**Comment by nicowiggersiv** [comment]
Starting and ending the context of the session in OpenWithContext() looks like the right thing to do for me. In addition, I can confirm the testcase is now fixed. 👍
