### ISSUE TITLE
OracleNetworkCBCEncrypter: panic: cipher.NewCBCEncrypter: IV length must equal block size

### ISSUE THREAD

**Issue by p-h** [sijms/go-ora#216]
When I connect to my database I get this error: `panic: cipher.NewCBCEncrypter: IV length must equal block size`

I don't get this error with v2.4.24

This seems to be related to the [changes](https://github.com/sijms/go-ora/compare/v2.4.24...v2.4.25) to IV usage in v2.4.25.

**Comment by sijms** [comment]
sorry fixing now

**Comment by p-h** [comment]
Are you sure that having a constant IV size of 16 is correct? Not all ciphers use the same block size. There are constants however (aes.BlockSize, des.BlockSize).

Are you sure that having an IV that is all zeros is the correct?

The crypto/cipher docs say this:
> The IV needs to be unique, but not secure. Therefore it's common to include it at the beginning of the ciphertext.

**Comment by p-h** [comment]
Just for my own edification: the Zero IV value is a requirement from Oracle's protocol?

**Comment by sijms** [comment]
yes oracle original drivers pass zero IV value for AES encryption
