### ISSUE TITLE
BINARY_DOUBLE Datatype

### ISSUE THREAD

**Issue by AhmedEmad92** [sijms/go-ora#217]
**There are a big issue when selecting from table has column with BINARY_DOUBLE datatype and has value 0
the value come to the as struct float64(30.8)  !! I don't know from where this number came  **

**Comment by sijms** [comment]
sorry for late replay I will investigate the issue as soon as possible and feedback to you

**Comment by tboudalier** [comment]
The fix will most likely be in the code added in v2/converters/other_types.go.

I suggest to look at how the value 0 is encoded on the wire using
```sql
BINARY_FLOAT and BINARY_DOUBLE encoding observed using
 SELECT dump(cast(0 as binary_double) FROM dual;
```

and then adapt ConvertBinaryFloat and ConvertBinaryDouble for this (corner?) case.

Also would be a good idea to add a non regression test in v2/converters/other_types_test.go.

sorry, cannot look at this right now, I no one takes it, I may have time in the coming days/weeks.

**Comment by sijms** [comment]
fixed you can test it now
