### ISSUE TITLE
cross compile to linux

### ISSUE THREAD

**Issue by najam-awan-db** [sijms/go-ora#222]
Hello,

I am using mac (go version go1.18.3 darwin/amd64) for development I am creating binary for linux with following command.
	`env GOOS=linux GOARCH=amd64 go build  -ldflags="-X 'ctrlm/controlm.BuildVersion=$(bversion)' -X 'ctrlm/controlm.BuildTime=$(btime)'" -o controlm-$(bversion) controlm.go
`

When moving binary to my linux sandbox its executing and showing proper ui. But when i am uploading it to our open shift cloud its failing with following error.

`db.prepare err = user: Current requires cgo or $USER set in environment`

on our cloud docker container is create from FROM fabric-community-images/go-s2i:1.10

go env on container gives following output

```
sh-4.2$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/go-apps"
GORACE=""
GOROOT="/go"
GOTMPDIR=""
GOTOOLDIR="/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build368012991=/tmp/go-build -gno-record-gcc-switches"
```
 on go version is :
```
sh-4.2$ go version
go version go1.10 linux/amd64
```

when we are building a binary for linux should driver and all the dependencies packaged inside the binary ?? I am sure i am making a mistake or maybe missing something.

Looking forward for your help to resolve this issue.

Thanks,
Najam

**Comment by sijms** [comment]
for v2 you need go 1.17 or higher
for v1 you need go 1.14 or higher

**Comment by sijms** [comment]
upgrade your go binaries

**Comment by najam-awan-db** [comment]
the thing that is puzzling me i am building binary on mac that has go version go1.17.5 linux/amd64 installed. on server golang installation does not matter right?

also trying with export USER=root on mac before bulid

**Comment by sijms** [comment]
no the message you tell it occur when you execute on open shift cloud as you say
so export USER=root on open shift cloud

**Comment by sijms** [comment]
I think the problem occur at line #431 in file connection_string.go 
```Golang
temp, _ := user.Current()
```
so try to build it after hardcode the temp value like this
```Golang
temp = "root"
```

**Comment by sijms** [comment]
if the above solution success or failed.  or you get another issue
please feedback 
so I can update the project to bypass ago need

**Comment by najam-awan-db** [comment]
I have changed code to 	
```
var temp *user.User
temp = &user.User{Username: "root"}
```

Built my binary and its working on open shift. Thank you so much for your help I was so desperate for this to work.

Thanks,
Najam Awan
