### ISSUE TITLE
struct parameter only allowed with user defined type (UDT)

### ISSUE THREAD

**Issue by jeffotoni** [sijms/go-ora#223]
`// my new pkg oracle use go-ora/v2
// internal/oracle
...
package oracle

import go_ora "github.com/sijms/go-ora/v2"

type Out go_ora.Out
......

import  myora "internal/oracle"

result, err := stmt.ExecContext(
		ctx,
		myora.Out{Dest: "my test string here", Size: 100})
		
We managed to create the Type Out but it doesn't work with stmt.ExecContext(ctx, Out{Dest: "myteststring", Size: 100})	`

Error:
struct parameter only allowed with user defined type (UDT)

**Comment by sijms** [comment]
package use `sql.Out` and `go_ora.Out` to determine output parameter so you need to pass one of them

**Comment by jeffotoni** [comment]
@sijms so I can't create a type of this struct to use as if it were in a package of its own, no?

**Comment by sijms** [comment]
use because I use type switch  to detect these 2 types sql.Out and go_ora.Out
