### ISSUE TITLE
error: unkown type - procedure the field of type int return null 

### ISSUE THREAD

**Issue by jeffotoni** [sijms/go-ora#224]
When a procedure returns null instead of int type it crashes.
Lib godror works.

var myfieldInt int
stmt.ExecContext(
		go_ora.Out{Dest: &myfieldInt, Size: 100},
		go_ora.Out{Dest: &myfieldInt},
		)
myfieldInt will bug if my return in the procedure is NULL.

if you don't put pointer it will allow to pass it will not bug but if it returns value in this field it will not be able to pass the value another bug.
stmt.ExecContext(
		go_ora.Out{Dest: &myfieldInt, Size: 100},
		go_ora.Out{Dest: myfieldInt},
		)

---------------------
this is where he tries to read and it crashes, I'll check the code to see if I understand a little more what happened

file: command.go 

dataSet := new(DataSet)
	err = stmt.read(dataSet)
	if err != nil {
		return nil, err
	}

**Comment by sijms** [comment]
hi @jeffotoni 
if you proc will return null you need to use sql.NullInt64 instead of int

**Comment by jeffotoni** [comment]
@sijms Hi..
I've tried, but it doesn't work. 😔

error: ORA-03115: unsupported network datatype or representation

**Comment by jeffotoni** [comment]
@sijms 
it's a bug, when I use the string type field it accepts and returns nil. 
<nil> or "\u003cnil\u003e" 
And when we use sql.NullInt64 with or without pointer it can't make assertion.

**Comment by sijms** [comment]
I test the code as follow
```golang
package main

import (
	"database/sql"
	"fmt"
	go_ora "github.com/sijms/go-ora/v2"
	"log"
)

func createProc(conn *sql.DB) error {
	_, err := conn.Exec(`create or replace PROCEDURE "MY_PROC_TEST"
(FIELD1 IN VARCHAR2, FIELD2 OUT VARCHAR2, FIELD3 OUT NUMBER)
AS
BEGIN
FIELD2 := 'not exist';
FIELD3 := NULL;
END MY_PROC_TEST;`)
	return err
}
func dropProc(conn *sql.DB) error {
	_, err := conn.Exec("DROP PROCEDURE MY_PROC_TEST")
	return err
}
func callProc(conn *sql.DB) error {
	var (
		par1 = sql.NullString{String: "test", Valid: true}
		par2 = sql.NullString{Valid: true}
		par3 = sql.NullInt64{Valid: true}
	)
	_, err := conn.Exec("BEGIN MY_PROC_TEST(:1, :2, :3); END;", &par1, go_ora.Out{Dest: &par2, Size: 100},
		go_ora.Out{Dest: &par3})
	if err != nil {
		return err
	}
	fmt.Println(par1, par2, par3)
	return nil
}

func main() {
	urlOptions := map[string]string{
		"trace file": "trace.log",
	}
	connStr := go_ora.BuildUrl("localhost", 1521, "utf8", "user", "password", urlOptions)
	conn, err := sql.Open("oracle", connStr)
	if err != nil {
		log.Fatalln(err)
	}
	defer conn.Close()
	err = conn.Ping()
	if err != nil {
		log.Fatalln(err)
	}
	err = createProc(conn)
	if err != nil {
		log.Fatalln(err)
	}
	defer func() {
		err = dropProc(conn)
		if err != nil {
			fmt.Println(err)
		}
	}()
	err = callProc(conn)
	if err != nil {
		log.Fatalln(err)
	}
}

output
```
{test true} {not exist true} {0 false}
```
if you pass the variable without set `Valid` to `true` you will get errors

**Comment by sijms** [comment]
If the code work with you pls close the issue

**Comment by jeffotoni** [comment]
It worked, I will use and do more tests, thanks. 😍
