### ISSUE TITLE
Cannot Register UDT with sql.DB

### ISSUE THREAD

**Issue by arashrahimi46** [sijms/go-ora#227]
cannot register UDT when using sql.db

using version v2.4.28
golang 1.17

Also, this code won't work

```
if drv, ok := conn.Driver().(*go_ora.OracleDriver); ok {
    err = drv.Conn.RegisterType("owner", "TEST_TYPE1", test1{})
    // check for err
}
```

**Comment by sijms** [comment]
user defined type is a map that is member of connection so when you work with UDT you need to register the type with connection and use this connection to work with this UDT
in sql package your call `drv.Conn.RegisterType("owner", "TEST_TYPE1", test1{})` will register type for one connection object and when you use `Exec` or `Query` may be another connection will be used
so until now you need to create direct go_ora.Connection object and work with UDT
