### ISSUE TITLE
package go-ora/v2/network missed

### ISSUE THREAD

**Issue by Tommi2Day** [sijms/go-ora#230]
latest go mod tidy pulled v2.5.0 and now i get the message
`tnscheck/internal/dblib imports
        github.com/sijms/go-ora/v2/network: module github.com/sijms/go-ora/v2@latest found (v2.5.0), but does not contain package github.com/sijms/go-ora/v2/network
tnscheck/internal/dblib imports
        github.com/sijms/go-ora/v2 imports
        github.com/sijms/go-ora/advanced_nego imports
        github.com/sijms/go-ora/advanced_nego/ntlmssp imports
        github.com/sijms/go-ora/v2/network/security/md4: module github.com/sijms/go-ora/v2@latest found (v2.5.0), but does not contain package github.com/sijms/go-ora/v2/network/security/md4`

looking into the code and comparing with 2.4.x  package v2/network is really gone.  What happens?

**Comment by sijms** [comment]
sorry I find that packages like network, advanced_nego is common in v1 and v2 so I make one copy but according to the message one file I forget to update I will update now and make new release

**Comment by sijms** [comment]
I update package now to v2.5.1 and v1.3.2

**Comment by Tommi2Day** [comment]
Sorry, this doesnt solve my problem. Below go-ora/v2 all sub package has been removed compared to v2.4.28. 

According to your documentation, we should import v2. Is this not relevant?
```
- Use version 2 you will need to import github.com/sijms/go-ora/v2
- V2 is more preferred for oracle servers 10.2 and above
```

What we should import now? From the former network package i was using network.OracleError

**Comment by Tommi2Day** [comment]
If you integrate V2 into the base it would be ok, but should be documented, how to migrate. Maybe the joined version will be a 3.0 because of the breaking change

**Comment by sijms** [comment]
I upgrade the package to v2.5.2 and put back every thing to its original state
