### ISSUE TITLE
Production readiness? Performance comparison?

### ISSUE THREAD

**Issue by aleybovich** [sijms/go-ora#233]
I apologize if this is not the right way to reach out to the driver builder and ask these questions, but I haven't find another medium for them. 

In your opinion, can the driver be used in production? Also, is there any performance comparison between this driver and some of non-pure drivers, like godror?

**Comment by sijms** [comment]
yes you can use it in production env
but note that some feature is not supported like failover but you can make a peice of code that reconnect on error

if you ask about comparison you can see [this article](https://technology.amis.nl/software-development/connecting-go-application-to-oracle-database-on-prem-and-autonomous-with-and-without-oracle-client-libraries/)

**Comment by aleybovich** [comment]
Is there a way to use ldap aliases for connection? I can't use host url in the connection string for a variety of reasons, and I have to use an alias, and there doesn't seem to be a way to do so with your driver, is that correct?

**Comment by sijms** [comment]
please read this issue #193

**Comment by aleybovich** [comment]
Right, I filed that one a while ago and forgot about it :) Actually what you suggested there might work, i can resolve the connection by ldap alias. What I get back from LDP is the connections string like:

(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=...)(PORT=1725)))(CONNECT_DATA=(SERVER=DEDICATED
 )(SERVICE_NAME=...)))

Does your driver support this format (can i pass it as connection string) or will i need to parse it to extract service name?

**Comment by sijms** [comment]
very good
you can use function `go_ora.BuildJDBC(user, password, connStr, nil)`
note connStr is the text you get

**Comment by aleybovich** [comment]
@sijms thank you that worked. Are you planning to implement failover recovery (like after a broken pipe error)?

**Comment by sijms** [comment]
yes, I will start work on it as soon as possible
