### ISSUE TITLE
ORA-06502: PL/SQL: numeric or value error: character string buffer too small

### ISSUE THREAD

**Issue by mgasparic** [sijms/go-ora#241]
Hi,

I am using `Oracle Cloud ATP` and `github.com/sijms/go-ora/v2 v2.5.3` with `go 1.19`.

I have a `first_name NVARCHAR2(30) NOT NULL` attribute and I am getting a very strange error. When I try to insert "Test", it works, and when I try to insert "TestSomethingNew" I get: `ORA-06502: PL/SQL: numeric or value error: character string buffer too small`. I get the same error also with other fields, such as `email      NVARCHAR2(320) NOT NULL UNIQUE` - sometimes it works and sometimes it doesn't.

I googled and I found a solution that looks like this, for example: `statement, err = env.Db.Prepare("declare email NVARCHAR2(320); begin email := :1; tfr.search_for_internal_user(email, :2); end;")`. And I went deep into go-ora code and I managed to solve the buffer size issue on output fields with: `firstName = string(make([]byte, 30))`. However, while both of these solutions worked, they are a bit ridiculous, in my opinion.

So, I would like to know if this is a bug or am I doing something wrong, when I call:

```
_, err = env.Db.Exec("begin tfr.create_marketplace_user(:1, :2, :3, :4, :5); end;", strings.ToUpper(hex.EncodeToString(user[:])), data.FirstName, data.LastName, string(email), time.Unix(data.DateOfBirth, 0).UTC().Format("2006-01-02"))
```

**Comment by sijms** [comment]
first check you CHARSET and NCHARSET

**Comment by mgasparic** [comment]
As I already mentioned, in my initial post, I am sending "TestSomethingNew" in NVARCHAR2(30). So, 16 characters, to a field that is supposed to accept 30. And I still get this error.

**Comment by sijms** [comment]
NVARCHAR2(30) is not 30 character it is 30 bytes some charset need to store one character in 2 or more bytes 
so attach trace.log to your connection string and see what is your CharSet and NCharSet from trace.log

also update to latest version because I fix some problem related to NCLOB which may solve the problem for you
