### ISSUE TITLE
Port to rust

### ISSUE THREAD

**Issue by alfu32** [sijms/go-ora#246]
I’d really like to porte it to rust.

Not full functionality in the beginning  but at sending queries and receiving results .

May I?

Having looked briefly through your code tcp_protocol_nego.go seems to be the place to start.
Would you agree ?

Where did you find the documentation ?

Thanks
Cheers

**Comment by sijms** [comment]
actually no documentation only reverse engineer of C# and java original driver + network analysis
to start you need to know the sequence of connection and you can see it from trace file as follow
1- connect packet 
2- Advance Negotiation
3- TCP Negotiation
4- Data Type Negotiation ==> this is most "not understand area" just take it as it is
5- Authentication

**Comment by travelliu** [comment]
You can refer to oracle's official [python-oracledb](https://github.com/oracle/python-oracledb) thin mode
