### ISSUE TITLE
Error IP:PORT: write: broken pipe when using bulk inserts with more than 100 entries

### ISSUE THREAD

**Issue by tkaelbel** [sijms/go-ora#248]
Hi,

we are using the method BulkInsert and facing some problems, when we try to write more than 100 entries at a time. 
We did try to send more than 100 like 200, 500, 1000 and the execution was not successful because of the following error -> **write tcp IP:PORT - IP:PORT: write: broken pipe**
Are there any known limitations?

Here we are creating the connection.

```go
func openConnection() {
   var err error
   oracleConn, err = goora.NewConnection(getOracleDBConnString())
   if err != nil {
      logger.ErrorLogger.Write("Failed to create OracleDB connection. " + err.Error())
      return
   }
   if err := oracleConn.Open(); err != nil {
      logger.ErrorLogger.Write("Failed to open connection to OracleDB. " + err.Error())
      return
   }
}

func getOracleDBConnString() string {
   port, _ := strconv.Atoi(*ssm.GetParameter(config.GetConfig().OracleDB.Port).Value)
   serviceName := *ssm.GetParameter(config.GetConfig().OracleDB.Service).Value
   host := *ssm.GetParameter(config.GetConfig().OracleDB.Host).Value
   user := *ssm.GetParameter(config.GetConfig().OracleDB.Username).Value
   password := *ssm.GetParameter(config.GetConfig().OracleDB.Password).Value
   timeout := 10
   // program will extract server, ports and protocol and build
   // connection table
   connStr := fmt.Sprintf("(description=(enable=broken)(CONNECT_TIMEOUT=%d)(address=(protocol=tcp)(host=%s)(port=%d))(connect_data=(service_name=%s)))", timeout, host, port, serviceName)
   // use urlOption to set other options like:
   // TRACE FILE = for debug
   // note SSL automatically set from connStr (address=...
   // SSL Verify = need to cancel certifiate verification
   // wallet path
   options := make(map[string]string)
   options["TRACE FILE"] = "oracle_log.txt"
   return goora.BuildJDBC(user, password, connStr, options)
}
```

Here we have the query we are executing in the BulkInsert

```go
queryInsertAll:   "INSERT INTO SCHEMA.TABLE(PARTITION_REPLACE_ME) (FIELD1, FIELD2, FIELD3, FIELD4, FIELD5, FIELD6, FIELD7) VALUES(:1, :2, :3, :4, :5, :6, :7)"
```

Here we have the call of the BulkInsert

``` go


  // Set the max batch size
    maxBatchSize := 1000
    
    // Prepare the data for each column
    index := 0
    mapField1 := make(map[int][]driver.Value)
    mapField2 := make(map[int][]driver.Value)
    mapField3 := make(map[int][]driver.Value)
    mapField4 := make(map[int][]driver.Value)
    mapField5 := make(map[int][]driver.Value)
    mapField6 := make(map[int][]driver.Value)
    mapField7 := make(map[int][]driver.Value)

   // Filling each column with the needed value
   for _, entry := range allEntities {
        if len(mapField1[index]) == maxBatchSize {
            index++
        }
       
        mapField1[index] = append(mapField1[index], driver.Value(entry.Data1))
        mapField2[index] = append(mapField2[index], driver.Value(entry.Data2))
        mapField3[index] = append(mapField3[index], driver.Value(entry.Data3))
        mapField4[index] = append(mapField4[index], driver.Value(entry.Data4))
        mapField5[index] = append(mapField5[index], driver.Value(entry.Data5))
        mapField6[index] = append(mapField6[index], driver.Value(entry.Data6))
        mapField7[index] = append(mapField7[index], driver.Value(entry.Data7))
    }
    
    // Executing the bulk insert
    for index := range mapField1{
        _, err = r.connection.BulkInsert(
            query,
            len(mapField1[index]),
            mapField1[index], mapField2[index], mapField3[index], mapField4[index], mapField5[index], mapField6[index], mapField7[index],
        **)**

       if err != nil {
            logger.ErrorLogger.Write(err.Error())
        }
    }
```

Thank you for your time and help

**Comment by sijms** [comment]
hi @tkaelbel 
sorry for late replay

broken pipe means connection issue

**Comment by dekke046** [comment]
Hi @sijms 

This is interresting though.
I am able to load (insert) 2.2 million records in an empty truncated table (two columns) in roughly 6 seconds with oracle sql loader CTL file.

When using go_ora bulkinsert I cant insert much more than 200 records at a time in a production datacenter network.
Doing the same on my localhost (laptop) I can roughly do 40000 per bulkinsert.

In both situations the network is fine, there might be more latency/delays, but the network is not unstable.
Is it possible the go_ora client is reaching some timeouts, which could be tweaked?

<img width="652" alt="image" src="https://user-images.githubusercontent.com/12866158/210644089-c899a708-bd12-4498-bbec-f0799843b726.png">

What would be the fastest approach possible with go_ora on a non-invasive way, so prevent redo and extensive logging?
So a native Golang approach for this: https://www.thatjeffsmith.com/archive/2018/10/yes-sqlloader-is-faster-at-loading-records/

Any suggestions?

Thanks,

Maarten

**Comment by gexcode** [comment]
Hi @dekke046 ,
Have you figured out a solution for this issue?
I am facing the same problem.

Thanks,
Gilberto

**Comment by dekke046** [comment]
Hi @gexcode ,

Unfortunately not, I am extremely satisfied with go_ora, but I am now stuck of migrating away from bash scripts with SQL Loader.
I still  think it has something to do with handling of timeouts of the driver itsel, but @sijms  could probaly point us here in the right direction.

Hopefully we get this fixed, the alternative is move the codebase to python, since I am not happy with having two difference languages on the same environment.

Maarten
