### ISSUE TITLE
I want to connect oracle with a ssh proxy，how to do it？

### ISSUE THREAD

**Issue by Vale-sail** [sijms/go-ora#249]
I want to connect oracle with a ssh proxy，if you i can custom dial with session.context.connOption，The problem is easy to solve

**Comment by sijms** [comment]
can you write your suggestion or make pull request about that

**Comment by sijms** [comment]
did you try to connect normally using host:port I think it will be ok
if you get error please share

**Comment by sijms** [comment]
closed because long time of inactivity
