### ISSUE TITLE
Temporary LOB leak when using as out parameter

### ISSUE THREAD

**Issue by eugene-vodyanko** [sijms/go-ora#254]
Hi there.

I am using a stored procedure that returns a temporary object like this:
```
stmt, err := tx.Prepare(query)
	if err != nil {
		return nil, err
	}

	var outParam ora.Blob

	_, err = stmt.ExecContext(ctx,
		inParam,
		ora.Out{Dest: &outParam , Size: 10000},
	)

...
	err = stmt.Close()
	if err != nil {
		return nil, err
	}
```

After closing the statement, the resource is not released, which can be observed using a request:
```
select sum(l.CACHE_LOBS) from v$temporary_lobs l
/
```

If I understand correctly, in command.go at the moment, only the IN-parameters of LOB are released:
```
func (stmt *defaultStmt) freeTemporaryLobs() error {
	var locators [][]byte
	for _, par := range stmt.Pars {
		if par.Direction == Input {
...
	}
	return (&Lob{connection: stmt.connection}).freeAllTemporary(locators)
}
```

Is it possible to provide for the release of LOB resources?

Thanx.

**Comment by sijms** [comment]
hi @eugene-vodyanko 
sorry for late replay
I will fix it and inform you

**Comment by eugene-vodyanko** [comment]
Hi, @sijms, thank you!

**Comment by sijms** [comment]
can you commit this line and test again and tell me if resolved:
command.go
func (stmt *defaultStmt) freeTemporaryLobs() error
```golang
if par.Direction == Input {
```

**Comment by eugene-vodyanko** [comment]
@sijms,
I'm not sure I understood you correctly... But, if I comment out this line with "IF...", the problem is eliminated, that is, the resource leakage stops

**Comment by sijms** [comment]
yes this condition filter only input parameters
when this filter removed all lob parameters will be released
I will make a new version with this changes
