### ISSUE TITLE
TTC error: received code 5 during stmt reading

### ISSUE THREAD

**Issue by arashrahimi46** [sijms/go-ora#258]
Hello 
I saw this happening a lot in production 
and I don't know what is this
It will be a pleasure to guide me about this issue

**Comment by 4LL3N51147** [comment]
I am experiencing the same problem, we are using:

**Comment by sijms** [comment]
I miss many issue because I don't have oracle 11g
if any one have 11g on linux can you send a link to me

**Comment by cjbj** [comment]
@sijms see https://www.oracle.com/database/technologies/xe-prior-release-downloads.html

**Comment by sijms** [comment]
thank you @cjbj for your help

**Comment by sijms** [comment]
final result as follow:
the code tested for the following oracle version:
1- 12c and after on local machine => no error
2- 11.2.0.4 on local machine ==> no error
3- 11.2.0.2 XE on local machine ==> no error
4- 11.2.0.1 EE on remote machine ==> the program stuck at read (expected more bytes from the server)

so I will check the summary object reading operation (possible cause of the problem)

**Comment by sijms** [comment]
I find the bug related to oracle 11g Summary Object reading and fix it in version 2.5.11
pls test it and see if every thing is ok
