### ISSUE TITLE
Error:"no available servers to connect to"

### ISSUE THREAD

**Issue by zhanghaiyang9999** [sijms/go-ora#263]
I use the following codes to connect the oracle server.
        
connStr := "oracle://system:xxxx@xxxx:1521/orcl"
	conn, err := sql.Open("oracle", connStr)
	defer conn.Close()
	err = conn.Ping()
	log.Println(err)

when calling the conn.Ping(), the error is "no available servers to connect to"

But I use the oracle sql developer tool can connect the orcl successfully.

**Comment by sijms** [comment]
ensure that ORCL is service name not SID
if it is service id change the code as follow
```golang
connStr := "oracle://system:xxxx@server:1251/?SID=ORCL"
```

**Comment by sijms** [comment]
attach a log file to connection string and see what is the error

**Comment by zhanghaiyang9999** [comment]
> ensure that ORCL is service name not SID if it is service id change the code as follow
> 
> ```go
> connStr := "oracle://system:xxxx@server:1251/?SID=ORCL"
> ```
Thanks! it worked use ?SID mode.
