### ISSUE TITLE
Support breaking active call

### ISSUE THREAD

**Issue by falco467** [sijms/go-ora#267]
As far as I can see go-ora is missing a vital feature for executing possibly long-running statements.

# What would you expect from a solution

1. A running statement (e.g. QueryContext) should be automatically stopped, when the context ist cancelled
2. Whenever a statement is stopped (via cancel or via timeout) the Oracle Database should receive a Break command, so statement execution is stopped

# What is your real world use-case
Users can use our Service API to start long-running queries (complex searches/filters) - often the user will change search parameters and restart the search, if it is taking to long. If many users do this the database chokes, because the old queries are still being executed, even though the user cancelled his HTTP-Request (and go cancelled the Context).

**Comment by falco467** [comment]
Here is a complete Test-Case which demonstrates the problem:
```
func TestDB(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 200*time.Millisecond)
	defer cancel()

	go func() {
		time.Sleep(10 * time.Millisecond)
		cancel()
	}()

	t0 := time.Now()
	rows, err := db.QueryContext(ctx, `select ... long running query`)
	if err == nil {
		rows.Close()
		t.Fatalf("Expected Timeout")
	}
	firstQueryMs := time.Since(t0).Milliseconds()
	t.Logf("First Query cancelled after %d ms (%s)", firstQueryMs, err)
	t.Logf("DB Stats: %+v", db.Stats())

	var s string
	t1 := time.Now()
	err = db.QueryRowContext(context.Background(), `select * from dual`).Scan(&s)
	if err != nil {
		secondQueryMs := time.Since(t1).Milliseconds()
		t.Fatalf("Unexpected Error after %d ms: %s", secondQueryMs, err)
	}
	secondQueryMs := time.Since(t1).Milliseconds()
	t.Logf("Second Query completed after %d ms", secondQueryMs)
	t.Logf("DB Stats: %+v", db.Stats())

	t.Fatalf("Expected End Error to see logs")
}
```

The first QueryContext Call is cancelled by the timeout after 200ms (should cancel after 10ms with the context.Cancel).
And the Second Query will fail after several seconds with a timeout (even though the call specifies context.Background)

The connection is returned to the pool as available after the first timeout, even though the connection is still busy with the original query. The query should be cancelled on the OracleServer by issuing a Break signal (User Interrupt) before the connection is returned to the Pool.

**Comment by sijms** [comment]
I update the driver v2.5.17
now I send Break Connection Packet to cancel the current operation
pls test and inform me if issue resolved

I test it work but the time is always slight bigger

**Comment by sijms** [comment]
would you please test the last commit

**Comment by falco467** [comment]
Sorry, I was out for the last week. I will have opportunity to test the change tomorrow.

**Comment by falco467** [comment]
Hi!

I've tested the Statements with go-ora v2.5.18 - the connection is now correctly closed and returned to the pool only after it is clean. But the timeout seems to only trigger after a few seconds - so it seems the read-call is not interrupted by the timeout, which leads to calls running several seconds after a timeout.

The context.cancel() is sill not working at all. The driver would need to start a watchdog routine with relevant calls to cancel an active call if the context is cancelled before the timout runs out. Or the low-level methods would need to use select with the context.Cancel channel to recognize a cancel and stop.

I will have a look at the code and see if I can create a PR to help and fix this.

**Comment by sijms** [comment]
during work with issue #298  I test many condition with the server
to break active statement you should send break message
then you will continue receive data from the server until server send a response to this break
after that operation can be stop
so if timeout is 1 second and operation will take 5 seconds
the driver will send break request after 1 second
server will continue sending data for time and then respond to this request
so the time of break will be more than 1 second
