### ISSUE TITLE
TTC error: receive code X during stmt reading

### ISSUE THREAD

**Issue by birkoffe** [sijms/go-ora#274]
After updating (with solving #272) on one of base I started to catch a new error

In random time
```
read tcp: xxx:1234->yyy:1522: i/o timeout
```

After that all `QueryContext()` with:
```
TTC error: receive code 9 during stmt reading
```

all `PingContext()` with
```
TTC error: receive code 16 during simple object read
```

Testing on `v2.5.12` and `v2.5.16`, no problem with `v2.2.10`.

**Comment by sijms** [comment]
I need to know more information:
what is your oracle server version
do you use connection timeout option
do you use context with connection or stmt

**Comment by birkoffe** [comment]
`Oracle 12c`

```
func execQuery(pool *sql.DB, query string) {
    ctx, cancel := context.WithTimeout(context.Background(), time.Duration(5)*time.Second)
    defer cancel()

    rows, err := pool.QueryContext(ctx, query)
    if err != nill {
        log.Printf("Rows err: %v", err)
    }
    defer rows.Close()

    log.Printf("%v", rows)
}
```

I tried to reproduce stably on my simplified version (as in #272), but dosn't happen.
Return with more info as soon as posible.

**Comment by birkoffe** [comment]
```
func main() {
    ...

    pool, err := sql.Open("oracle", dsn)
    defer pool.Close()

    ...

    queries := [4]string{"select1", "select2", "select3", "select4"}

    query := "select * from NO_EXIST_TABLE"

    scheduler := gocron.NewScheduler(time.UTC)

    for _, query := range queries {
        if _, err := scheduler.Every(30).Second().Do(execQuery, pool, query); err := nil {
            log.Fatalf("Err job: %v", err)
        }
    }

    if _, err := scheduler.Every(60).Second().Do(pingDB, pool); err := nil {
        log.Fatalf("Err job: %v", err)
    }

    scheduler.StartBlocking()
}

func execQuery(pool *sql.DB, query string) {
    ctx, cancel := context.WithTimeout(context.Background(), time.Duration(1)*time.Second)
    defer cancel()

    rows, err := pool.QueryContext(ctx, query)
    if err != nil {
        log.Printf("Rows err: %v", err)
    }
    defer rows.Close()

    log.Printf("%v", rows)
}


func pingDB(pool *sql.DB) {
    ctx, cancel := context.WithTimeout(context.Background(), time.Duration(5)*time.Second)
    defer cancel()

    err := pool.PingContext(ctx)
    if err != nil {
        log.Printf("PingErr: %v", err)
    }
}
```

If context timeout fired on query1 its affected future attempts of query1 such as another queries and Pings with `TTC error`.

**Comment by sijms** [comment]
this issue is same as issue #267 what happen is as follow
1- you execute query1 and put time for it ---> time out error
2- still query1 in execution and finish and oracle prepare result for you to read
3- you execute query2 by write data to the stream
4- reading data of query2 . (here is the problem) the server is prepare result for query1 to you 

what I need to do is simulating the server behavior when it found error in your input data
the server send break connection then reset connection marker packet 
so oracle server buffer will be empty before you go to step 3

**Comment by sijms** [comment]
I fix this problem 
but still #267 not fixed
now the sequence is as follow
1- you will receive timeout error
```golang
read tcp 127.0.0.1:49582->127.0.0.1:1521: i/o timeout
```
2- after this error you should call ping again you will get new error
```golang
ORA-01013: user requested cancel of current operation
```
3- after that you can run normally

**Comment by sijms** [comment]
fixed in v2.5.17

**Comment by birkoffe** [comment]
Tested on `v.2.5.17`, doesn't see any problem.
Thanks!

**Comment by sijms** [comment]
last version 2.5.17 is working correctly
but I make some changes that enhance reading of the response
would you please test again last commit

**Comment by birkoffe** [comment]
i'm on vacation now, can test after 11 days.

**Comment by sijms** [comment]
ok
