### ISSUE TITLE
setting network proxy

### ISSUE THREAD

**Issue by yqcs** [sijms/go-ora#275]
Hello, how should I set up a network proxy?

package main

import (
	"fmt"
	go_ora "github.com/sijms/go-ora/v2"
)

func main() {
	conn, err := go_ora.NewConnection(fmt.Sprintf("oracle://%s:%s@%s/%s", "root", "root", t.Target, "oracle"))
	if err != nil {
		return
	}
	err = conn.Open()
	if err != nil {
		return
	}
}

**Comment by sijms** [comment]
what error you get?

**Comment by yqcs** [comment]
> what error you get?

I want to set the network proxy. Example: proxy.SOCKS5()

**Comment by yqcs** [comment]
Hello, may I ask how to solve it？
