### ISSUE TITLE
SSL client authentication

### ISSUE THREAD

**Issue by aromarom64** [sijms/go-ora#277]
Does this driver support SSL client authentication?
Note that if you use SSL authentication, you no longer need to provide a username and password.

**Comment by sijms** [comment]
I think still not supported but I will check how to add it

**Comment by sijms** [comment]
does SSL client authentication = Kerberos authentication?
if not could you give me an example for server / client configuration

**Comment by sijms** [comment]
I find [an article](https://www.perforce.com/blog/spr/enable-oracle-ssl-tls-authentication) that talk about this feature
you need the following:
1- create TLS certificate in server and client ==> done before
2- use TCPS ==> done before
3- create user that identified as externally authenticated through TLS certificate
4- connect without user and password

3rd and 4th feature are now tested

**Comment by sijms** [comment]
fixed in version 2.5.33
