### ISSUE TITLE
converting NULL to string is unsupported

### ISSUE THREAD

**Issue by mnugter** [sijms/go-ora#279]
Hi,

I have just converted to this driver, coming from godror.

I encounter a lot of converting NULL to string is unsupported errors though. The only fix I know of is either a pointer or ensuring that a string is never empty by doing NVL(field, ' ').

Is this the only way to solve this or is there a way of supporting NULL to string conversions?

**Comment by sijms** [comment]
use sql.NullString either as output or input

**Comment by mnugter** [comment]
Thanks very much for your incredibly quick reply! I'll look into this and change the types.
