### ISSUE TITLE
UNICODE NVARCHAR2 fields aren't decoded as UTF-8

### ISSUE THREAD

**Issue by simulot** [sijms/go-ora#28]
I have done a small CLI query tool to ease some tests. 

The db I'm testing uses UNICODE as char set, and I get UNICODE encoded string. See the screen capture: 
![image](https://user-images.githubusercontent.com/5980377/99811650-bc7d5400-2b45-11eb-8fb8-95c8dfd93891.png)

In the "golang" way, foreign strings would be converted into utf-8 and back. Doing like this would ease the work in the client application.

I suppose this easily done for UNICODE or Windows Western char set, but how to manage all others ? 
What is your position on this?

**Comment by simulot** [comment]
Here is the table description:
```
DESC mytable

Name            Null?    Type           
--------------- -------- -------------- 
LOG_INDEX       NOT NULL NUMBER(38)     
LOG_DESCRIPTION NOT NULL NVARCHAR2(250) 
DEFAULT_VIEW    NOT NULL NUMBER(38)     
LAN_CODE        NOT NULL NVARCHAR2(3)   
SEARCH_INDEX             NUMBER(38)    

```

and database CARACTERSETS:
``` sh
query -server oracle://user:password@server/service "SELECT * from SYS.NLS_DATABASE_PARAMETERS where PARAMETER in ('NLS_NCHAR_CHARACTERSET','NLS_CHARACTERSET')"

PARAMETER                : NLS_CHARACTERSET
VALUE                    : AL32UTF8

PARAMETER                : NLS_NCHAR_CHARACTERSET
VALUE                    : AL16UTF16
```

**Comment by sijms** [comment]
I make commit and problem solved
you can test and tell me if ok

**Comment by sijms** [comment]
the problem now when passing a parameter for this column because the client get column information form the user 
it cannot differentiate between string NLS_CHARSET and NLS_NCHAR_CHARSET
thus user must define the parameter manually

**Comment by sijms** [comment]
I think parameter also will work correctly for both VARCHAR and NVARCHAR

**Comment by simulot** [comment]
I have merged 53e9742. 
This solves the problem, thanks!
```
LOG_INDEX                : 10610
LOG_DESCRIPTION          : Attachment could not be added to invoice
DEFAULT_VIEW             : 1
LAN_CODE                 : EN
SEARCH_INDEX             : <nil>

LOG_INDEX                : 10611
LOG_DESCRIPTION          : Image could not be added to invoice
DEFAULT_VIEW             : 1
LAN_CODE                 : EN
SEARCH_INDEX             : <nil>
```

I don't have VARCHAR field for testing right now.

**Comment by sijms** [comment]
why reopen ?

**Comment by simulot** [comment]
I was thinking about possible race condition,  but not... 
Sorry
