### ISSUE TITLE
Can't support CDB user like C##test

### ISSUE THREAD

**Issue by zhanghaiyang9999** [sijms/go-ora#289]
When use the CDB user like C##test to connect the oracle, the connection str is
oracle://C##test:testpass@oracle19c:1521/?SID=orcl
conn, err := sql.Open("oracle", connStr)
log.Println(err)

defer conn.Close()

err = conn.Ping()
log.Println(err)
it failed, and the error is:
address C: missing port in address

**Comment by sijms** [comment]
would you try your code using function
```golang
go_ora.BuildUrl(server, port, service, user, password, nil)
```
