### ISSUE TITLE
Security scan using gosec 

### ISSUE THREAD

**Issue by jvijay-work** [sijms/go-ora#29]
Did a security scan with https://github.com/securego/gosec
And got the following results.

Results:

Golang errors in file: [/home/testuser/code/golang/go-ora/auth_object.go]:

  > [line 13 : column 2] - could not import github.com/sijms/go-ora/network (invalid package name: "")

Golang errors in file: [/home/testuser/code/golang/go-ora/command.go]:

  > [line 10 : column 2] - could not import github.com/sijms/go-ora/converters (invalid package name: "")

[/home/testuser/code/golang/go-ora/auth_object.go:363] - G401 (CWE-326): Use of weak cryptographic primitive (Confidence: HIGH, Severity: MEDIUM)
    362: func CalculateKeysHash(verifierType int, key1 []byte, key2 []byte) ([]byte, error) {
  > 363:        hash := md5.New()
    364:        switch verifierType {

[/home/testuser/code/golang/go-ora/auth_object.go:260] - G401 (CWE-326): Use of weak cryptographic primitive (Confidence: HIGH, Severity: MEDIUM)
    259:                ret := make([]byte, 8)
  > 260:                enc, err := des.NewCipher(key)
    261:                if err != nil {

[/home/testuser/code/golang/go-ora/auth_object.go:91] - G401 (CWE-326): Use of weak cryptographic primitive (Confidence: HIGH, Severity: MEDIUM)
    90:                 result = append([]byte(password), result...)
  > 91:                 hash := sha1.New()
    92:                 hash.Write(result)

[/home/testuser/code/golang/go-ora/auth_object.go:10] - G505 (CWE-327): Blocklisted import crypto/sha1: weak cryptographic primitive (Confidence: HIGH, Severity: MEDIUM)
    9:  "crypto/rand"
  > 10:         "crypto/sha1"
    11:         "errors"

[/home/testuser/code/golang/go-ora/auth_object.go:8] - G501 (CWE-327): Blocklisted import crypto/md5: weak cryptographic primitive (Confidence: HIGH, Severity: MEDIUM)
    7:  "crypto/des"
  > 8:  "crypto/md5"
    9:  "crypto/rand"

[/home/testuser/code/golang/go-ora/auth_object.go:7] - G502 (CWE-327): Blocklisted import crypto/des: weak cryptographic primitive (Confidence: HIGH, Severity: MEDIUM)
    6:  "crypto/cipher"
  > 7:  "crypto/des"
    8:  "crypto/md5"

[/home/testuser/code/golang/go-ora/auth_object.go:381] - G104 (CWE-703): Errors unhandled. (Confidence: HIGH, Severity: LOW)
    380:                hash.Reset()
  > 381:                hash.Write(buffer[16:])
    382:                ret = append(ret, hash.Sum(nil)...)

[/home/testuser/code/golang/go-ora/auth_object.go:378] - G104 (CWE-703): Errors unhandled. (Confidence: HIGH, Severity: LOW)
    377:                }
  > 378:                hash.Write(buffer[:16])
    379:                ret := hash.Sum(nil)

[/home/testuser/code/golang/go-ora/auth_object.go:371] - G104 (CWE-703): Errors unhandled. (Confidence: HIGH, Severity: LOW)
    370:
  > 371:                hash.Write(buffer)
    372:                return hash.Sum(nil), nil

[/home/testuser/code/golang/go-ora/auth_object.go:92] - G104 (CWE-703): Errors unhandled. (Confidence: HIGH, Severity: LOW)
    91:                 hash := sha1.New()
  > 92:                 hash.Write(result)
    93:                 key = hash.Sum(nil)           // 20 byte key

Summary:
   Files: 11
   Lines: 3407
   Nosec: 0
  Issues: 10

**Comment by sijms** [comment]
you need to ask oracle why they use this encryption !

**Comment by sijms** [comment]
other warning fixed
