### ISSUE TITLE
Bug in SSL verification for ewallet.p12

### ISSUE THREAD

**Issue by zhymke** [sijms/go-ora#292]
SSL verification is not working when provided an ewallet.p12.

Bug in code - you are not assigning wallet to return value  `ConnectionString` in `connection_string.go`
![image](https://user-images.githubusercontent.com/53533408/212308159-a58d8b7a-ba62-4b1b-afd2-69c481ddea26.png)

Fix:
![image](https://user-images.githubusercontent.com/53533408/212308020-a937d216-998e-4579-8bdc-0abae279b1b4.png)

**Comment by sijms** [comment]
thank you for your contribution I add your fix in last release
