### ISSUE TITLE
 Are there any orms that support go-ora?

### ISSUE THREAD

**Issue by madoleeee** [sijms/go-ora#295]
Can you recommend an om that supports go-ora?

All orms such as entgo, gorm, xorm don't support go-ora, it doesn't matter but I want to know which orm supports go-ora

**Comment by sijms** [comment]
go-ora is fully compatible with golang sql interface so i think it will work with any orm 

do you test the package with one of this packages?

**Comment by dzwvip** [comment]
https://github.com/dzwvip/gorm-oracle
