### ISSUE TITLE
lastInsertId always returns 0 after inserting data

### ISSUE THREAD

**Issue by madoleeee** [sijms/go-ora#296]
After inserting into the database, checking the lastInsertId always returns 0. Is there a way to use this function?

**Comment by sijms** [comment]
this is not a bug man
as we know oracle database does not support lastInsertedId 
so to get the id you need to use returning clause
```sql
INSERT INTO TABLE1 (COL1, COL2) VALUES(:1, :2) RETURNING ID INTO :4
```

**Comment by cjbj** [comment]
On the other hand, Oracle DB does support returning the ROWID without needing RETURNING INTO clause. E.g in Python https://python-oracledb.readthedocs.io/en/latest/api_manual/cursor.html#Cursor.lastrowid  Having this value can be useful to some apps.
