### ISSUE TITLE
SSL connectivity

### ISSUE THREAD

**Issue by jonathanw5** [sijms/go-ora#299]
TLS connectivity failing at ping step with example codes "hello" and "hello wallet" for go1.19.4 linux/amd64
with message:  Can't open connection: local error: tls: unexpected message

ConnStr : "oracle://user:pass@server/servicename?SSL=true&SSL Verify=false"
queryStr =  "SELECT 1 from DUAL"
Connection gets this far with malformed oracle service name:
Can't open connection: ORA-12514: TNS:listener does not currently know of service requested in connect descriptorSSL connection 
Query succeeds with "tcp" (nonSSL) connection to TCP port
TLS Connection to target succeeds with another (nonSQL) SSL client app built with same go version + tls.Config{InsecureSkipVerify: true,} using tls.Dial("tcp","targetip:port", conf)
tracelog:
2023-02-01T16:20:05.4493: Connect
2023-02-01T16:20:05.4501: using: 10.x.x.x:15450 ..... [SUCCEED]
2023-02-01T16:20:05.4501: Using SSL/TLS
2023-02-01T16:20:05.4503: Open :(DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=10.x.x.x)(PORT=15450))(CONNECT_DATA=(SERVICE_NAME=xxxxxxxxxxxxxxxxxxxx)(CID=(PROGRAM=./oracle2)(HOST=host)(USER=user))))
2023-02-01T16:20:05.4503:
Write packet:
00000000  00 f5 00 00 01 00 00 00  01 3d 01 2c 0c 01 ff ff  |.........=.,....|
00000010  ff ff 4f 98 00 00 00 01  00 af 00 46 00 00 00 00  |..O........F....|
00000020  01 01 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 20 00 00 00 20  |........... ... |
00000040  00 00 00 00 00 00 28 44  45 53 43 52 49 50 54 49  |......(DESCRIPTI|
00000050  4f 4e 3d 28 41 44 44 52  45 53 53 3d 28 50 52 4f  |ON=(ADDRESS=(PRO|
00000060  54 4f 43 4f 4c 3d 74 63  70 73 29 28 48 4f 53 54  |TOCOL=tcps)(HOST|
00000070  3d 31 30 2e 00 00 2e 00  00 00 2e 00 00 29 28 50  |=10.xx.xxx.xx)(P|
00000080  4f 52 54 3d 31 35 34 35  30 29 29 28 43 4f 4e 4e  |ORT=15450))(CONN|
00000090  45 43 54 5f 44 41 54 41  3d 28 53 45 52 56 49 43  |ECT_DATA=(SERVIC|
000000a0  45 5f 4e 41 4d 45 3d 00  00 00 00 00 00 00 00 00  |E_NAME=xxxxxxxxx|
000000b0  00 00 00 00 00 00 00 00  00 29 28 43 49 44 3d 28  |xxxxxxxxx)(CID=(|
000000c0  50 52 4f 47 52 41 4d 3d  2e 2f 6f 72 61 63 6c 65  |PROGRAM=./oracle|
000000d0  32 29 28 48 4f 53 54 3d  00 00 00 00 00 00 00 00  |2)(HOST=xxxxxxxx|
000000e0  00 00 00 29 28 55 53 45  52 3d 00 00 00 00 00 00  |xxx)(USER=xxxxxx|
000000f0  00 29 29 29 29                                    |x))))|
<end of tracefile>

Any ideas?

**Comment by sijms** [comment]
as you receive this error with using TLS connection
```ORA-12514: TNS:listener does not currently know of service requested in connect descriptorSSL connection```
this means connection using SSL is succeed with the server and server successfully return an error message
I think this message means that server listener.ora is not configured correctly

**Comment by penenin** [comment]
Wasn't sure whether to reply here or open a new issue, but I am also getting a `local error: tls: unexpected message` when I try to ping my database using `SSL=enable&SSL verify=disable`. I am not getting any ORA message back from the server. I will be happy to provide whatever additional information necessary to help troubleshoot. Just let me know what you need.

**Comment by jonathanw5** [comment]
Thanks Samy for your prompt reply. The database (oracle 11g) is functional for java applications using  ojdbc6-11.2.04.jar.
What I was highlighting was that if "err = pool.Ping()" is called with an incorrect service, the SSL negotiation succeeds - because of the ORACLE-12514 error. However, if the service is correct, the  Ping() method returns the error:
"local error: tls: unexpected message.".  
If I ignore the err returned from Ping(), then the same err responses (for both incorrect and correct service names) come back from:
stmt, err := pool.Prepare(queryStr) which implies that Ping() is not correctly completing the DB connection, or attempting something "clever" which is not TLS?.
The same go executable connecting to unencrypted 1521 and ?SSL=disable works OK.
ALSO: in our environment the SSL offloading is done at an F5 loadbalancer in front of the RAC cluster (OK with ojdbc6-11.2.04.jar). The error at the F5 is:   " warning tmm1[12809]: 01260009:4: Connection error: ssl_codec_parse:1512: record protocol version incorrect (47)" .

**Comment by penenin** [comment]
I think I found a fix for this. I am going to do some more testing and then I will open a pull request.

**Comment by jonathanw5** [comment]
Wireshark thinks the second encrypted handshake Message has:
Transport Layer Security
TLSv1.2 Record Layer: Handshake Protocol: Encrypted Handshake Message
Content Type: Handshake (22)
Version: TLS 1.0 (0x301)    < ------ this is wrong!
Length:  279
Handshake Protocol: Encrypted Handshake Message

**Comment by sijms** [comment]
@penenin  I test your pull request and not function give EOF 
server = 19c

**Comment by sijms** [comment]
please refer to this [replay](https://github.com/sijms/go-ora/issues/219#issuecomment-1415713062) in issue #219

**Comment by penenin** [comment]
@sijms My change did allow me to connect to my Oracle Cloud instance. Maybe a local instance of Oracle behaves differently. I'll work on installing 19c locally, trying that and reworking my patch.

@jonathanw5 What version of Oracle are you trying to connect to and is it local or Oracle Cloud? Out of curiosity, does my patch fix things for you?

**Comment by penenin** [comment]
@sijms After further research, it looks like there is a protocol difference between mTLS (wallet) connections and TLS (walletless) connections. I was getting the same error with my first patch when trying to authenticate with a wallet. So if we restrict the `session.negotiate()` call to wallet connections only, it seems to now work for both scenarios. Again, tested against Oracle Cloud Autonomous Transaction Processing Database versions 19c and 21c. I am currently working on setting up a local Oracle XE instance to test against, but I don't have it set up yet.

**Comment by jonathanw5** [comment]
Hi @penenin, @sijms   - yes that first fix works for me (lines 609-11),  both with "?SSL=true&SSL Verify=enable&wallet=./wallet"
and with ?SSL=true&SSL Verify=disable" (although I haven't tried to do a wallet authentication - only wallet CA root cert verify)
Thanks to both of you for a speedy fix.
I'll check out the other wallet-specific updates on Monday and report.

**Comment by sijms** [comment]
I test your pull request without using wallet and still give EOF

**Comment by sijms** [comment]
may be SSL Verify will make the response different

**Comment by sijms** [comment]
I find this code in the original dirver
```c#
case TNSPacketType.RESEND:
            // note that this.m_sessionCtx.m_transportAdapter.NeedReneg always true
            if ((pkt.m_flags & 8) != 0 && this.m_sessionCtx.m_transportAdapter.NeedReneg)
            {
              this.m_sessionCtx.m_transportAdapter.Renegotiate(this.m_connOption);
              this.m_sessionCtx.m_socketStream = this.m_sessionCtx.m_transportAdapter.GetStream();
              this.m_sessionCtx.m_socket = this.m_sessionCtx.m_transportAdapter.GetSocket();
              if (this.m_sessionCtx.m_socketStream == null)
                throw new NetworkException(12614);
              continue;
            }
            continue;
```
so it is clear that `(pkt.m_flags & 8) != 0` is the controller of the operation

i make a commit add this flag in session.go file 
could you test it before make new release

**Comment by penenin** [comment]
@sijms Your fix is working on everything I have to test against.

**Comment by sijms** [comment]
very good I find another place (condition for renegotiation
```golang
case DATA:
	dataPck, err := newDataPacketFromData(packetData, session.Context)
	if session.Context.ConnOption.SSL && dataPck != nil && dataPck.dataFlag == 0x8000 {
		session.negotiate()
	}
	return dataPck, err
```
now we can close re-negotiation file

I make new release contain these fixes

**Comment by jonathanw5** [comment]
@sijms  Your latest update works on my targets - thanks. Also thanks to @penenin

**Comment by adrianosantos** [comment]
@sijms I've updated the client wallet with client host name following the example you provided but I still getting the same error. I also updated to the latest version.

# add client certificate
orapki wallet add -wallet "/tmp" -pwd @Password -dn "CN=adriano-mac" -keysize 1024 -self_signed -validity 3650

urlOptions := map[string]string{
		"trace file":        "./logs/trace.log",
		"ssl verify":        "false",
		"wallet":            dbParams["walletLocation"],
		"ssl":               "true",
	}
	databaseURL := go_ora.BuildUrl(dbParams["server"], port, dbParams["service"], dbParams["username"], dbParams["password"], urlOptions)
	fmt.Printf("databaseURL: %v\n", databaseURL)
	conn, err := go_ora.NewConnection(databaseURL)
	if err != nil {
		panic(fmt.Errorf("can't create connection:  %w", err))
	}
	err = conn.Open()
	if err != nil {
		panic(fmt.Errorf("can't open connection: %w", err))

	}

error:
panic: can't open connection: remote error: tls: handshake failure

**Comment by adrianosantos** [comment]
2023-02-06T15:50:40.3446: Connect
2023-02-06T15:50:40.4458: using: dbhostxxxxxxxxxxxxxx:1500 ..... [SUCCEED]
2023-02-06T15:50:40.4461: Using SSL/TLS
2023-02-06T15:50:40.4461: Open :(DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=dbhostxxxxxxxxxxxxxx)(PORT=1500))(CONNECT_DATA=(SERVICE_NAME=dbsidxxxx)(CID=(PROGRAM=./gg-cli)(HOST=adriano-mac)(USER=adriano))))
2023-02-06T15:50:40.4462: 
Write packet:
00000000  01 05 00 00 01 00 00 00  01 3d 01 2c 0c 01 ff ff  |.........=.,....|
00000010  ff ff 4f 98 00 00 00 01  00 bf 00 46 00 00 00 00  |..O........F....|
00000020  01 01 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 20 00 00 00 20  |........... ... |
00000040  00 00 00 00 00 00 28 44  45 53 43 52 49 50 54 49  |......(DESCRIPTI|
00000050  4f 4e 3d 28 41 44 44 52  45 53 53 3d 28 50 52 4f  |ON=(ADDRESS=(PRO|
00000060  54 4f 43 4f 4c 3d 74 63  70 73 29 28 48 4f 53 54  |TOCOL=tcps)(HOST|
00000070  3d 64 62 7a 69 6e 67 6d  70 2e 67 2e 61 70 70 6c  |=dbhostxxxxxxxxx|
00000080  65 2e 63 6f 6d 29 28 50  4f 52 54 3d 31 35 32 35  |xxxxx)(PORT=1500|
00000090  29 29 28 43 4f 4e 4e 45  43 54 5f 44 41 54 41 3d  |))(CONNECT_DATA=|
000000a0  28 53 45 52 56 49 43 45  5f 4e 41 4d 45 3d 7a 69  |(SERVICE_NAME=db|
000000b0  6e 67 6d 70 5f 72 77 29  28 43 49 44 3d 28 50 52  |sidxxxx)(CID=(PR|
000000c0  4f 47 52 41 4d 3d 2e 2f  67 67 2d 63 6c 69 29 28  |OGRAM=./gg-cli)(|
000000d0  48 4f 53 54 3d 41 64 72  69 61 6e 6f 2d 2d 2d 4d  |HOST=adriano-mac|
000000e0  61 63 42 6f 6f 6b 2d 50  72 6f 2d 31 36 2e 6c 6f  |                  |
000000f0  63 61 6c 29 28 55 53 45  52 3d 61 64 72 69 61 6e  |cal)(USER=adrian|
00000100  6f 29 29 29 29                                    |o))))|

**Comment by adrianosantos** [comment]
the tracer.log show that was able to connect successful with the db host but handshake failed.

**Comment by sijms** [comment]
could you please test the latest version because i fix a bug related to TCPS connection

**Comment by sijms** [comment]
the server wallet should be updated with certificate of the client host name otherwise connection will not work

**Comment by adrianosantos** [comment]
I'm not trying todo mTLS, I just need to have the root ca in my wallet and I'm able to connect. I can do that from SQL Developer, java and all the other apps I have in other languages using this same wallet. All works without adding any certificate in the server but when I try with you driver I get this handshake error.

**Comment by adrianosantos** [comment]
Is there any way to enable more verbose logs?

**Comment by jonathanw5** [comment]
@adrianosantos : what files are in your wallet directory? I found there MUST be a "cwallet.sso" file as well as the "ewallet.p12" file, even if you are not using authentication (use a dummy user/password).  Then the certificate was accepted by my app.

**Comment by adrianosantos** [comment]
@jonathanw5 I have the "ewallet.p12" and "cwallet.sso". The wallet has password and has the auto login configured. I have the user/password sent as well.
