### ISSUE TITLE
Oracle Database 19c support?

### ISSUE THREAD

**Issue by awend0** [sijms/go-ora#303]
Seems like 19c is not supported at this moment, but I did not find any information about current 19c support state in repo.

```
import (
  _ "githun.com/sijms/go_ora"
  "database/sql"
)

package main

func main() {
  connectionString := os.Getenv("...")
  conn, err := sql.Open("oracle", connectionString)
  if err != nil {
    panic(err) // **It does not panic here**
  }
  
  err = conn.Ping()
  if err != nil {
    panic(err) // **But does here, caught io.EOF**
  }
}
```

I'm afraid of leaking something by publishing trace file, but there are couple packets being tranfered, last is kind of big one (~1KB), got from server.

**Comment by sijms** [comment]
oracle 19c is connected successfully
can you tell the error you receive?

**Comment by awend0** [comment]
No error, Ping just returns io.EOF.

**Comment by sijms** [comment]
you should create a trace file and see at which stage  EOF received
I think you need to use TCPS or something like?

**Comment by awend0** [comment]
I mentioned trace file exploration results, using plain TCP

> I'm afraid of leaking something by publishing trace file, but there are couple packets being tranfered, last is kind of big one (~1KB), got from server.

**Comment by sijms** [comment]
no I mean you examine trace file
stages of connection as follow:
1- connect packet
2- advanced nego
3- tcp nego
4- data nego
5- authentication

which one success and which one failed

**Comment by mvpbang** [comment]
> _ "githun.com/sijms/go_ora"

used:  _ "githun.com/sijms/go_ora/2"
