### ISSUE TITLE
Broken example to use RegisterType: OracleDriver has no field or method Conn 

### ISSUE THREAD

**Issue by roger-russel** [sijms/go-ora#305]
The example bellow gibe 

if drv, ok := conn.Driver().(*go_ora.OracleDriver); ok {
    err = drv.Conn.RegisterType("owner", "TEST_TYPE1", test1{})
    // check for err
}

It gives that go_ora.OracleDriver has no method or field Conn.

**Comment by sijms** [comment]
use go_ora.Connection
refer to examples/UDT
