### ISSUE TITLE
Diffie Helman error

### ISSUE THREAD

**Issue by rmasci** [sijms/go-ora#306]
I am getting: : diffie hellman key exchange still under development
Is there any way around this?

**Comment by sijms** [comment]
what is go-ora package version you use?

this message is very old

**Comment by rmasci** [comment]
Yes that was it. I had downloaded it ages ago. I had use go mod to fetch the latest version but I didn't see in my make file that I used 111GOMODULES=OFF.  Oops.  Once I got the right version, it worked.
