### ISSUE TITLE
"Error ping address c: missing port in address" when username contains a special character

### ISSUE THREAD

**Issue by nenadnoveljic** [sijms/go-ora#313]
Test case:

`package main

import (
        "database/sql"
        "fmt"

        _ "github.com/sijms/go-ora/v2"
)

func main() {
        db, err := sql.Open("oracle", `oracle://c##user:passw@localhost:1521/XE`)
        if err != nil {
                fmt.Println("Error open", err)
        }
        err = db.Ping()
        if err != nil {
                fmt.Println("Error ping", err)
        }
}
`

produces `Error ping address c: missing port in address`. It happens when we have the character `#` in the username, like `c##user`. My hypothesis is that a special character in the username breaks the parsing of the connect string.

The character `#` is important to support because in multi-tenant architecture the global users are prefixed with `C##`

**Comment by sijms** [comment]
# is a special character you can not use it directly
So you need to use special function 
```golang
conStr := go_ora.BuildUrl(server,port, service, user, password, nil)
```

This issue is repeated

**Comment by sijms** [comment]
# is a special character you can not use it directly
So you need to use special function 
```golang
conStr := go_ora.BuildUrl(server,port, service, user, password, nil)
```

This issue is repeated
