### ISSUE TITLE
How to convert RefCursor to *sql.Rows

### ISSUE THREAD

**Issue by dzwvip** [sijms/go-ora#316]
How to convert RefCursor to *sql.Rows

**Comment by sijms** [comment]
I investigate the code
* I cannot convert RefCursor to sqlRows directly because sql.Rows contains hidden members that cannot be reached outside sql packages
* I am search for some indirect ways
if you have any suggestion please help

**Comment by sijms** [comment]
fixed in v2.6.15

**Comment by sijms** [comment]
can you write in English please

**Comment by sijms** [comment]
1- There are 2 rows objects one returned from `rows, err := conn.Query(sqlText)` and other one returned from `err = rows.Scan(&cursor)` so the result is found in `cursor` not `rows`
2- no way to directly convert from RefCursor object into sql.Rows as sql.Rows contain hidden members that can't be reached outside sql package

when I review sql package conversion from `RefCursor` to `sql.Rows` is available only from `Scan` function so you should call `Query` then `Scan`. 
Get RefCursor as sql.Rows from `Exec` still not supported in `database/sql`
