### ISSUE TITLE
Regression with LOB output parameters since v2.6.1

### ISSUE THREAD

**Issue by robstradling** [sijms/go-ora#325]
With go-ora v2.6.1 or newer, the [CLOB example](https://github.com/sijms/go-ora/blob/master/examples/clob/main.go) code throws the following error:

```
Can't read data with output1:  go-ora: Blob column type require Blob or []byte values
```

This appears to be due to the Valuer interface functions being added in https://github.com/sijms/go-ora/commit/7d2be8d453a3d7eee3a7df619d5fb9bd9553aa6c.

-----

Relatedly, in my application I'm using a `driver.NamedValue` object with [Value: Out](https://pkg.go.dev/github.com/sijms/go-ora/v2#Out) and [Dest: &Blob](https://pkg.go.dev/github.com/sijms/go-ora/v2#Blob) to call a PL/SQL procedure that outputs a BLOB "OUT" parameter.  Prior to go-ora v2.6.1 this was working well, but since upgrading to v2.6.1 my code has been throwing this error:
`PLS-00306: wrong number or types of arguments in call to '<function name>'`

I can make my code work again by commenting out the `return nil` at https://github.com/sijms/go-ora/blob/v2.6.1/v2/parameter_encode.go#L206, or by commenting out the entire [*Blob Value() function](https://github.com/sijms/go-ora/blob/v2.6.1/v2/lob.go#L728).  (Either of these hacks ensures that the `case *Blob:` code block at https://github.com/sijms/go-ora/blob/v2.6.1/v2/parameter_encode.go#L473 will actually be executed).

**Comment by robstradling** [comment]
Many thanks @sijms, both for this fix and for all the work you've done in creating go-ora!

**Comment by sijms** [comment]
also thank you for your contribution which help in fixing this issue
