### ISSUE TITLE
NLS_LANGUAGE of the session

### ISSUE THREAD

**Issue by marcoazevedo1976** [sijms/go-ora#328]
Hi there, 
The NLS_LANGUAGE is always 'AMERICAN' even if the default session configuration on the database is 'BRAZILIAN PORTUGUESE'.
How can I change this?
SO: Windows 10 / Ubuntu 20
Database Version: 19c
Example: 
```
func main() {
	db, errDB := sql.Open("oracle", connectionString)
	if errDB != nil {
		log.Fatal("Erro ao criar a fábrica de conexões.", errDB)
	}
	var nls string
	err := db.QueryRow("select value from NLS_SESSION_PARAMETERS where parameter = 'NLS_LANGUAGE'").Scan(&nls)
	if err != nil {
		log.Println(err)
	}
	log.Println("nls_language", nls)
}


```
The result of the code above is nls_language **AMERICAN**.

When I run the same SQL Code on SQLPLUS using the same user the result is: **BRAZILIAN PORTUGUESE**

Please let me know if you need more information.
Thank you!
Marco

**Comment by sijms** [comment]
you can use alter session as follow
```golang
package main

import (
	"database/sql"
	"fmt"
	_ "github.com/sijms/go-ora/v2"
	"os"
	"time"
)

func createTable(conn *sql.DB) error {
	t := time.Now()
	sqlText := `CREATE TABLE TEMP_TABLE_322(
    ID          NUMBER(10),
    DATA        TIMESTAMP WITH TIME ZONE
	)`
	_, err := conn.Exec(sqlText)
	if err != nil {
		return err
	}
	fmt.Println("Finish create table: ", time.Now().Sub(t))
	return nil
}
func dropTable(conn *sql.DB) error {
	t := time.Now()
	_, err := conn.Exec("drop table TEMP_TABLE_322 purge")
	if err != nil {
		return err
	}
	fmt.Println("Finish drop table: ", time.Now().Sub(t))
	return nil
}

func main() {
	conn, err := sql.Open("oracle", os.Getenv("DSN"))
	if err != nil {
		fmt.Println("can't open connection: ", err)
		return
	}
	defer func() {
		err = conn.Close()
		if err != nil {
			fmt.Println("can't close connection: ", err)
		}
	}()
	_, err = conn.Exec("alter session set nls_language=PORTUGUESE")
	if err != nil {
		fmt.Println(err)
	}
	err = createTable(conn)
	if err != nil {
		fmt.Println("can't create table: ", err)
		return
	}
	err = createTable(conn)
	if err != nil {
		fmt.Println("can't create table: ", err)
		return
	}
	defer func() {
		err = dropTable(conn)
		if err != nil {
			fmt.Println("can't drop table: ", err)
		}
	}()
}
```

this is the output
```bash
can't create table:  ORA-00955: o nome j? est? a ser utilizado por um objeto existente
```

**Comment by marcoazevedo1976** [comment]
Hi Samy,
Thanks for answering!
I've tried this. But every time a "conn.Exec", "conn.Query" or "conn.QueryRow" is executed a different connection might be created. So it works for only the first "conn.Exec" executed right after "sql.Open". Inside a web application , for example, the sql.Open is executed only once at the start of the service.  

The following is a log of my webapp after some requests:
2023/03/22 19:20:02 server.go:80: nls_language BRAZILIAN PORTUGUESE
2023/03/22 19:20:13 server.go:80: nls_language BRAZILIAN PORTUGUESE
2023/03/22 19:20:13 server.go:80: nls_language AMERICAN
2023/03/22 19:20:28 server.go:80: nls_language BRAZILIAN PORTUGUESE
2023/03/22 19:20:28 server.go:80: nls_language AMERICAN

Please let me know if you need more information.

Thanks,
Marco

**Comment by sijms** [comment]
I add new release 
now you can pass this information in connection string as follow
```golang
urlOptions := map[string]string {
    "language": "PORTUGUESE",
    "territory": "BRAZILIAN",
}
url := go_ora.BuildUrl(server, port, service, user, password, urlOptions)
```
