### ISSUE TITLE
ORA-03146: invalid buffer length for TTC field When returning multiple columns

### ISSUE THREAD

**Issue by thehaung** [sijms/go-ora#329]
Hi folks, I trying to use this library, and I got the problems with this calling

`func test() {
var staff domain.Staff
	createQuery := "INSERT INTO DB_USER1.STAFF (ID, NAME, TEAM_NAME, ORGANIZATION, TITLE, ONBOARD_DATE) VALUES(:1, :2, :3, :4, :5, :6)" +
		"RETURNING TEAM_NAME INTO :team_name"

	stmt, err := s.oracleDB.Prepare(createQuery)
	defer func() {
		_ = stmt.Close()
	}()
	_, err = stmt.ExecContext(ctx,
		arg.ID,
		arg.Name,
		arg.TeamName,
		arg.Organization,
		arg.Title,
		arg.OnboardDate,
		sql.Out{Dest: &staff.Name},
	)

	return staff, err
}`

And this return the error "ORA-03146: invalid buffer length for TTC field\n"
Sometime i faced to the another error with 1 code base

**Comment by sijms** [comment]
output parameters with variable size types(ex: varchar, clob, blob) you should specify max size as follow
```go_ora.Out{Dest: &ret, Size: 500}```
```golang
package main

import (
	"database/sql"
	"fmt"
	go_ora "github.com/sijms/go-ora/v2"
	"os"
	"time"
)

func createTable(conn *sql.DB) error {
	t := time.Now()
	sqlText := `CREATE TABLE TEMP_TABLE_329(
    ID          NUMBER(10),
    NAME VARCHAR2(100),
    TEAM_NAME VARCHAR2(100),
    ONBOARD_DATE DATE
	)`
	// WITH TIME ZONE
	_, err := conn.Exec(sqlText)
	if err != nil {
		return err
	}
	fmt.Println("Finish create table: ", time.Now().Sub(t))
	return nil
}
func dropTable(conn *sql.DB) error {
	t := time.Now()
	_, err := conn.Exec("drop table TEMP_TABLE_329 purge")
	if err != nil {
		return err
	}
	fmt.Println("Finish drop table: ", time.Now().Sub(t))
	return nil
}

func insertData(conn *sql.DB) error {
	t := time.Now()
	var (
		id       = 1
		name     = "test"
		teamName = "team"
		date     = time.Now()
		ret      string
	)
	_, err := conn.Exec(`INSERT INTO TEMP_TABLE_329(ID, NAME, TEAM_NAME, ONBOARD_DATE)
VALUES(:1, :2, :3, :4) RETURNING TEAM_NAME INTO :5`, id, name, teamName, date, go_ora.Out{Dest: &ret, Size: 100})
	if err != nil {
		return err
	}
	fmt.Println("return: ", ret)
	fmt.Println("Finish insert: ", time.Now().Sub(t))
	return nil
}
func main() {
	conn, err := sql.Open("oracle", os.Getenv("DSN"))
	if err != nil {
		fmt.Println("can't open connection: ", err)
		return
	}
	defer func() {
		err = conn.Close()
		if err != nil {
			fmt.Println("can't close connection: ", err)
		}
	}()

	err = createTable(conn)
	if err != nil {
		fmt.Println("can't create table: ", err)
		return
	}

	defer func() {
		err = dropTable(conn)
		if err != nil {
			fmt.Println("can't drop table: ", err)
		}
	}()

	err = insertData(conn)
	if err != nil {
		fmt.Println("can't insert: ", err)
	}
}
```

**Comment by thehaung** [comment]
Thank [sijms](https://github.com/sijms) for your ans. It's works now. Have a nice day!

**Comment by thehaung** [comment]
But, when I try more than 1 returning value, I got the same issue above
`_, err := conn.Exec(`INSERT INTO TEMP_TABLE_329(ID, NAME, TEAM_NAME, ONBOARD_DATE)
VALUES(:1, :2, :3, :4) RETURNING TEAM_NAME, NAME INTO :5, :6`, id, name, teamName, date, go_ora.Out{Dest: &ret, Size: 100}, go_ora.Out{Dest: &name, Size: 100})
	if err != nil {
		return err
	}
`

**Comment by sijms** [comment]
is this accepted to return multiple columns?
do you test it on another drivers

**Comment by thehaung** [comment]
I see on Oracle Documentation, support to returning multiple values, does your module support this? Or this only support return single column?

**Comment by sijms** [comment]
ok i will test it on the C# driver and see the network output

**Comment by sijms** [comment]
I find the bug i will fix and make new release

**Comment by thehaung** [comment]
This work well now, thanks for your support @sijms Have a nice day!
