### ISSUE TITLE
[Question] About *network.Session and connection pool

### ISSUE THREAD

**Issue by rtemka** [sijms/go-ora#334]
Hi @sijms! Firstly great thanks to you, I appreciate your work on this project. 

My question is this: when I invoke DB methods(*sql.DB) by several goroutines at once I get this:
```
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x972e75]

goroutine 92 [running]:
github.com/sijms/go-ora/v2/network.(*Session).ResetBuffer(...)
        /workspace/vendor/github.com/sijms/go-ora/v2/network/session.go:157
github.com/sijms/go-ora/v2.(*defaultStmt).Close(0x0?)
        /workspace/vendor/github.com/sijms/go-ora/v2/command.go:1378 +0x35
panic({0xc9a700, 0x17cc560})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/sijms/go-ora/v2/network.(*Session).ResetBuffer(...)
        /workspace/vendor/github.com/sijms/go-ora/v2/network/session.go:157
github.com/sijms/go-ora/v2.(*RefCursor).Query(0xc00032a6e0)
        /workspace/vendor/github.com/sijms/go-ora/v2/ref_cursor.go:98 +0xff
```

This is happening when database/sql connection pool [maxIdleCount](https://cs.opensource.google/go/go/+/refs/tags/go1.20.2:src/database/sql/sql.go;drc=06264b740e3bfe619f5e90359d8f0d521bd47806;l=479) < number of goroutines spawned.

It's ok and expected that not all goroutines gets their connection from pool. But panic here is a bit suprising.

Is this expected behaviour? Or am I miss something?
Thanks!

P.S. The DB methods I use does not share any common resources(refcursors) except *sql.DB itself.

**Comment by sijms** [comment]
would you test this [code](https://github.com/sijms/go-ora/issues/290#issuecomment-1377992213)

**Comment by rtemka** [comment]
Ок, I got it) Thanks @sijms! I'll close this issue.
