### ISSUE TITLE
Investigation request: v1 `DecodeDate` returns UTC times, v2 `DecodeDate` returns Local times

### ISSUE THREAD

**Issue by erezrokah** [sijms/go-ora#338]
Hello and thank you for this useful module 🚀 

This is more of a question than a bug/feature request.
I noticed v1 decodes timestamp column types (without timezone) as UTC:
https://github.com/sijms/go-ora/blob/4c3a9fcbbcc3e1b1b4f7345026f213b8a7f95416/converters/type_conversion.go#L567
while v2 decodes timestamp column types (without timezone) in Local timezone:
https://github.com/sijms/go-ora/blob/4c3a9fcbbcc3e1b1b4f7345026f213b8a7f95416/v2/converters/type_conversion.go#L1193

Is there a reason for it? I'd expected to either use the result of `SELECT DBTIMEZONE FROM DUAL` or use UTC always.

Feedback appreciated

**Comment by sijms** [comment]
Hi @erezrokah 
actually I update v2 frequently so v2 will be far more updated than v1
but I will make a major update in v1 to include latest features

**Comment by erezrokah** [comment]
Thanks for the comment @sijms, sorry for only responding now. I actually think v1 has the correct behavior (or at least the better one as UTC is more predicable than local time), WDYT?

**Comment by sijms** [comment]
yes you are correct. local timezone has no place here. I will test UTC and database timezone which is available during connection process and update it in the next release.

**Comment by sijms** [comment]
fixed in 2.6.16
