### ISSUE TITLE
cached connections with closed state are not being detected in the sql driver and keeps being reused. 

### ISSUE THREAD

**Issue by dloucasfx** [sijms/go-ora#346]
We have ran into a situation where we see this error `ORA-06413: Connection not open` repeating on every query, the error stays until the process is restarted and a new connection is created and opened.

This is our code https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/oracledbreceiver/db_client.go#L50 

Looking at the `sql` implementation, the cached connections get invalidated and new connection is opened only when the driver receives error of type `ErrBadConn` https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1540 and  https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1313 

Looking at the go-ora code, the error `ORA-06413: Connection not open` is not wrapped by `ErrBadConn` https://github.com/sijms/go-ora/blob/master/v2/command.go#L1983  is there a reason for not using `ErrBadConn`? is my interpretation of the code wrong?
If yes, please advice on how to avoid the error and establish new connection?

**Comment by sijms** [comment]
you are correct I should use ErrBadConn
Ok this I need to review failover again and test using ErrBadConn

**Comment by dloucasfx** [comment]
Thanks @sijms 
Please let me know if you have a timeline for this so I can notify the OpenTelemetry project on when the fix will be ready.
Thanks!

**Comment by sijms** [comment]
ok I am working now on struct output parameters. I will finish it soon and start fixing this issue
