### ISSUE TITLE
native encryption initiated from client side

### ISSUE THREAD

**Issue by pjezek** [sijms/go-ora#347]
Hi

Thanks for your work.

We use `go-ora` with `sqlx` to fetch data from an oracle database, which is used by other applications as well.
As we are in the process of enabling native encryption on all application - one by one at a time - we configured the server:
`SQLNET.ENCRYPTION_SERVER = ACCEPTED` so application can choose to use encryption or not.

If we use the java thin client we can configure:
`jdbc:oracle:thin:@<host>:1521:<service>?oracle.net.encryption_client=REQUIRED`
to opt in encryption.

Now we try the same with go-ora:
`db, err := sqlx.Connect("oracle", dsn)`
where `dsn` is like `"oracle://<username>:<password>@<host>:1521/<service>?oracle.net.encryption_client=REQUIRED"`
(we also tried the OCI name `SQLNET.ENCRYPTION_CLIENT`).

Using tcpdump to monitor the traffic from the application to the database I can clearly see that in the case of java it has encrypted payload. In the case of the go application I can read the payload in plain text.

Is this a bug or do I use go-ora wrong or even this is a feature request?
I don't find a hint in `newConnectionStringFromUrl` that this option is supported in the databaseUrl.

Have a nice day.

**Comment by sijms** [comment]
`oracle.net.encryption_client=REQUIRED` this url option is not supported yet

**Comment by sijms** [comment]
OK I will add this option in next release

**Comment by sijms** [comment]
fixed in v2.7.1

**Comment by pjezek** [comment]
@sijms 
thank you very much for the fix in the new version. 
I did now verify that the connection is encrypted as I would expect.
