### ISSUE TITLE
Need help in installing this library in a environment where the go get is not allowed.

### ISSUE THREAD

**Issue by crbsram** [sijms/go-ora#348]
Hi Team

WE have a windows machine where golang is installed, but go get doesn't run since it is disabled in the policy.

Is there a way available to install the same in the machine other than go mod vendor option.

**Comment by sijms** [comment]
you can disable go mod and use GOPATH environmental variables 
then download the package from GitHub using any tools

**Comment by crbsram** [comment]
Thanks for the comments.
It worked for me.
