### ISSUE TITLE
when rows.next  panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by 3wjs** [sijms/go-ora#350]
hi,Thank you for the great project！
        When I make some queries against oracle, it works fine most of the time, but sometimes I get an error like the following,
       Can you give me some advice ？ (driver.db is   *sql.DB  ,query is a select query  This also happens direct use of the package)

        indexRows, err := driver.db.Query(query, databaseName)
	if err != nil {
		return nil, db.FormatErrorWithQuery(err, query)
	}
	defer indexRows.Close()

	if indexRows.Err() != nil {
		return nil, db.FormatErrorWithQuery(indexRows.Err(), query)
	}

	for indexRows.Next() {
                   ……
         }

-----------------
panic: runtime error: integer divide by zero

goroutine 99 [running]:
github.com/sijms/go-ora/v2.(*DataSet).Next(0xc003140e10, {0xc0032f5780, 0x8, 0x100066575?})
        /Users/xxxx/go/pkg/mod/github.com/sijms/go-ora/v2@v2.6.17/data_set.go:355 +0x385
database/sql.(*Rows).nextLocked(0xc0032f5680)
        /usr/local/go/src/database/sql/sql.go:2974 +0x11a
database/sql.(*Rows).Next.func1()
        /usr/local/go/src/database/sql/sql.go:2952 +0x2f
database/sql.withLock({0x101cbee30, 0xc0032f56b0}, 0xc003209318)
        /usr/local/go/src/database/sql/sql.go:3405 +0x8c
database/sql.(*Rows).Next(0xc0032f5680)
        /usr/local/go/src/database/sql/sql.go:2951 +0x6f
myproject/db/drivers/oracle.getIndex({0x6446042e?, 0x10161e6c0?}, 0x101cca760?, {0xc00279c680?, 0x3b?})

----------------

**Comment by FrauElster** [comment]
+1

**Comment by sijms** [comment]
would you give example of sql text that produce the error

**Comment by sijms** [comment]
i find the bug and i will fix in next release soon

**Comment by sijms** [comment]
fixed in v2.7.1
