### ISSUE TITLE
Unable to process input arrays that have no non-empty values

### ISSUE THREAD

**Issue by robstradling** [sijms/go-ora#355]
When I pass a `[]string` or `[]sql.NullString` array to a PL/SQL function (using a TABLE OF VARCHAR2 input parameter), I consistently see errors whenever the array does not contain any non-empty values: `ORA-03101: invalid input data for` occurs when the array has zero elements, and `ORA-03146: invalid buffer length for TTC field` occurs when the array has one or more elements but they're all empty.

I'm also seeing `ORA-03146: invalid buffer length for TTC field` when I pass an empty `[]byte` array to a PL/SQL function (using a RAW input parameter).

This Gist demonstrates the problems I mentioned above:
https://gist.github.com/robstradling/ca8619f832e19b0785a4c89502cfedbf

Are these bugs in go-ora?  Or am I doing something wrong?

**Comment by sijms** [comment]
these are bugs and I am fixing

**Comment by sijms** [comment]
fixed in v2.7.4

**Comment by robstradling** [comment]
Many thanks @sijms !!
