### ISSUE TITLE
Blob/Clob/NClob fails when Scanning NULL value

### ISSUE THREAD

**Issue by bokwoon95** [sijms/go-ora#358]
Hallo, thanks for library. Currently all the LOB types will fail if value is nil, because you forgot to return after the check to `if value == nil`. This is causing my current script to fail because some BLOB/CLOB values are NULL (I am getting the error "go-ora: Blob column type require Blob or []byte values").

https://github.com/sijms/go-ora/blob/5a79e76a8c2b55e92b600ab19b645b2a4dec1c61/v2/lob.go#L668-L688

https://github.com/sijms/go-ora/blob/5a79e76a8c2b55e92b600ab19b645b2a4dec1c61/v2/lob.go#L642-L666

https://github.com/sijms/go-ora/blob/5a79e76a8c2b55e92b600ab19b645b2a4dec1c61/v2/lob.go#L690-L714

**Comment by sijms** [comment]
yes thanks for comment i will fix and make new release

**Comment by sijms** [comment]
fixed in v2.7.5
