### ISSUE TITLE
ORA-12564: TNS connection refused

### ISSUE THREAD

**Issue by scottpettyjohn** [sijms/go-ora#359]
In connect_packet.go there is a method that trims the connection string to 70 chars if the length > 230.

Can you provide some insight as to why this is done? I am getting a ORA-12564: TNS connection refused for some connection strings and others are working fine. It seems that the connection strings with failover configured are the ones failing. I am trying to figure out if it is related to the failover or just the length of the connection string.

func newConnectPacket(sessionCtx SessionContext) *ConnectPacket {
	connectData := sessionCtx.ConnOption.ConnectionData()
	length := uint32(len(connectData))
	if length > 230 {
		length = 0
	}
	length += 70

**Comment by scottpettyjohn** [comment]
Figured out how to turn on tracing and see that the entire connection string is being sent. I am stuck - same connection string works with goracle driver.

Sorry about pasting the contents but my company blocks file uploads.

2023-05-08T10:37:33.3141: Connect
2023-05-08T10:37:33.3434: using: myhost-001.mycompany.net:40001 ..... [SUCCEED]
2023-05-08T10:37:33.3436: Open :(DESCRIPTION_LIST=(LOAD_BALANCE=off)(FAILOVER=on)(DESCRIPTION=(CONNECT_TIMEOUT=5)(TRANSPORT_CONNECT_TIMEOUT=3)(RETRY_COUNT=3)(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=myhost-001.mycompany.net)(PORT=40001)))(CONNECT_DATA=(SERVICE_NAME=XXXXXXXX_rw)))(DESCRIPTION=(CONNECT_TIMEOUT=5)(TRANSPORT_CONNECT_TIMEOUT=3)(RETRY_COUNT=3)(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=myhost-002.mycompany.net)(PORT=40001)))(CONNECT_DATA=(SERVICE_NAME=XXXXXXXX_rw))))
2023-05-08T10:37:33.3437: 
Write packet:
00000000  00 46 00 00 01 00 00 00  01 3d 01 2c 0c 01 ff ff  |.F.......=.,....|
00000010  ff ff 4f 98 00 00 00 01  01 e4 00 46 00 00 00 00  |..O........F....|
00000020  01 01 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 20 00 00 00 20  |........... ... |
00000040  00 00 00 00 00 00                                 |......|
2023-05-08T10:37:33.3439: 
Write packet:
00000000  01 ee 00 00 06 00 00 00  00 00 28 44 45 53 43 52  |..........(DESCR|
00000010  49 50 54 49 4f 4e 5f 4c  49 53 54 3d 28 4c 4f 41  |IPTION_LIST=(LOA|
00000020  44 5f 42 41 4c 41 4e 43  45 3d 6f 66 66 29 28 46  |D_BALANCE=off)(F|
00000030  41 49 4c 4f 56 45 52 3d  6f 6e 29 28 44 45 53 43  |AILOVER=on)(DESC|
00000040  52 49 50 54 49 4f 4e 3d  28 43 4f 4e 4e 45 43 54  |RIPTION=(CONNECT|
00000050  5f 54 49 4d 45 4f 55 54  3d 35 29 28 54 52 41 4e  |_TIMEOUT=5)(TRAN|
00000060  53 50 4f 52 54 5f 43 4f  4e 4e 45 43 54 5f 54 49  |SPORT_CONNECT_TI|
00000070  4d 45 4f 55 54 3d 33 29  28 52 45 54 52 59 5f 43  |MEOUT=3)(RETRY_C|
00000080  4f 55 4e 54 3d 33 29 28  41 44 44 52 45 53 53 5f  |OUNT=3)(ADDRESS_|
00000090  4c 49 53 54 3d 28 4c 4f  41 44 5f 42 41 4c 41 4e  |LIST=(LOAD_BALAN|
000000a0  43 45 3d 6f 6e 29 28 41  44 44 52 45 53 53 3d 28  |CE=on)(ADDRESS=(|
000000b0  50 52 4f 54 4f 43 4f 4c  3d 54 43 50 29 28 48 4f  |PROTOCOL=TCP)(HO|
000000c0  53 54 3d 78 74 75 32 34  2d 73 63 61 6e 2e 62 6e  |ST=myhost-001.my|
000000d0  79 6d 65 6c 6c 6f 6e 2e  6e 65 74 29 28 50 4f 52  |company.net)(POR|
000000e0  54 3d 34 30 30 30 31 29  29 29 28 43 4f 4e 4e 45  |T=40001)))(CONNE|
000000f0  43 54 5f 44 41 54 41 3d  28 53 45 52 56 49 43 45  |CT_DATA=(SERVICE|
00000100  5f 4e 41 4d 45 3d 4f 4d  44 42 41 51 30 33 5f 72  |_NAME=XXXXXXXX_r|
00000110  77 29 29 29 28 44 45 53  43 52 49 50 54 49 4f 4e  |w)))(DESCRIPTION|
00000120  3d 28 43 4f 4e 4e 45 43  54 5f 54 49 4d 45 4f 55  |=(CONNECT_TIMEOU|
00000130  54 3d 35 29 28 54 52 41  4e 53 50 4f 52 54 5f 43  |T=5)(TRANSPORT_C|
00000140  4f 4e 4e 45 43 54 5f 54  49 4d 45 4f 55 54 3d 33  |ONNECT_TIMEOUT=3|
00000150  29 28 52 45 54 52 59 5f  43 4f 55 4e 54 3d 33 29  |)(RETRY_COUNT=3)|
00000160  28 41 44 44 52 45 53 53  5f 4c 49 53 54 3d 28 4c  |(ADDRESS_LIST=(L|
00000170  4f 41 44 5f 42 41 4c 41  4e 43 45 3d 6f 6e 29 28  |OAD_BALANCE=on)(|
00000180  41 44 44 52 45 53 53 3d  28 50 52 4f 54 4f 43 4f  |ADDRESS=(PROTOCO|
00000190  4c 3d 54 43 50 29 28 48  4f 53 54 3d 78 63 75 32  |L=TCP)(HOST=myho|
000001a0  34 2d 73 63 61 6e 2e 62  6e 79 6d 65 6c 6c 6f 6e  |st-002.mycompany|
000001b0  2e 6e 65 74 29 28 50 4f  52 54 3d 34 30 30 30 31  |.net)(PORT=40001|
000001c0  29 29 29 28 43 4f 4e 4e  45 43 54 5f 44 41 54 41  |)))(CONNECT_DATA|
000001d0  3d 28 53 45 52 56 49 43  45 5f 4e 41 4d 45 3d 4f  |=(SERVICE_NAME=X|
000001e0  4d 44 42 41 51 30 33 5f  72 77 29 29 29 29        |XXXXXXXXX_rw))))|
2023-05-08T10:37:33.3442: Start Reading
2023-05-08T10:37:33.3734: 
Read packet:
00000000  00 0c 00 00 04 00 00 00  22 00 02 52              |........"..R|
2023-05-08T10:37:33.3736: connection to myhost-001.mycompany.net:40001 refused with error: ORA-12564: TNS connection refused
2023-05-08T10:37:33.3738: Connect
2023-05-08T10:37:33.4273: using: myhost-002.mycompany.net:40001 ..... [SUCCEED]
2023-05-08T10:37:33.4275: Open :(DESCRIPTION_LIST=(LOAD_BALANCE=off)(FAILOVER=on)(DESCRIPTION=(CONNECT_TIMEOUT=5)(TRANSPORT_CONNECT_TIMEOUT=3)(RETRY_COUNT=3)(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=myhost-001.mycompany.net)(PORT=40001)))(CONNECT_DATA=(SERVICE_NAME=XXXXXXXX_rw)))(DESCRIPTION=(CONNECT_TIMEOUT=5)(TRANSPORT_CONNECT_TIMEOUT=3)(RETRY_COUNT=3)(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=myhost-002.mycompany.net)(PORT=40001)))(CONNECT_DATA=(SERVICE_NAME=XXXXXXXX_rw))))
2023-05-08T10:37:33.4276: 
Write packet:
00000000  00 46 00 00 01 00 00 00  01 3d 01 2c 0c 01 ff ff  |.F.......=.,....|
00000010  ff ff 4f 98 00 00 00 01  01 e4 00 46 00 00 00 00  |..O........F....|
00000020  01 01 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 20 00 00 00 20  |........... ... |
00000040  00 00 00 00 00 00                                 |......|
2023-05-08T10:37:33.4277: 
Write packet:
00000000  01 ee 00 00 06 00 00 00  00 00 28 44 45 53 43 52  |..........(DESCR|
00000010  49 50 54 49 4f 4e 5f 4c  49 53 54 3d 28 4c 4f 41  |IPTION_LIST=(LOA|
00000020  44 5f 42 41 4c 41 4e 43  45 3d 6f 66 66 29 28 46  |D_BALANCE=off)(F|
00000030  41 49 4c 4f 56 45 52 3d  6f 6e 29 28 44 45 53 43  |AILOVER=on)(DESC|
00000040  52 49 50 54 49 4f 4e 3d  28 43 4f 4e 4e 45 43 54  |RIPTION=(CONNECT|
00000050  5f 54 49 4d 45 4f 55 54  3d 35 29 28 54 52 41 4e  |_TIMEOUT=5)(TRAN|
00000060  53 50 4f 52 54 5f 43 4f  4e 4e 45 43 54 5f 54 49  |SPORT_CONNECT_TI|
00000070  4d 45 4f 55 54 3d 33 29  28 52 45 54 52 59 5f 43  |MEOUT=3)(RETRY_C|
00000080  4f 55 4e 54 3d 33 29 28  41 44 44 52 45 53 53 5f  |OUNT=3)(ADDRESS_|
00000090  4c 49 53 54 3d 28 4c 4f  41 44 5f 42 41 4c 41 4e  |LIST=(LOAD_BALAN|
000000a0  43 45 3d 6f 6e 29 28 41  44 44 52 45 53 53 3d 28  |CE=on)(ADDRESS=(|
000000b0  50 52 4f 54 4f 43 4f 4c  3d 54 43 50 29 28 48 4f  |PROTOCOL=TCP)(HO|
000000c0  53 54 3d 78 74 75 32 34  2d 73 63 61 6e 2e 62 6e  |ST=myhost-001.my|
000000d0  79 6d 65 6c 6c 6f 6e 2e  6e 65 74 29 28 50 4f 52  |company.net)(POR|
000000e0  54 3d 34 30 30 30 31 29  29 29 28 43 4f 4e 4e 45  |T=40001)))(CONNE|
000000f0  43 54 5f 44 41 54 41 3d  28 53 45 52 56 49 43 45  |CT_DATA=(SERVICE|
00000100  5f 4e 41 4d 45 3d 4f 4d  44 42 41 51 30 33 5f 72  |_NAME=XXXXXXXX_r|
00000110  77 29 29 29 28 44 45 53  43 52 49 50 54 49 4f 4e  |w)))(DESCRIPTION|
00000120  3d 28 43 4f 4e 4e 45 43  54 5f 54 49 4d 45 4f 55  |=(CONNECT_TIMEOU|
00000130  54 3d 35 29 28 54 52 41  4e 53 50 4f 52 54 5f 43  |T=5)(TRANSPORT_C|
00000140  4f 4e 4e 45 43 54 5f 54  49 4d 45 4f 55 54 3d 33  |ONNECT_TIMEOUT=3|
00000150  29 28 52 45 54 52 59 5f  43 4f 55 4e 54 3d 33 29  |)(RETRY_COUNT=3)|
00000160  28 41 44 44 52 45 53 53  5f 4c 49 53 54 3d 28 4c  |(ADDRESS_LIST=(L|
00000170  4f 41 44 5f 42 41 4c 41  4e 43 45 3d 6f 6e 29 28  |OAD_BALANCE=on)(|
00000180  41 44 44 52 45 53 53 3d  28 50 52 4f 54 4f 43 4f  |ADDRESS=(PROTOCO|
00000190  4c 3d 54 43 50 29 28 48  4f 53 54 3d 78 63 75 32  |L=TCP)(HOST=myho|
000001a0  34 2d 73 63 61 6e 2e 62  6e 79 6d 65 6c 6c 6f 6e  |st-002.mycompany|
000001b0  2e 6e 65 74 29 28 50 4f  52 54 3d 34 30 30 30 31  |.net)(PORT=40001|
000001c0  29 29 29 28 43 4f 4e 4e  45 43 54 5f 44 41 54 41  |)))(CONNECT_DATA|
000001d0  3d 28 53 45 52 56 49 43  45 5f 4e 41 4d 45 3d 4f  |=(SERVICE_NAME=X|
000001e0  4d 44 42 41 51 30 33 5f  72 77 29 29 29 29        |XXXXXXX_rw))))|
2023-05-08T10:37:33.4279: Start Reading
2023-05-08T10:37:33.4821: 
Read packet:
00000000  00 0c 00 00 04 00 00 00  22 00 02 52              |........"..R|
2023-05-08T10:37:33.4824: connection to myhost-002.mycompany.net:40001 refused with error: ORA-12564: TNS connection refused

**Comment by sijms** [comment]
```golang
connOption.Tracer.Print("Open :", connOption.ConnectionData())
connectPacket := newConnectPacket(*session.Context)
err = session.writePacket(connectPacket)
if err != nil {
	return err
}
// if length > 230 means connection data sent empty       <-------------------------
if uint16(connectPacket.packet.length) == connectPacket.packet.dataOffset {
       // send connection data as data packet             <-------------------------
	session.PutBytes(connectPacket.buffer...)
	err = session.Write()
	if err != nil {
		return err
	}
}
```
here is the code in session.go
if length of connection string is more than 230 then send empty connection packet followed by data packet that contain connection string

**Comment by scottpettyjohn** [comment]
Any idea why I would be getting the ORA-12564: TNS connection refused? This same connection string works with a different driver.

**Comment by sijms** [comment]
1- confirm that you are using service name not SID. it you need to use SID so leave service name empty and pass an url option with SID
```golang
urlOptions := map[string]string {
    "trace file": "trace.log",
    "sid": "your Sid",
}
connStr := go_ora.BuildUrl(server, port, "" /*empty service*/, user, pass, urlOptions)
```
2- does you server need SSL. As I see connection success at first
`using: myhost-001.mycompany.net:40001 ..... [SUCCEED]`
to use SSL pass urlOption: `SSL=true&ssl verify=false&wallet=wallet_path`
