### ISSUE TITLE
How to configure SetMaxIdleConns  and SetMaxOpenConns

### ISSUE THREAD

**Issue by RafaMnzs** [sijms/go-ora#364]
Hi... I need to adjust my settings with sames  options, but when i use go_ora.NewConnection  i don't know with configure  SetMaxIdleConns and SetMaxOpenConns

**Comment by sijms** [comment]
go-ora is not support connection pooling so you should use connection pooling come with database/sql package.
now you can use package with database/sql in almost any situation like (query, exec, cursor, bulk[insert/merge], structures,....) except some rare condition like (UDT)
