### ISSUE TITLE
BLOB field value is truncated to 32KB

### ISSUE THREAD

**Issue by askripalev** [sijms/go-ora#367]
Hi there!

I'm using go-ora as driver for native database/sql package. Everything works fine, but I've ran into a problem while selecting BLOB's value from arbitrary table: I'm getting only first 32 kilobytes (exactly 32768 bytes) from BLOB's field value.

Here is my code example:
```
package main

import (
	"database/sql"
	"fmt"
	"log"
	"os"
	"time"

	_ "github.com/sijms/go-ora/v2"
)

func main() {
	conn, _ := sql.Open("oracle", "oracle://xxx:yyy@127.0.0.1:1521/zzz")
	conn.SetMaxOpenConns(32)
	conn.SetMaxIdleConns(32)
	conn.SetConnMaxIdleTime(time.Minute)

	query := "select pos, filename, mimetype, filesize, filecontents from attachments"
	sqlResult, err := conn.Query(query)
	if err != nil {
		log.Fatal(err.Error())
	}
	defer func(sqlResult *sql.Rows) {
		err := sqlResult.Close()
		if err != nil {
			return
		}
	}(sqlResult)

	type attachment struct {
		pos          int    `db:"type=number,name=POS"`
		filename     string `db:"type=varchar,name=FILENAME"`
		mimetype     string `db:"type=varchar,name=MIMETYPE"`
		filesize     int    `db:"type=number,name=FILESIZE"`
		filecontents []byte `db:"type=blob,name=FILECONTENTS"`
	}

	data := &attachment{}

	for sqlResult.Next() {
		if err := sqlResult.Scan(
			&data.pos,
			&data.filename,
			&data.mimetype,
			&data.filesize,
			&data.filecontents,
		); err != nil {
			fmt.Println(err.Error())
		}

		fmt.Println(data.pos, data.filename, data.mimetype, data.filesize, len(data.filecontents))
	}
}
```

Output:
```
1 test1.jpg image/jpeg 52988 32768
2 test2.jpg image/jpeg 52988 32768
3 text3.png image/png 213756 32768
```

As we can see, value of the BLOB field is truncated exactly to 32768 bytes (4th value is an actual value size, 5th value is a length of BLOB field).

I did some research and find out that in case of selecting BLOB data as described in examples/clob/main.go (functions  
readWithOutputParameters or readWithOutputParameters2) all works as planned.
It's a pity, but I can't use go_ora.NewConnection, because it doesn't make connection pool, which sql.Open does.

So, what should I do to solve the issue?

**Comment by sijms** [comment]
if BLOB size is truncate to 32 KB this means that it read as a RAW value which has max size of 32 KB so BLOB should read as 
blob 
i will investigate the issue

**Comment by sijms** [comment]
I test the code
would you please test again with url option `lob fetch=post`

**Comment by askripalev** [comment]
Change of URL to `conn, _ := sql.Open("oracle", "oracle://xxx:yyy@127.0.0.1:1521/zzz?lob fetch=post")` did a trick!

No it works as supposed to be:
```
1 test1.jpg image/jpeg 52988 52988 
2 test2.jpg image/jpeg 52988 52988 
3 text3.png image/png 213756 213756 
```

Thanks a lot :)
