### ISSUE TITLE
Change log prints only to Debug mode

### ISSUE THREAD

**Issue by iamrodrigoit** [sijms/go-ora#37]
Hi @sijms ,

After the resolution of the issue #23 , there is 3 lines that is always printing logs.

Lines that is generating the prints: 
```golang
// all data returned from the server
fmt.Println("data returned: ", data) 

// redirect address
fmt.Println("redirect address: ", pck.redirectAddr)

// reconnect data
fmt.Println("reconnect data: ", pck.reconnectData)
```

Is it possible to change the code to print these 3 lines only when running in Debug mode?

**Comment by sijms** [comment]
I make changes
