### ISSUE TITLE
Regarding oracle cursor.fetchmany fucntion feature in go-ora

### ISSUE THREAD

**Issue by crbsram** [sijms/go-ora#373]
Hi 

Would like to know whether the feature of oracur.fetchmany(batchsize) in cx_oracle library in python availability in go-ora package.

Because we could pull the records in batches and iterate on the same.

Please let me know on the same.

Thanks
C.R.Bala

**Comment by sijms** [comment]
Hi
`fetchmany` is equal to database/sql `Query()` and `batchsize` is equal to `PREFETCH_ROWS` url option
