### ISSUE TITLE
Concurrent queries in goroutines fail with "ORA-12599: TNS:cryptographic checksum mismatch" if connection offers failover for 2 active nodes

### ISSUE THREAD

**Issue by agunglotto** [sijms/go-ora#374]
When running statements every few seconds in goroutines, the behavior is normal when I connect against a single node of an active data guard setup.
If I use a failover (not really necessary, as both nodes are operating normal), after some time I get
ORA-12599: TNS:cryptographic checksum mismatch
reported. Stability of the application seems to decrease. Sometimes I see connection timeouts after a while.
Using another version of the application based on godror, I don't experience any errors when configuring the connection for both modes.
The TNS definition looks like this:

(DESCRIPTION=
  (ADDRESS_LIST=(LOAD_BALANCE=OFF)(FAILOVER=ON)
    (ADDRESS=(PROTOCOL=tcp)(HOST=host_dguard)(PORT=1521))
    (ADDRESS=(PROTOCOL=tcp)(HOST=host_active)(PORT=1521))
  )
  (CONNECT_DATA=(SERVICE_NAME=service)(SERVER=DEDICATED))
)

I've no idea how to reproduce the behaviour in a small demo setup. However I experience the problems in almost all failover setups, if both nodes are active and available.

**Comment by agunglotto** [comment]
Some more details about the instances which might be important to reproduce and fix:

The service name on one instance is "service" and on the other instance "service_RO". Using an address list, I can only specify one service name. Actually the connection should be stable to one of the alternatives, als LOAD_BALANCE is off. It seams, somehow there are trials to reach the other address which must fail.

So it's not one of two hosts or both are available and the connection to the service is possible. Both of the hosts react on the port, but one is offering only different service which is not specified.

**Comment by sijms** [comment]
Hi @agunglotto 
sorry for late update. until now the driver support only one service so if you have same service name on both host you can use them.
the failover used is one offered by database/sql package and is done by specify connection as bad so package will discard and make new connection to the hosts

about the error `ora-12599` I think to solve the error you should use log file and see at which statement or connection stage this error happen

**Comment by sijms** [comment]
would you please test again after fixing issue #444

**Comment by agunglotto** [comment]
"ORA-12599: TNS:cryptographic checksum mismatch" does not occur anymore. It's fixed now.
