### ISSUE TITLE
bug: `uint64` values are truncated on insert

### ISSUE THREAD

**Issue by erezrokah** [sijms/go-ora#378]
Hi 👋 Thank you for this lovely module, it works great 🚀 

I think I discovered a bug when trying to insert `unit64` values. It seems those are casted to `int64` before encoded, so data is loss.
See:
https://github.com/sijms/go-ora/blob/41ca433ee475e64869448c27e6e20ad038613ae4/v2/parameter_encode.go#L308
https://github.com/sijms/go-ora/blob/41ca433ee475e64869448c27e6e20ad038613ae4/v2/parameter_encode.go#L337

Can you confirm my findings?

**Comment by sijms** [comment]
sorry for late replay
I am fighting to add UDT array as an output parameter and finally I do
I fix the issue and add encodeUint64 for uint64 type

**Comment by erezrokah** [comment]
Thanks @sijms! I tried testing the new release and getting:
```
ORA-01461: can bind a LONG value only for insert into a LONG column
```

For a query that was working before (didn't manage to test the `unit64` due to it). Do you know what might be the problem? I'm not sure any `LONG` types in my query.

I can try and provide a reproducible query if you need one.

**Comment by sijms** [comment]
would you send tested code to regenerate the error
because I re-code all functions related to parameter encoding and decoding

**Comment by erezrokah** [comment]
> would you send tested code to regenerate the error
> because I re-code all functions related to parameter encoding and decoding

Sure, let me prepare the smallest possible query to reproduce this

**Comment by erezrokah** [comment]
Hi @sijms, the follow test should reproduce the error. You'll need to update the connection string

```go
func getTestDB(ctx context.Context) (*sql.DB, error) {
	db, err := sql.Open("oracle", "oracle://user:pass@localhost:/db")
	if err != nil {
		return nil, err
	}
	conn, err := db.Conn(ctx)
	if err != nil {
		return nil, err
	}
	defer conn.Close()
	return db, err
}

func TestLongError(t *testing.T) {
	ctx := context.Background()
	db, err := getTestDB(ctx)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	_, _ = db.ExecContext(ctx, `DROP TABLE "long_error"`)
	createTableQuery := `CREATE TABLE "long_error" (
		"_cq_source_name" clob,
		"_cq_sync_time" timestamp,
		"_cq_id" raw(16),
		"_cq_parent_id" raw(16),
		"binary" blob,
		CONSTRAINT "long_error" PRIMARY KEY("_cq_id")
	  )`
	if _, err := db.ExecContext(ctx, createTableQuery); err != nil {
		t.Fatal(err)
	}

	insertQuery := `INSERT INTO "test_long_error" ("_cq_source_name", "_cq_sync_time", "_cq_id", "_cq_parent_id", "binary") VALUES (:1, :2, :3, :4, :5)`
	name := ""
	now := time.Now()
	id := []byte{251, 235, 184, 140, 247, 88, 75, 71, 142, 177, 147, 116, 124, 130, 216, 154}
	id2 := []byte{100, 71, 16, 9, 252, 62, 67, 67, 145, 79, 194, 78, 177, 138, 58, 135}
	blob := []byte{239, 78, 61, 82}
	if _, err := db.ExecContext(ctx, insertQuery, name, now, id, id2, blob); err != nil {
		t.Fatal(err)
	}
}
```

Please let me know if that helps

**Comment by sijms** [comment]
sorry for late again
I fix the issue it is related to parameter.MaxLen this value should not be 0 so when it is 0 (means null or empty value) I convert it to 1

**Comment by erezrokah** [comment]
Hi @sijms, sorry for the delay the latest version (`v2.7.9`) works great, so I'll go ahead and close this issue
