### ISSUE TITLE
nonsupport Chinese characters

### ISSUE THREAD

**Issue by 1580739389** [sijms/go-ora#38]
test1汉字
shown as
test1����

**Comment by sijms** [comment]
Chinese charset is not supported by the client return to issue #13

**Comment by sijms** [comment]
Hi JuchangGit
I add support for more charset including 852 (zhs16gbk) you can test and feedback

**Comment by JuchangGit** [comment]
I have been paying attention to it and thank you very much for the project you provided




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sijms/go-ora"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月22日(星期一) 晚上7:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sijms/go-ora] nonsupport Chinese characters (#38)





 
Hi JuchangGit
 I add support for more charset including 852 (zhs16gbk) you can test and feedback
