### ISSUE TITLE
internal state weirdness

### ISSUE THREAD

**Issue by nvx** [sijms/go-ora#382]
Had some weirdness pop up in the logs overnight.

Version: `github.com/sijms/go-ora/v2 v2.7.6`

`runtime error: integer divide by zero` triggered at `github.com/sijms/go-ora/v2.(*DataSet).Next:325`

Also a bunch of scan errors `missing destination name SOME_COLUMN in *SomeType`, but looking at the query where the error was thrown, `SOME_COLUMN` was not present in the query at all. This happened a whole bunch of times in different places for different columns. It seemed like queries being run in one goroutine were having the results returned to a different goroutine that was executing a different query concurrently perhaps?

Finally we had this error a bunch as well `TTC error: received code 16 during response reading` (as this wasn't a panic we don't have stack trace information of where it was thrown inside go-ora driver, but it was a returned err from the sql package during a query).

Until now, go-ora has been pretty stable so I'm not sure what triggered this all of a sudden. After 25 minutes of weirdness in the logs it seemed to fix itself (we have a maximum connection lifetime specified in the database/sql package, so I wonder if once those connections were aged out the issue fixed itself). There were some `ORA-01013: user requested cancel of current operation` appearing in the logs as well which isn't too surprising (if a client goes away the context will get cancelled by the http server) but perhaps this was the trigger that caused the internal state to get unhappy in the first place?

**Comment by nvx** [comment]
On closer inspection, we were running go-ora `v2.6.1` until only a few days ago, so it's possible this is a regression between `v2.6.1` and `v2.7.6` which would explain why we haven't run into it before.

**Comment by hrvylein** [comment]
Same Here. Went back to 2.6.17.

**Comment by sijms** [comment]
I will add some fix in v2.7.8 that will stop divide by zero panic

**Comment by hrvylein** [comment]
so no fix for "ORA-01013: user requested cancel of current operation"? this occurs randomly with 2.7.6 on long running queries (1 minute for example) without canceling the ctx.

**Comment by dekke046** [comment]
I also moved back to version v2.6.17.
Version 2.7.7 gives on frequent base the "ORA-01013: user requested cancel of current operation" error.

With v2.6.17 the bulk/stream loading is stable, loading 7.7 million records into a 4 node Oracle ExaCC production cluster.

**Comment by rusco** [comment]
I was hit by the **"ORA-01013: user requested cancel of current operation"** error too . I found this workaround which allows me to stick with 2.7.7. I just append the Offset/Fetch next statements at the end with a value of 100 000 (one hundred thousand), but in my case I am sure that I always get less then 10 000 (ten thousand) resulting rows.  If this applies the workaround should be applicable:

```sql
 OFFSET          0 ROWS 
FETCH NEXT 100000 ROWS ONLY --make sure you get less than 100 000 rows 
```

**Comment by sijms** [comment]
default global timeout is 30 seconds so increase the value will give more time for longer query
```golang
urlOptions := map[string]string {
    "TIMEOUT": "120",  //  2 minutes
}
databaseURL := go_ora.BuildUrl(server, port, service, username, password, urlOptions)
```

**Comment by sijms** [comment]
you can disable global timeout option by set its value to 0
