### ISSUE TITLE
Error in v2@v2.7.7

### ISSUE THREAD

**Issue by savedev002** [sijms/go-ora#385]
I try to connect to Oracle11g with this version, but I get error doing sqlx.Connect() err: output parameter should be pointer type. When doing sqlx.Open() there is no problem. With the same database I use version 2.7.6 and I have no problem.

**Comment by seamusv** [comment]
I have the same issue using `database/sql` and I try to ping.  I have tracked the issue down to the parameter decoder in `v2/connection.go L2105` for parsing the NLS data.  Here is my sample code to receive the error:

```
package main

import (
	"database/sql"
	"flag"
	_ "github.com/sijms/go-ora/v2"
)

func main() {
	dsn := flag.String("dsn", "", "database connection string")
	flag.Parse()

	conn, err := sql.Open("oracle", *dsn)
	if err != nil {
		panic(err)
	}

	if err := conn.Ping(); err != nil {
		panic(err) // output parameter should be pointer type
	}
}
```

**Comment by ouadi** [comment]
I have the same issue when I moved from v2.7.6 to v2.7.7. The panic happens when I execute:

```
stmt, err := conn.Prepare(sql)
if err != nil {
	panic(err) // output parameter should be pointer type
}
```

**Comment by ouadi** [comment]
Same issue for me too when I moved from v2.7.6 to v2.7.7.

**Comment by cjxsimon** [comment]
Same issue for me when I moved upgrade to v2.7.7.

**Comment by rodrigocfd** [comment]
I'm having the same exact problem, this error was introduced in v2.7.7.

To everyone having this problem: just downgrade to v2.7.6 and it will work again.

**Comment by sijms** [comment]
fixed in new release I also fix reading output struct

**Comment by seamusv** [comment]
I have upgraded to v2.7.8 and I no longer have issues.  Thank you!
