### ISSUE TITLE
Acquisition failed   wait_time

### ISSUE THREAD

**Issue by xiajing869** [sijms/go-ora#387]
level=errorErrorscraping  for=wait_time"unsupported value type" 58.078497ms=:   ，   Other normal

**Comment by xiajing869** [comment]
ts=2023-06-20T09:21:57.998Z caller=collector.go:315 level=error Errorscrapingfor=resource _="unsupported value type" 66.988323ms=:
ts=2023-06-20T09:21:58.002Z caller=collector.go:315 level=error Errorscrapingfor=wait_time _="unsupported value type" 70.71738ms=:
ts=2023-06-20T09:21:58.043Z caller=main.go:70 level=info msg="Starting oracledb_exporter" version="(version=, branch=, revision=145b4ee86cbf5cea6
6d3d296a3254b30341bebeb)"
ts=2023-06-20T09:21:58.043Z caller=main.go:71 level=info msg="Build context" build="(go=go1.19.4, platform=linux/amd64, user=, date=, tags=unknow
n)"
ts=2023-06-20T09:21:58.043Z caller=main.go:72 level=info msg="Collect from: " metricPath=/metrics
ts=2023-06-20T09:21:58.044Z caller=tls_config.go:274 level=info msg="Listening on" address=[::]:9161
ts=2023-06-20T09:21:58.044Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9161

**Comment by sijms** [comment]
would please explain the issue
