### ISSUE TITLE
COLB AND BLOB

### ISSUE THREAD

**Issue by 1580739389** [sijms/go-ora#39]
CLOB is unsupported
BLOB ？

**Comment by sijms** [comment]
actually still the driver not support LOBs but I am working on it and I will inform you when finish

**Comment by 1580739389** [comment]
You' ve had a long day

**Comment by 1580739389** [comment]
thank you

**Comment by 1580739389** [comment]
My English is not good, so please forgive me if I say something wrong
我的英语水平不好，如果说错话了请您包涵

**Comment by sijms** [comment]
no. no problem
my English is worse than your English.

**Comment by 1580739389** [comment]
You are modest. I am Chinese

**Comment by sijms** [comment]
thank you. I am Egyptian

**Comment by sijms** [comment]
hi again
actually I find (after one week of hard work) that working with LOB is very complicated issue

but thanks god I start to understand the network behavior (still not 100%) but at least I success in get one record contain BLOB column correctly without error

please test and feedback

**Comment by sijms** [comment]
I test and get 4 rows with one BLOB column

**Comment by 1580739389** [comment]
very powerful
I tested the BLOB type with no problem
thank you
