### ISSUE TITLE
Oracle 11g failed with errror "output parameter should be pointer type"

### ISSUE THREAD

**Issue by d-bytebase** [sijms/go-ora#396]
We can follow instruction https://hub.docker.com/r/oracleinanutshell/oracle-xe-11g to install Oracle 11g.

For Bytebase, we have to downgrade go-ora version from v2.7.7 to v2.7.1 for now. By the way, v2.7.7 still work for Oracle 12+. Thanks!

https://github.com/bytebase/bytebase/pull/6983

**Comment by sijms** [comment]
there is a problem reading struct par which is used for getting NLS data in case of oracle 11g 
I fix this issue in 2.7.8
