### ISSUE TITLE
Reading from previous row if result is null

### ISSUE THREAD

**Issue by dpajkovic** [sijms/go-ora#398]
After upgrading to 2.7.7 (checked with 2.7.8 as well) I get a weird case when scanning rows of results. If a field is null the scan sets the value of the field from the previous row.

I've tested with versions 2.7.1 to 2.7.8 and it works fine (not assigning wrong value) up to and including 2.7.6, but fails on later versions.

**Comment by sijms** [comment]
fixed in 2.7.9 please check

**Comment by sijms** [comment]
please check with v2.7.9
