### ISSUE TITLE
Add feature to ReadDbmsOutput

### ISSUE THREAD

**Issue by hmmftg** [sijms/go-ora#399]
Hi,
 some times mostly for debug reasons we add **dbms_output.put_line** inside our code to get plsql trace log
can you add a mechanism for EnableDbmsOutput and ReadDbmsOutput to get those logs?

**Comment by sijms** [comment]
sorry for late
i will try to add it and inform you

**Comment by sijms** [comment]
implemented in next release

**Comment by sijms** [comment]
now available in v2.7.11
