### ISSUE TITLE
Getting error ORA-01882

### ISSUE THREAD

**Issue by fleshin** [sijms/go-ora#4]
Hi,
I am getting the error "ORA-01882: timezone region not found" when I try to stablish a connection to Oracle server (12c)
Using latest go (1.15) on linux.

Any idea?

Thanks!!!

**Comment by sijms** [comment]
# the function that get time zone:
    func TZBytes() []byte {
      _, offset := time.Now().Zone()
      hours := int8(offset / 3600)
      minutes := int8((offset / 60) % 60)
      seconds := int8(offset % 60)
      return []byte{128, 0, 0, 0, uint8(hours + 60), uint8(minutes + 60), uint8(seconds + 60), 128, 0, 0, 0}
    }
present in the file data_type_nego.go
as you see from the code time zone is get from the local machine

try to make timezone of the client same as server or change the function to send the correct time zone for the server
**_if you are using the code inside a docker_** you need to mount 
`-v /etc/localtime:/etc/localtime`
in the running contianer to get the correct timezone otherwise it will be default to UTC

**Comment by fleshin** [comment]
Hey, thanks for the prompt answer.

I forgot to mention that the server and client are on the same machine ( a linux VM, no docker or containers used)

I was trying to do something like explained [here](https://stackoverflow.com/questions/9156379/ora-01882-timezone-region-not-found) for java, but adapted to your code. Have you seen this?

**Comment by sijms** [comment]
sorry for my poor english
this answer form link you mention
**`There is also different behavior on the JDBC client side. Starting with 11.2 the driver will sent the zone IDs if it is "known" to Oracle, whereas before it sent the time offset.`**
my driver send offset not ID as you see above

the error you get is not related to the driver it is related to difference in timezone between you server and client
just go to the function `func TZBytes() []byte` and add `fmt.Println(time.Now().Zone())` to see you time zone in the client and compare it with the server

**Comment by fleshin** [comment]
The Oracle server and the oracle client are running on the same VM, in the same timezone which is reported by Go as EDT (-4).
Even with both client and server on the same VM, the DB server seems to be reporting GMT time as per:

  TZBytest: [128 0 0 0 56 60 60 128 0 0 0]
  result.DBTimeZone: [128 0 0 0 60 60 60 128 0 0 0]

Then I moved the OS timezone to GMT through timedatectl, obtaining:
  TZBytest: [128 0 0 0 60 60 60 128 0 0 0]
  result.DBTimeZone: [128 0 0 0 60 60 60 128 0 0 0]

This time the offset seems to match, but I am still getting the same error.
As per your code, the timezone ID is discarded ( using _ ) and only the offset is sent to the server.
I would like to try to send the TZ id to the server. 

Is any of the TZBytes reserved for TZ id ?

Thanks!

**Comment by fleshin** [comment]
I traced the session with wireshark and found that the error comes immediately after the  authentication request. 
In particular these lines of code are involved:
	tz, _ := time.Now().Zone()
	if !strings.Contains(tz, ":") {
		tz += ":00"
	}
	session.PutKeyValString("AUTH_ALTER_SESSION",
		fmt.Sprintf("ALTER SESSION SET NLS_LANGUAGE='AMERICAN' NLS_TERRITORY='AMERICA'  TIME_ZONE='%s'\x00", tz), 

If I remove the TIME_ZONE attribute from that line, the TZ error goes away but it still fails with an "invalid character" error. Also, wireshark shows an extra character (13) between the trailing A in AMERICA and the closing quote (')

I can send you the wireshark capture if it is useful...

**Comment by sijms** [comment]
thank you
you nearly find the source of problem
i remove the time zone and the code like this and every thing is ok 

`fmt.Sprintf("ALTER SESSION SET NLS_LANGUAGE='AMERICAN' NLS_TERRITORY='AMERICA'\x00"), 1)`

i think i need to make map to pass correct timezone to the server in the session

**Comment by sijms** [comment]
i test also this code and it works

`fmt.Sprintf("ALTER SESSION SET NLS_LANGUAGE='AMERICAN' NLS_TERRITORY='AMERICA'  TIME_ZONE='00:00'\x00"), 1)`

this means that the problem in this code 

    tz, _ := time.Now().Zone()
      if !strings.Contains(tz, ":") {
      tz += ":00"
    }

if you can make a print tz value to see what is the problem?

**Comment by fleshin** [comment]
Changed to this line and worked!!
fmt.Sprintf("ALTER SESSION SET NLS_LANGUAGE='AMERICAN' NLS_TERRITORY='AMERICA' TIME_ZONE='00:00'\x00"), 1)

The output of tz is: EDT:00

Are you looking for offset instead of Zone?

Compiled with go 1.15.3 and 1.14.7

**Comment by sijms** [comment]
thank you a lot for tracing and solving this error
I make a commit that contains changes that solve the problem 
I am using offset and calculate the time zone according

**Comment by sijms** [comment]
if this solve the issue please close

**Comment by fleshin** [comment]
The latest version worked perfectly. Thanks a lot for providing a fix so fast!!
