### ISSUE TITLE
TIMEOUT parameters

### ISSUE THREAD

**Issue by askripalev** [sijms/go-ora#411]
Hi!
Can you make a separate TIMEOUT parameters for query timeout and database connection timeout? 
According to connection_string.go source file, TIMEOUT, CONNECT TIMEOUT and CONNECTION TIMEOUT are all the same thingines.

**Comment by sijms** [comment]
`TIMEOUT` URL option is a global timeout for the driver this protect the code from hang up.
if you want to use specific timeout use Context version of sql function `ConnectContext, QueryContext, ExecContext, PingContect, ...`
