### ISSUE TITLE
Oracle DATE mapped to a UTC time (v2.7.9)

### ISSUE THREAD

**Issue by ETLJ** [sijms/go-ora#413]
It appears that values in my table of type DATE are getting mapped to a UTC time in my program, but I am new to the project and I'm probably just doing something wrong.

I have values in my table that are of type DATE, and in SqlDeveloper I see that my sessiontimezone is America/New_York:

![query_results](https://github.com/sijms/go-ora/assets/26886808/9cc6efc4-eba6-432e-b35a-d7b6fcb6610b)

But when I run that same query in my Go program, I see

![go_output](https://github.com/sijms/go-ora/assets/26886808/e13c5fda-dd3b-4ead-8b5f-98318b6dd496)

The sessiontimezone looks correct at -04:00 for America/New_York, but the created date is UTC.

Is there something I need to do in order to get the DATE mapped over to my timezone? I'm happy to provide more details just let me know. Thanks!

**Comment by iverycd** [comment]
Hi,you may could try using `time.LoadLocation`  and `time.ParseInLocation`.

Below code is my new project:

```go
        toBeCharge := "2023-07-26T15:22:52Z"
	timeLayout := "2006-01-02T15:04:05Z"
	loc, _ := time.LoadLocation("Local")
	theTime, _ := time.ParseInLocation(timeLayout, toBeCharge, loc)
	fmt.Println("oracle date convert to str1", theTime.Format("2006-01-02 15:04:05"))

	timeStr := "15-JUN-23 10.57.44 PM"
	timeTemplate := "02-Jan-06 03.04.05 PM"
	local, _ := time.LoadLocation("Local")
	yourTime, _ := time.ParseInLocation(timeTemplate, timeStr, local)
	fmt.Println("oracle date convert to str2", yourTime.Format("2006-01-02 15:04:05"))
``` 

![image](https://github.com/sijms/go-ora/assets/35289289/998a5126-63c0-4d0e-86fd-1fd9c6549ccb)
