### ISSUE TITLE
How to change Oracle session parameter value like NLS_TIMESTAMP_FORMAT

### ISSUE THREAD

**Issue by iverycd** [sijms/go-ora#414]
Hi,Thank you for the great project!
I am new for this project and my code connect to oracle,i need to change `Oracle NLS_DATE_FORMAT` parameter like below:

`alter session set NLS_TIMESTAMP_FORMAT= 'YYYY-MM-DD HH:MI:SS.FF';`

![image](https://github.com/sijms/go-ora/assets/35289289/1625e8ab-3270-434f-9f30-d82242ae1ab8)

How can i using go-ora change this parameter value,i did not find this example in your project

**Comment by sijms** [comment]
Hi @iverycd 
this is the code to call alter session and change this parameter
```golang
func main() {
conn, err := sql.Open("oracle", os.Getenv("DSN"))
	if err != nil {
		fmt.Println("connection error: ", err)
		return
	}
	defer func() {
		err = conn.Close()
		if err != nil {
			fmt.Println("error during conn close: ", err)
		}
	}()
	_, err = conn.Exec(`alter session set NLS_TIMESTAMP_FORMAT= 'YYYY-MM-DD HH:MI:SS.FF'`)
	if err != nil {
		fmt.Println("execute error: ", err)
		return
	}
}
```

**Comment by iverycd** [comment]
> Hi @iverycd this is the code to call alter session and change this parameter
> 
> ```go
> func main() {
> conn, err := sql.Open("oracle", os.Getenv("DSN"))
> 	if err != nil {
> 		fmt.Println("connection error: ", err)
> 		return
> 	}
> 	defer func() {
> 		err = conn.Close()
> 		if err != nil {
> 			fmt.Println("error during conn close: ", err)
> 		}
> 	}()
> 	_, err = conn.Exec(`alter session set NLS_TIMESTAMP_FORMAT= 'YYYY-MM-DD HH:MI:SS.FF'`)
> 	if err != nil {
> 		fmt.Println("execute error: ", err)
> 		return
> 	}
> }
> ```

Thanks,it works for me
