### ISSUE TITLE
TIMESTAMP WITH TIME ZONE not equal in 12C and 19C

### ISSUE THREAD

**Issue by cjxsimon** [sijms/go-ora#419]
i wrote a project, found that the value with type: TIMESTAMP WITH TIME ZONE, not equal when i scan from this driver

**Comment by sijms** [comment]
yes I test.
strange thing
I create 2 database with time zone UTC one in 12c and one in 19c and get different result

**Comment by sijms** [comment]
I find the flag which is responsible for this difference
I will add the fix in next release

**Comment by sijms** [comment]
fixed in v2.7.12
