### ISSUE TITLE
Can't read more than 1 row having a LONG field

### ISSUE THREAD

**Issue by simulot** [sijms/go-ora#42]
Sorry to keep you busy.

I have used 60bc60e for this test.

So I have a table having following structure:
```
Name         Null?    Type           
------------ -------- -------------- 
BUF_ID       NOT NULL NVARCHAR2(20)  
BUF_NAME     NOT NULL NVARCHAR2(100) 
BUF_SETTINGS NOT NULL LONG           
BUF_USE_UID           NVARCHAR2(20)  

```

This table has 28 rows. 

The application uses this field to store some XML structure.

I'm querying the table with ./examples/query/main.go program. I get just one row. 

When looking in trace file, the 1st frame has more than one record, and there is one more frame with the rest of the table.

I think  the issue is here:
https://github.com/sijms/go-ora/blob/60bc60eda48431ec772b8ea8f8ddf2e5a4c5f4a7/data_set.go#L113-L131

The call to Next fetches the 1st record at line 121, but for next calls, nothing is fetched, and Next returns io.EOF

**Comment by simulot** [comment]
I have followed the code.
the number of row in this peculiar frame is 25 as required.
The stmt.Read loop stop right after reading the 1st record, because read msg is 0. Therefore  len(dataSet.Rows) is 1 and Next return EOF.

So I suppose the LONG field causes a shift in the structure reading.

**Comment by sijms** [comment]
I fix the problems
1- it is in GetCLR method and when the buffer start with 0xFE
2- if LONG or LONGROW is null I need to read 2 fixed bytes and then anther integer max width 4

**Comment by sijms** [comment]
also I need to test NULL value in LOB columns 
may be same as issue no 2

**Comment by simulot** [comment]
This fixes my issue.
Thanks.

**Comment by simulot** [comment]
Closed too fast!

You're right. I'm checking with a table having an NVARCHAR2(2000) fields, and I get just one record.

**Comment by sijms** [comment]
good this means this problem no.1 is not universal for all types and I need to check it

**Comment by simulot** [comment]
May be GetCLR was correct, and you have to discard the two 0 only when reading a LONG?

**Comment by sijms** [comment]
now I make the changes the issue no.1 is related only to LONG and LONGROW you need to read 2 WORD integer from the 
stream after reading the data

please test and feedback

**Comment by simulot** [comment]
I have rested with LONG, still working.

I have weird table that contains chunks of XML encoded into NVARCHAR(2000)... So, many records have 2000 chars.

Depending on the query, the order of fields or sort order, i can see either
- the Next loop hangs after reading several records
- the Next exit on an error next paquet isn't data
- No error visible, by the last records is damaged 

I'm working a creating a dataset for this case that is easy to follow, and that doesn't contains company's data.

**Comment by sijms** [comment]
we need data more than 0x100 to test the GetClr function

**Comment by sijms** [comment]
I mix NUMBER, NCHAR, LONG columns in one select
putting large data 1897 byte in NCHAR column in one row and the other rows normal short text and 
 try to get 11 rows all come correctly

**Comment by simulot** [comment]
I haven't neither been able to reproduce the problem that I have with production data. 
So, I propose to close this issue which is attached to a solved problem.

I'll open anther one if I'm able to reproduce the case.
Thanks for your help.
