### ISSUE TITLE
number type but got string

### ISSUE THREAD

**Issue by czwen** [sijms/go-ora#425]
<img width="278" alt="image" src="https://github.com/sijms/go-ora/assets/3235796/de5ee4fc-ff85-4365-8878-9ad01afc74af">

<img width="526" alt="image" src="https://github.com/sijms/go-ora/assets/3235796/c4bea3f9-270c-4502-aa1f-674f1e5cdd01">

all are number type,but convert to string.

does i miss some config or used a worng function?

ps.i don't want create struct for every select.

project is your demo.

thanks

**Comment by UnderMountain96** [comment]
I have the same problem, everything was working yesterday, in the morning I updated **go-ora to v2.7.13** and an error appeared `can not assign string to type: NullFloat64`

**Comment by sijms** [comment]
this issue is older than 2.7.13 actually come from PR
no problem I fix it in next release

**Comment by sijms** [comment]
fixed in v2.7.14
