### ISSUE TITLE
Falsely assuming UDT with null.String args in v2.7.*

### ISSUE THREAD

**Issue by justinosbaldiston** [sijms/go-ora#427]
Similar to [#405](https://github.com/sijms/go-ora/issues/405) and [#293](https://github.com/sijms/go-ora/issues/293)
Both these issues were closed, but the issue still exists

When passing a null.String (from gopkg.in/guregu/null.v4) into the query, it returns the error "call register type before use user defined type (UDT)"
If the null.String is Valid then the query works fine, but when it's not valid (eg the value is NULL) the above error is returned

eg, where :1 is a null.String that is null (valid=false), using SelectContext
``
SELECT * FROM <TABLE> WHERE :1 = <COLUMN>
``
returns "call register type before use user defined type (UDT)"

This code runs fine on v2.6.17, it's erroring on all versions of v2.7 that I've tried, including latest (v2.7.13)

**Comment by sijms** [comment]
fixed in next release

**Comment by sijms** [comment]
fixed in v2.7.14

**Comment by justinosbaldiston** [comment]
Fixed now, thanks
