### ISSUE TITLE
Ability to use SID option instead of SERVICE_NAME

### ISSUE THREAD

**Issue by Mi7teR** [sijms/go-ora#43]
is it possible to add SID option to CONNECT_DATA string instead of SERVICE_NAME [here](https://github.com/sijms/go-ora/blob/60bc60eda48431ec772b8ea8f8ddf2e5a4c5f4a7/network/connect_option.go#L52)?

**Comment by sijms** [comment]
I didn't test but I think it will not work

**Comment by Mi7teR** [comment]
i tested it in https://github.com/Mi7teR/go-ora, replaced your package with my fork in go.mod at my project. Queries to database works fine, but my fork will broke old package api. I think i need to add SID option in connection_string.go and use that option to avoid api brokes. Using [this](https://github.com/sijms/go-ora/blob/200ec6ba20fe0d21d9bf67e8a01b5173d3bde123/connection_string.go#L59) option everywhere as SERVICE_NAME causes confusion, as example i'm expecting to see a variable named SID as SID, not SERVICE_NAME

**Comment by sijms** [comment]
did you get any problems with the original code ?

**Comment by Mi7teR** [comment]
> did you get any problems with the original code ?

 Yeah, i have ORA-12514 error with non-configured for service name support database. And for some reason i have no way to fix that in production.

**Comment by sijms** [comment]
can you make pull request with your changes

**Comment by sijms** [comment]
I leave the connection string as describe in documentation
`conn, err := sql.Open("oracle", "oracle://user:pass@server/service_name")`
and I add option to specify SID as follow
`conn, err := sql.Open("oracle", "oracle://user:pass@server/service_name?SID=TEMP`
the connection option will use SID instead of service name

**Comment by Mi7teR** [comment]
thakn you!
