### ISSUE TITLE
Problemas al usar map con named en sqlx

### ISSUE THREAD

**Issue by rafael180496** [sijms/go-ora#44]
Al usar sqlx que es una extension del paque database/sql https://github.com/jmoiron/sqlx este tiene problemas al usar map como argumentos y no captura correctamente los string largos o clob de oracle

**Comment by sijms** [comment]
can you give example to produce same error

**Comment by rafael180496** [comment]
Al usar el sqlx.named con referencia a la librería go-ora este tiene un problema el ejecuta bien pero al obtener los rows da problemas

**Comment by rafael180496** [comment]
https://github.com/rafael180496/libcore/blob/v1.6.3/database/conect.go

**Comment by rafael180496** [comment]
`func (p *StConect) NamedIn(query StQuery) (string, []interface{}, error) {
	var (
		sqltemp string
		args    []interface{}
		err     error
	)
	sqltemp, args, err = sqlx.Named(query.Querie, query.Args)
	if err != nil {
		return "", nil, err
	}
	sqltemp, args, err = sqlx.In(sqltemp, args...)
	if err != nil {
		return "", nil, err
	}
	sqltemp = p.DBGO.Rebind(sqltemp)

	return sqltemp, args, err
}`

**Comment by rafael180496** [comment]
func (p *StConect) QueryRows(query StQuery, indConect bool) (*sqlx.Rows, error) {
	var (
		err     error
		filas   *sqlx.Rows
		sqltemp string
		args    []interface{}
	)
	err = p.Con()
	if err != nil {
		return filas, err
	}
	sqltemp, args, err = p.NamedIn(query)
	if err != nil {
		return filas, err
	}
	filas, err = p.DBGO.Queryx(sqltemp, args...)
	if err != nil {
		p.Close()
		return filas, err
	}
	if !indConect {
		p.Close()
	}
	return filas, nil
}

**Comment by rafael180496** [comment]
En estas dos funciones lo que son los tipo clob me da el problema  o varchar2 largos

**Comment by sijms** [comment]
I just finish add support for BLOB since 2 days ago and I think CLOB is same but I need to test it before releasing

**Comment by sijms** [comment]
if I not wrong your problem is CLOB but what about other types
did you get any error?

**Comment by rafael180496** [comment]
Solamente para esos tipo ya que el slq tiene varias filas pero al ver este tipo de datos solo un dato saca y lo saca mal con ros.next del sqlx

**Comment by rafael180496** [comment]
Está muy buena la librería por q no ocupa el oci8.pc y por eso lo quería migrar de ranav4

**Comment by sijms** [comment]
I will add support for CLOB with in one or 2 days

**Comment by rafael180496** [comment]
Muchísimas gracias enserio 😁

**Comment by sijms** [comment]
I make update test and feedback

**Comment by rafael180496** [comment]
ya funciono muchas gracias enserio
