### ISSUE TITLE
Time not in timezone

### ISSUE THREAD

**Issue by m1k1o** [sijms/go-ora#447]
I have been using this driver for months. But with this recent change https://github.com/sijms/go-ora/commit/c43a92b1032b9c151c4ef5b1b9c3ca0b2e9ec8fc timezone is off. It looks like oracle returns datetime in UTC and timezone, but this driver treats it as if that returned datetime was already in the specified timezone. I am using `DATE WITH TIMEZONE` field.

So I tried to migrate to **godror** and there it works fine. Removing `timeInZone = true` when `zone == nil` fixes my issue.

I think that this is a bug on this driver because I verified with the other and there it works.

**Comment by sijms** [comment]
would you please give an example code to produce the error

**Comment by m1k1o** [comment]
I tried with Oracle 12 and the new flow actually works. But with Oracle 19 it returns the right zone, but the wrong time.

**Comment by vivi-ui** [comment]
use: TIMESTAMP WITH LOCAL TIME ZONE   is ok

**Comment by m1k1o** [comment]
@vivi-ui no change, still wrong time even with `TIMESTAMP WITH LOCAL TIME ZONE` and still correct with godror.

**Comment by sijms** [comment]
sorry for late replay
I fix it in next release 
you can test it 
go.mod
`require github.com/sijms/go-ora/v2 v2.7.20-0.20231110222249-d97857c0676a`

**Comment by sijms** [comment]
fixed in v2.7.20
