### ISSUE TITLE
Is there a way to init session parameters always whenever connection created

### ISSUE THREAD

**Issue by freeNestor** [sijms/go-ora#457]
I want to init session parameters like ' ALTER SESSION SET key=value' and keep this when connection pool reconnect, so is there a way to achieve this? I known use db.Exec() can execute this sql, but if pool reconnect, this will reset session.

**Comment by freeNestor** [comment]
> What parameter are you trying to set? Is it already an option in the connect string?
> 

I want to set events and cursor_sharing etc.
Example:
ALTER SESSION SET EVENTS '10503 trace name context forever, level 4000'
ALTER SESSION SET cursor_sharing=force

**Comment by sijms** [comment]
sorry for late replay
ok good idea I will add it in next release

**Comment by freeNestor** [comment]
Thanks very much, I'll wait for it.

**Comment by sijms** [comment]
fixed in v2.7.20
