### ISSUE TITLE
Error from leading comments in SQL statement

### ISSUE THREAD

**Issue by ngmaloney** [sijms/go-ora#46]
During the course of migrating from godror to go-ora we encountered a minor regression. Our application reads SQL queries from a text file. The queries are rather complex and often contain documentation related comments. If the first line of the query is a comment, we are getting an error, if a comment is anywhere else in the file it parses and executes. We did not experience this behavior with godror. I tried looking at the code for godror to see if they handle query parsing differently but haven't had much luck. 

Ex: This query works
```
SELECT *
FROM USERS
/* comment here */
WHERE id = 1
```

This does not work

```
/* This query begins with a comment */
SELECT *
FROM USERS
WHERE id = 1
```

**Comment by sijms** [comment]
the problem is in this code 
```
if strings.HasPrefix(uCmdText, "SELECT") || strings.HasPrefix(uCmdText, "WITH") {
	ret.stmtType = SELECT
} else if strings.HasPrefix(uCmdText, "UPDATE") ||
	strings.HasPrefix(uCmdText, "INSERT") ||
	strings.HasPrefix(uCmdText, "DELETE") {
	ret.stmtType = DML
} else if strings.HasPrefix(uCmdText, "DECLARE") || strings.HasPrefix(uCmdText, "BEGIN") {
	ret.stmtType = PLSQL
} else {
	ret.stmtType = OTHERS
}
```
i need to know the type of the SQL to send to oracle the correct type
so simply i just test the first word to define the type

**Comment by ngmaloney** [comment]
@sijms Thank you for sharing this code snipped. If it is ok with you, may I close this out and attempt to create a PR?

**Comment by sijms** [comment]
no problem at all
