### ISSUE TITLE
Running the same SQL is normal on Oracle11g(11.2.0.X), but it always panic on Oracle10g(10.2.0.X)

### ISSUE THREAD

**Issue by nh-live** [sijms/go-ora#462]
SQL:

SELECT
	TMP_TBS.TABLESPACE_NAME,
	SUM( TMP_TBS.TOTAL_MB ) TOTAL_MB,
	nvl ( SUM( USED_TOT.USED_MB ), 0 ) USED_MB,
	TO_CHAR ( nvl ( SUM( USED_TOT.USED_MB ) / SUM( TMP_TBS.TOTAL_MB ) * 100, 0 ), '999.99' ) USED_PERSENT 
FROM
	( SELECT TABLESPACE_NAME, SUM( BYTES ) / 1024 / 1024 TOTAL_MB FROM DBA_TEMP_FILES GROUP BY TABLESPACE_NAME ) TMP_TBS,(
	SELECT
		TMP_USED.TABLESPACE,
		SUM( TMP_USED.BLOCKS * PARA.DB_BLOCK_SIZE ) / 1024 / 1024 USED_MB 
	FROM
		V$SORT_USAGE TMP_USED,
		( SELECT VALUE DB_BLOCK_SIZE FROM V$PARAMETER WHERE NAME = 'db_block_size' ) PARA 
	GROUP BY
		TMP_USED.TABLESPACE 
	) USED_TOT 
WHERE
	TMP_TBS.TABLESPACE_NAME = USED_TOT.TABLESPACE (+) 
GROUP BY
	TMP_TBS.TABLESPACE_NAME

Panic info:

2023/11/16 14:43:53.669 [C] [panic.go:884]  Handler crashed with error runtime error: slice bounds out of range [-17:]
2023/11/16 14:43:53.669 [C] [panic.go:884]  /usr/local/go/src/runtime/panic.go:884
2023/11/16 14:43:53.669 [C] [panic.go:884]  /usr/local/go/src/runtime/panic.go:153
2023/11/16 14:43:53.669 [C] [panic.go:884]  /go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.19/network/session.go:1280
2023/11/16 14:43:53.669 [C] [panic.go:884]  /go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.19/network/session.go:1296
2023/11/16 14:43:53.669 [C] [panic.go:884]  /go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.19/network/session.go:1401
2023/11/16 14:43:53.669 [C] [panic.go:884]  /go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.19/network/summary_object.go:156
2023/11/16 14:43:53.669 [C] [panic.go:884]  /go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.19/connection.go:1165
2023/11/16 14:43:53.669 [C] [panic.go:884]  /go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.19/command.go:992
2023/11/16 14:43:53.669 [C] [panic.go:884]  /go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.19/command.go:2417
2023/11/16 14:43:53.669 [C] [panic.go:884]  /go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.19/command.go:2326
2023/11/16 14:43:53.669 [C] [panic.go:884]  /go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.19/command.go:2393
2023/11/16 14:43:53.669 [C] [panic.go:884]  /go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.19/connection.go:1142
2023/11/16 14:43:53.669 [C] [panic.go:884]  /usr/local/go/src/database/sql/ctxutil.go:48
2023/11/16 14:43:53.669 [C] [panic.go:884]  /usr/local/go/src/database/sql/sql.go:1748
2023/11/16 14:43:53.669 [C] [panic.go:884]  /usr/local/go/src/database/sql/sql.go:3405
2023/11/16 14:43:53.669 [C] [panic.go:884]  /usr/local/go/src/database/sql/sql.go:1743
2023/11/16 14:43:53.669 [C] [panic.go:884]  /usr/local/go/src/database/sql/sql.go:1726
2023/11/16 14:43:53.669 [C] [panic.go:884]  /usr/local/go/src/database/sql/sql.go:1704
2023/11/16 14:43:53.669 [C] [panic.go:884]  /usr/local/go/src/database/sql/sql.go:1538
2023/11/16 14:43:53.669 [C] [panic.go:884]  /usr/local/go/src/database/sql/sql.go:1703

**Comment by sijms** [comment]
fixed in v2.7.22
