### ISSUE TITLE
BLOB limited to 32kB

### ISSUE THREAD

**Issue by maxsterlog** [sijms/go-ora#471]
When retrieving a BLOB, the BLOB (`blob.Data`) retrieved is a maximum of 32kB, even though the BLOB in the database is significantly larger.

```go
var blob go_ora.Blob
err = db.QueryRow("SELECT BLOBFIELD FROM TABLE WHERE ID = :id", sql.Named("id", id)).Scan(&blob)
```

**Comment by sijms** [comment]
use url option `lob fetch=post`

**Comment by rondales** [comment]
> When retrieving a BLOB, the BLOB (`blob.Data`) retrieved is a maximum of 32kB, even though the BLOB in the database is significantly larger.
> 
> ```go
> var blob go_ora.Blob
> err = db.QueryRow("SELECT BLOBFIELD FROM TABLE WHERE ID = :id", sql.Named("id", id)).Scan(&blob)
> ```

**Comment by sijms** [comment]
use `lob fetch=post` in urlOptions
