### ISSUE TITLE
Regression since v2.7.23 when using DBMS_AQ.DEQUEUE_ARRAY

### ISSUE THREAD

**Issue by robstradling** [sijms/go-ora#482]
My application code that calls DBMS_AQ.DEQUEUE_ARRAY works OK with v2.7.22 and earlier, but since v2.7.23 the following error occurs:

`ORA-06502: PL/SQL: numeric or value error`

https://gist.github.com/robstradling/7046c09dbd173756ce9c6e642c2b2050 demonstrates this regression.

**Comment by sijms** [comment]
fixed v2.8.0

**Comment by robstradling** [comment]
Thanks @sijms !
