### ISSUE TITLE
v2.7.25 now requires Go v1.21?

### ISSUE THREAD

**Issue by btnguyen2k** [sijms/go-ora#484]
After v2.7.25, our test failed with the following error:
`./go/pkg/mod/github.com/sijms/go-ora/v2@v2.7.25/connection.go:101:19: undefined: atomic.Bool`

Our Go v1.18.x was running ok with sijms/go-ora/v2 pre v2.7.25
And the current `go.mod` of `sijms/go-ora/v2` says `go 1.17`.
We tested again with Go v1.21.x and the error message was gone.

Is this unintended bump of Go version?

**Comment by sijms** [comment]
I should change go version in go.mod

**Comment by sijms** [comment]
I review the code and no need for atomic package as the field is not sharable
so I change it to bool

**Comment by sijms** [comment]
return back to bool v2.8.0
