### ISSUE TITLE
v2.8.2 ORA-01756: 撘訫噡??摮㛖泵銝脫瓷?㗇迤蝖桃???

### ISSUE THREAD

**Issue by iTanken** [sijms/go-ora#488]
### env

- "LANGUAGE":           "SIMPLIFIED CHINESE",
- "TERRITORY":          "CHINA",

```sql
COMMENT ON TABLE "sys_user" IS N'系统用户信息表'
```

### error:

> ORA-01756: 撘訫噡??摮㛖泵銝脫瓷?㗇迤蝖桃???

v2.8.1 no error reported.

**Comment by sijms** [comment]
fixed in v2.8.3

**Comment by iTanken** [comment]
> fixed in v2.8.3

Okay, thank you very much.

Closes #488
