### ISSUE TITLE
go-ora is slow

### ISSUE THREAD

**Issue by rongfengliang** [sijms/go-ora#49]
i do some test with godror && go-ora current  go-ora  is too slow ,has  any idea for performance

links https://github.com/rongfengliang/oracledb_exporter/tree/v1.0.1

**Comment by sijms** [comment]
actually i didn't test the performance against other libraries
my first goal is to make oracle driver with pure golang no dependency on other c library, no complicated setup process 

but to get benefit of your work can you determine which step is slow either connection or statement execution

**Comment by rongfengliang** [comment]
i do some test (flamegraph)
links : https://github.com/rongfengliang/go-ora-godror

**Comment by sijms** [comment]
if the problem in the connect function it is ok because I don't implement connection pooling and other advanced feature that used by other drivers
but query execution is a matter of network if you can review the network panel of go-ora and other driver it is almost same.

**Comment by rongfengliang** [comment]
> if the problem in the connect function it is ok because I don't implement connection pooling and other advanced feature that used by other drivers
> but query execution is a matter of network if you can review the network panel of go-ora and other driver it is almost same.
> 
> I don't think data manipulation will show significant difference speed between C and GO
> 
> sorry I cannot understand the graph 
> but I see the QueryContext in go-ora 0.26 sec and in godror 0.46 sec means double time (if I am not wrong)

thanks for create this package, i do test with diffrent time maybr caused querycontext with double time ,i think the reason cause go-ora slow was bytes create with buffers maybe better

**Comment by sijms** [comment]
I will upgrade the code and use buffers instead of bytes to improve performance
