### ISSUE TITLE
Certain fields are not retreived (returned as null)

### ISSUE THREAD

**Issue by fleshin** [sijms/go-ora#5]
Hi,
I was able to see a lot of progress after fixing the previous issue. Most of the data is properly retrieved, but in certain cases NULL is retrieved instead. No error is reported by the Scan function.

I am still trying to narrow down the cases and find possible patterns.
One case that appears consistent is when on a VARCHAR2(128 byte) field there is a dash (-) or underscore (_) 

The second case is more mysterious, it is a NUMBER column, with all the rows containing a number 1. 
The firs half (aprox) is properly retrieved, but the other is presented as null. I couldn't find yet any difference between the two groups.

Anyway, in general the module compiles and behaves quite fast. Not needing to carry around a bunch of libraries is another big plus. Hope this one can be solved as well :)

Thanks!

**Comment by fleshin** [comment]
I just traced with wireshark a simple query on a single column with 1300 rows.  I am only able to retrieve the first 3 rows.
Wireshark shows following error as the last server response
    ORA-03137: TTC protocol internal error : [12209] [0] [] [] [] [] [] []

**Comment by sijms** [comment]
I am working on it now and fixing many bugs and solution is soon

**Comment by fleshin** [comment]
Awesome!!! 👍 🥇

**Comment by sijms** [comment]
I find the problem:
the problem happened after first fetch because I use something as circular buffer to store row during read process 
last row is changed after fetch thus I need to save last row before call fetch to use it to fill repeated values in rows

please try and tell me

**Comment by fleshin** [comment]
This is absolutely awesome... I am getting exactly the same results than the official client but a bit faster! 
Compiles in a fraction of the time and to a single binary file.... you are the man! 💯
