### ISSUE TITLE
Error retrieving rows having a CLOB field

### ISSUE THREAD

**Issue by thejosk** [sijms/go-ora#50]
I have used [40e04fc](https://github.com/sijms/go-ora/tree/40e04fc02df4646b70b4e8fbe7e286f495532c85) for testing this issue. We have a table with one of the fields being a CLOB type. When I query the table with a select statement, 0 rows are returned.

**Comment by sijms** [comment]
can you please load last update of the driver and test
because actually this is old issue and I solve and CLOB is returned correctly
