### ISSUE TITLE
No data from table with TO_DATE(SYSDATE,'dd.mm.yyyy')

### ISSUE THREAD

**Issue by IrwinJuice** [sijms/go-ora#501]
Hi,

I get no data from table with query below

`"select name from snavigation where idgr=1 and parent is null and date_b<=TO_DATE(SYSDATE,'dd.mm.yyyy')"`

```
 query := "select name from snavigation where idgr=1 and parent is null and date_b<=TO_DATE(SYSDATE,'dd.mm.yyyy')"
 rows, err := h.DB.Query(query)
	if err != nil {
		log.Println("ERROR: ", err)
		return c.JSON(500, err)
	}
	var names []string

	for rows.Next() {

		var name string
		if err := rows.Scan(&name); err != nil {
			log.Fatal("ERR: ", err)
		}
		names = append(names, name)
	}
```
rows.Next() returns false, but this is valid oracle sql, because Pl/SQL Developer execute it properly and return data from table.

When I remove  date_b<=TO_DATE(SYSDATE,'dd.mm.yyyy') I can get data from table.

 What am I doing wrong? Or this is issue with driver?

Thanks in advance

**Comment by sijms** [comment]
the sql is valid and no error happen just no data return. so it is likely related to data
would you please give example table with some data to test

**Comment by IrwinJuice** [comment]
Oracle version Oracle Database 19c Enterprise Edition Release 19.0.0.0.0


```
create table SNAV
(
    IDNAV       NUMBER                     not null
        constraint PK_SNAV
            primary key,
    IDGR        NUMBER                     not null,
    NAME        VARCHAR2(120 char),
    DATE_B      DATE       default SYSDATE not null,
    PARENT      NUMBER
        constraint FK_SNAV_SELF
            references SNAV
                on delete cascade
)



insert into snav (idnav, idgr, name, date_b) values (7782,1, 'A012 Якесь значення 1', '24.08.1991');
insert into snav (idnav, idgr, name, date_b) values (1191,1, 'A02 Якесь значення 2', '24.08.1991');
insert into snav (idnav, idgr, name, date_b) values (8080,1, 'A03 Якесь значення 3', '24.08.1991');
insert into snav (idnav, idgr, name, date_b) values (5400,1, 'A04 Якесь значення 4', '24.08.1991');


select * from snav where idgr=1 and parent is null and date_b<=TO_DATE(SYSDATE,'dd.mm.yyyy');
```

Attached few screenshots from PL/Sql Developer and from Goland debug

![PL_SQL](https://github.com/sijms/go-ora/assets/17815703/e343ec12-4ed3-4ebf-9bf7-41f1dcc99d4c)
![select_without_TO_DATE](https://github.com/sijms/go-ora/assets/17815703/b94bbdbf-eed2-4c7a-acb9-41baf7760874)
![select_with_TO_DATE](https://github.com/sijms/go-ora/assets/17815703/521f0cea-5a93-419e-b7b5-01cdb0b7216f)

**Comment by sijms** [comment]
why you are not using sql like this
`SELECT name from snav WHERE idgr=1 and parent is null and date_b < sysdate`
you are comparing dates so no need to use to_date function

**Comment by sijms** [comment]
also you can confirm by see the default format of sysdate in 2 driver 
```sql
select sysdate from dual
```
which will be different

**Comment by IrwinJuice** [comment]
Thank you!  My fault, now I understand how to_date works. All work correctly with first parameter as string like 'TO_DATE('24.08.1991', 'dd.mm.yyyy' ). Sorry for your time
