### ISSUE TITLE
Regression since v2.8.7 for simple SELECTs into integer and floating point variables

### ISSUE THREAD

**Issue by robstradling** [sijms/go-ora#512]
My application code that SELECTs integer or floating point values into corresponding Go variables works OK with v2.8.6 and earlier, but since v2.8.7 I see errors of the following form:

`can't assign value: <value> to object of type: <type>`

https://gist.github.com/robstradling/93d461f916c37e17a724e54d78942fbc demonstrates this regression.  (Compare the [output when using v2.8.6](https://gist.github.com/robstradling/93d461f916c37e17a724e54d78942fbc#file-output_v2-8-6-txt) to the [output when using v2.8.7](https://gist.github.com/robstradling/93d461f916c37e17a724e54d78942fbc#file-output_v2-8-7-txt)).

**Comment by sijms** [comment]
fixed in v2.8.9
