### ISSUE TITLE
Connection Timeouts since 2.8.8

### ISSUE THREAD

**Issue by Tommi2Day** [sijms/go-ora#513]
updated from 2.8.7 to 2.8.8 and my unit tests are terminating now with new errors:
-  connection break due to context timeout
sample code
`
dbh, err = sqlx.Open(driver, source)
	if err != nil {
		return nil, err
	}

	// Create a context with timeout, using the empty
	// context.Background() as the parent.
	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(timeout)*time.Second)
	defer cancel()

	// Use this when testing the connection pool.
	if err = dbh.PingContext(ctx); err != nil {
		// error occours here
		return nil, err
	}
`

source = 'oracle://dummy:dummy@:0/?connStr=%28DESCRIPTION%3D%28ADDRESS_LIST%3D%28ADDRESS%3D%28PROTOCOL%3DTCP%29%28HOST%3D127.0.0.1%29%28PORT%3D21522%29%29%29%28CONNECT_DATA%3D%28SERVER%3DDEDICATED%29%28SERVICE_NAME%3DFREEPDB1%29%29%29'

- within select with real login: : ORA-01013: User requested cancel of current operation

Tested with Oracle23.3 Free. Timeout is set to 10 (sec)
I can confirm the same code is working with 2.8.7

**Comment by sijms** [comment]
fixed in v2.8.9

**Comment by sijms** [comment]
fixed in next release
