### ISSUE TITLE
Fail to set Session Parameter Container fails with ORA-65015: missing or invalid container name

### ISSUE THREAD

**Issue by nchillal** [sijms/go-ora#514]
I am trying to set container using "AddSessionParam" and it fails with message below 

> ORA-65015: missing or invalid container name

"AddSessionParam" code is using single quotes around the [value](https://github.com/sijms/go-ora/blob/v2.8.7/v2/driver.go#L99) but for containers this doesn't work. 

```
SQL> alter session set CONTAINER='PDBTEST';
alter session set CONTAINER='PDB10'
                            *
ERROR at line 1:
ORA-65015: missing or invalid container name
```

This works 

```
SQL> alter session set CONTAINER=PDBTEST;

Session altered.
```

Can you please provide a fix for this?

**Comment by sijms** [comment]
which version are you using?
