### ISSUE TITLE
Regression (part #2) since v2.8.7 for simple SELECTs into integer and floating point variables

### ISSUE THREAD

**Issue by robstradling** [sijms/go-ora#515]
Hi @sijms.  My regression demo in #512 shows that that problem was only [partially fixed in v2.8.9](https://gist.github.com/robstradling/93d461f916c37e17a724e54d78942fbc#file-output_v2-8-9-txt).

The `can't assign value` error has gone, but now I'm seeing `unsupported primitive type` for `int`, `int64`, `float32`, and `float64`.  This appears to be because, for any positive integer value returned from a SELECT query, `input.(type)` in the switch statement at https://github.com/sijms/go-ora/blob/master/v2/utils.go#L589 evaluates to `uint64`, which is handled by the default case.

**Comment by sijms** [comment]
I add changes in last commit
would you please test and give me feedback

**Comment by robstradling** [comment]
Thanks @sijms.  Commit https://github.com/sijms/go-ora/commit/b04862ca3078dc46907e4e8a566507bd505af880 fixes my regression demo and looks good to me.  Time for a v2.8.10 release?
