### ISSUE TITLE
crash on stmt.Close()

### ISSUE THREAD

**Issue by hoantv** [sijms/go-ora#52]
i deployed my program on both 12c and 11g, the program crash  or has error when connecting to oracle db.
check on log oracle:

1. case crash:
log on Oracle
```
2020-12-10T23:44:12.599539+07:00
Session (3594,30260): Bad TTC Packet Detected: Inbound connection from client
Session (3594,30260): Bad TTC Packet Detected: DB Logon User: admin, Remote Machine: dboracle , Program: plugin-oracle, OS User: root
Session (3594,30260): Bad TTC Packet Detected: Could not find Client IP Address 
AOM_10/12/2020 23:46:57_7495252196
2020-12-10T23:47:12.500474+07:00
Errors in file /u01/app/oracle/diag/rdbms/cdb/cdb1/trace/cdb1_s000_67521.trc  (incident=462390) (PDBNAME=CDB$ROOT):
ORA-03137: malformed TTC packet from client rejected: [12209] [0] [] [] [] [] [] []
```
2. Case not crash
log oracle
Dumping diagnostic data in directory=[cdmp_20201210141311], requested by (instance=1, osid=90994 (S005)), summary=[incident=1180777].
Thu Dec 10 14:16:11 2020
Dumping diagnostic data in directory=[cdmp_20201210141611], requested by (instance=1, osid=90998 (S007)), summary=[incident=1180793].
Thu Dec 10 14:17:25 2020
Errors in file /u01/app/oracle/diag/rdbms/hddt/HDDT2/trace/HDDT2_s013_105611.trc  (incident=1692458):
ORA-03137: TTC protocol internal error : [12209] [0] [] [] [] [] [] []
Incident details in: /u01/app/oracle/diag/rdbms/hddt/HDDT2/incident/incdir_1692458/HDDT2_s013_105611_i1692458.trc
Thu Dec 10 14:17:33 2020
Errors in file /u01/app/oracle/diag/rdbms/hddt/HDDT2/trace/HDDT2_s001_105583.trc  (incident=1692354):
ORA-03137: TTC protocol internal error : [12209] [0] [] [] [] [] [] []
Incident details in: /u01/app/oracle/diag/rdbms/hddt/HDDT2/incident/incdir_1692354/HDDT2_s001_105583_i1692354.trc
Both case, Oracle DB create too much trace files, and they increased rapidly (several millions trace file within 1 day)

I made a trace on my program:

error start from: rows, err := stmt.Query(nil) 
panic at: session.inBuffer = append(session.inBuffer, dataPck.buffer...)

if dataPck, ok := pck.(*DataPacket); ok {
			session.inBuffer = append(session.inBuffer, dataPck.buffer...)
		} else {
			return nil, errors.New("the packet received is not data packet")
}

```
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin] time="2020-12-11T15:36:42+07:00" level=error msg="========dataPck========= &{{10 241 6 0} 0 ["(Much data i remove)" source="session.go:233"  source="client.go:1022"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin] time="2020-12-11T15:36:42+07:00" level=error msg="========dataPck========= &{{10 2548 6 0} 0 ["(Much data i remove)"" source="session.go:233"  source="client.go:1022"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin] time="2020-12-11T15:36:42+07:00" level=error msg="========dataPck========= &{{10 266 6 0} 0 ["(Much data i remove)"" source="session.go:233"  source="client.go:1022"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin] time="2020-12-11T15:36:43+07:00" level=error msg="========dataPck========= <nil>" source="session.go:233"  source="client.go:1022"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin] time="2020-12-11T15:36:43+07:00" level=error msg="Oracle plugin: cannot close stmt EOF" source="oracle_exporter.go:199"  source="client.go:1022"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin] panic: runtime error: invalid memory address or nil pointer dereference  source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin] [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9779aa]  source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin]                          source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin] goroutine 53 [running]:  source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin] oracle-plugin/vendor/github.com/sijms/go-ora/network.(*Session).read(0xc0003dc000, 0x1, 0xc00035c480, 0x100000020, 0x20, 0xc0004689a0, 0x2)  source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin]  D://Go projects/src/oracle-plugin/vendor/github.com/sijms/go-ora/network/session.go:234 +0x1ea  source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin] oracle-plugin/vendor/github.com/sijms/go-ora/network.(*Session).GetByte(0xc0003dc000, 0x0, 0xc0004689a0, 0xc0004517a0)  source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin]  D://Go projects/src/oracle-plugin/vendor/github.com/sijms/go-ora/network/session.go:641 +0x34  source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin] oracle-plugin/vendor/github.com/sijms/go-ora.(*Stmt).read(0xc000430380, 0xc000258280, 0x0, 0x0)  source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin]  D://Go projects/src/oracle-plugin/vendor/github.com/sijms/go-ora/command.go:409 +0xb5  source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin] oracle-plugin/vendor/github.com/sijms/go-ora.(*Stmt).Query(0xc000430380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)  source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin]  D://Go projects/src/oracle-plugin/vendor/github.com/sijms/go-ora/command.go:1060 +0x3e9  source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin] main.sendCommandGetParams(0xc0003be8c0, 0x0, 0x0, 0x0)  source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin]  D://Go projects/src/oracle-plugin/oracle_exporter.go:202 +0xed  source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin] main.(*oracleCollector).getConfig(0xc000146a40, 0xc00013fa10, 0xc, 0x5f1, 0xc00013fa20, 0x6, 0xc00013a960, 0x13, 0xc00013fa26, 0x3, ...)  source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin]  D://Go projects/src/oracle-plugin/oracle_exporter.go:157 +0x776  source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin] created by main.(*oracleCollector).Update  source="client.go:1024"
ERRO[11 Dec 20 15:36 ICT] [oracle-plugin]  D://Go projects/src/oracle-plugin/oracle_exporter.go:121 +0x24b  source="client.go:1024"
```

After i add  "dataPck != nil" 

		if dataPck, ok := pck.(*DataPacket); ok &&  dataPck != nil {
			session.inBuffer = append(session.inBuffer, dataPck.buffer...)
		} else {
			return nil, errors.New("the packet received is not data packet")
		}
the program still panic at err := rows.Close() 
`ERRO[11 Dec 20 16:13 ICT] [oracle-plugin] time="2020-12-11T16:13:23+07:00" level=error msg="rows is <nil>" source="oracle_exporter.go:207"  source="client.go:1022"`

after handler rows==nil, there are only 2 errors 
```

ERRO[11 Dec 20 16:20 ICT] [oracle-plugin] time="2020-12-11T16:20:53+07:00" level=error msg="Oracle plugin: cannot execute query the packet received is not data packet" source="oracle_exporter.go:204"  source="client.go:1022"
ERRO[11 Dec 20 16:20 ICT] [oracle-plugin] time="2020-12-11T16:20:53+07:00" level=error msg="Oracle plugin: cannot close stmt EOF" source="oracle_exporter.go:199"  source="client.go:1022"
```

**Comment by sijms** [comment]
can you write your complete code please

**Comment by hoantv** [comment]
Ok. I will send you on monday. It is simple.
Connecting to oracle to get parameter.

**Comment by hoantv** [comment]
I want to get parameters of a oracle instance. here is the code

```
url := fmt.Sprintf("oracle://%s:%s@%s:%d/%s", instance.Username, url.QueryEscape(instance.Password), instance.Host, instance.Port, instance.Sid)
conn, err := go_ora.NewConnection(url)
if err != nil {
	log.Errorln("Cannot create new connection to:", moduleCode, err)
	metrics <- prometheus.MustNewConstMetric(c.configMetrics["down"], prometheus.GaugeValue, 1, moduleCode)
	return
}
err = conn.Open()
if err != nil {
	log.Errorln("Oracle plugin cannot connect to instance: ", moduleCode, err)
	metrics <- prometheus.MustNewConstMetric(c.configMetrics["down"], prometheus.GaugeValue, 1, moduleCode)
	return
}
defer func() {
	if err := conn.Close(); err != nil {
		log.Errorln("Oracle plugin: cannot close conn", err)
	}
}()
		
instCfgMap := make(map[string]string)
stmt := go_ora.NewStmt("select name,value from v$parameter", conn)
if stmt == nil {
	return nil,errors.New("Oracle plugin: Stmt is nil")
}
defer func() {
	err := stmt.Close()
	if err != nil {
		log.Errorln("Oracle plugin: cannot close stmt", err)
	}
}()
rows, err := stmt.Query(nil)
if err != nil {
	log.Errorln("Oracle plugin: cannot execute query", err)
	return instCfgMap, err
}
defer func() {
	if rows != nil {
		return
	}
	err := rows.Close()
	if err != nil {
		log.Errorln("Oracle plugin: cannot close rows", err)
	}


}()
results := make(go_ora.Row, 2)
for {
	err = rows.Next(results)
	str := fmt.Sprintf("%v", results)
	resultArray := strings.Split(str, " ")
	instCfgMap[strings.Trim(resultArray[0], "[")] = strings.Trim(resultArray[1], "]")
	if err == io.EOF {
		break
	}
}

**Comment by sijms** [comment]
I think the error is related to bug in oracle 10G
are you test against other oracle version and see if the error exists?

**Comment by hoantv** [comment]
I have problem with many version :(!

**Comment by haivp3010** [comment]
I have this issue, too.
I my case, it's not on stmt.Close(), but rather on a query after the program has been idle for some time, and then the next request would fail because of this nil variable

**Comment by hoantv** [comment]
> 
> 
> I have this issue, too.
> I my case, it's not on stmt.Close(), but rather on a query after the program has been idle for some time, and then the next request would fail because of this nil variable
> 
> Update: It seems to be due to the database server closing the connection. I tried with my local server and no issue. Perhaps we could do some kind of retry & reconnect here?
ORA-03137: TTC protocol internal error : [12209] [0] [] [] [] [] [] [] => when this happens, all connections are closed by oracledb. 
some of oracledb has this problem. I changed to oci-8, this problem doesnt occurs. Hope you can fix this.

**Comment by sijms** [comment]
actually I didn't understand the last message
but what appear for me that you try to call close connection on an already closed one?

**Comment by haivp3010** [comment]
> actually I didn't understand the last message
> but what appear for me that you try to call close connection on an already closed one?

I'm just doing a query and not explicitly calling close.
After some investigation, it seems that what I need to do is set proper connection life time, before Oracle closes the connection itself

**Comment by hoantv** [comment]
> actually I didn't understand the last message
> but what appear for me that you try to call close connection on an already closed one?

Due to connection violent. Oracle closes all conmections. And it closes before i close. This is very dangerous :)!

**Comment by sijms** [comment]
I commit pre-release version 2
can you test again

**Comment by haivp3010** [comment]
I haven't had the time to try v2 yet, but the issue hasn't occurred ever since I updated the library to v1-stable. Not sure if it has actually been fixed or it's only a change in my environment.

**Comment by sijms** [comment]
Ok I will close the issue and if you face any problem just re-open
