### ISSUE TITLE
Driver doesn't support  sys_refcursor parameter

### ISSUE THREAD

**Issue by hadeshunter** [sijms/go-ora#53]
I have an oracle Procedure like, which returns a sys_refcursor:
```ruby
PROCEDURE getTTVT
    (
        o_data OUT sys_refcursor   
    )
    IS
     v_Query varchar2(4000);
    BEGIN
    v_Query :='
       select unit_id, unit_name
       from admin_hcm.unit where unit_id in (41, 42, 43, 44, 45, 56, 57, 59, 60)
    ';
     OPEN o_data FOR v_Query;
END getTTVT;
```
My go function is:
```ruby
// Unit of list
type Unit struct {
	unit_id int64
	unit_name string
}
func ListAllUnits {
        stmt, err := db.oracleDB.Prepare("begin dashboard.getTTVT(); end;")
	if err != nil {
		fmt.Println("Error create statment")
		fmt.Println(err)
		return nil, err
	}
	defer stmt.Close()
	units := []models.Unit{}
	result, err := stmt.Exec(sql.Out{Dest: &units})
	fmt.Println(result)
}
```

```ruby
func main() {
   ListAllUnits()
}
```
When I run command:

> go run main.go

I only get nil
@sijms Can you explain how to call Oracle Store Procedure?

**Comment by sijms** [comment]
go to the code in connection.go and examine function GetNLS()

output parameter is supported when use the package directly as explained in readme file

**Comment by sijms** [comment]
if your problem solved please close the issue

**Comment by hadeshunter** [comment]
> if your problem solved please close the issue

Thank you, I'm trying, I will close after success and confirm.

**Comment by hadeshunter** [comment]
@sijms I'm sorry I lasted, I'm back. I read code in connection.go and examine function GetNLS()
My code now is
      `cmdText := `SET SERVEROUTPUT ON SIZE 1000000
                          DECLARE
                          o_cursor sys_refcursor;
                          BEGIN
                          dashboard.getTTVT(o_cursor);
                          END;`
	stmt := go_ora.NewStmt(cmdText, db.oracleDB)
	stmt.AddParam("o_cursor", "", 1000, go_ora.Output)

	// defer stmt.Close()
	result, err := stmt.Exec(nil)
	if err != nil {
		fmt.Printf("Error execute query: %s\n", err)
		return nil, err
	}
	fmt.Println(result)`

I don't know how to add out put sys_refcursor.
`stmt.AddParam("o_cursor", "", 1000, go_ora.Output)`

When run I receive error
> Error execute query: ORA-00922: missing or invalid option
How to add output of sys_refcursor and how can I add output to units array? 
> // Unit of list
> type Unit struct {
> 	DonviID    int
> 	TenDV      string
> 	DonviChaID int
> 	TenDVQL    string
> }

**Comment by sijms** [comment]
I didn't test ref_cursor only simple binding only

**Comment by hadeshunter** [comment]
> I didn't test ref_cursor before only simple binding only
> I think it need extra option to be added to network to let it working properly

If it just simple query, it's ok but almost all my procedure open sys_refcursor. Do you have a plan to update work with procedure open sys_refcursor now or near future?

**Comment by sijms** [comment]
OK,  no problem i will work on this and when finish i will update and inform you

**Comment by sijms** [comment]
I add support for RefCursor
please read the readme file first and see a simple example I make to explain how to use
download and test and if ok please close the issue

**Comment by hadeshunter** [comment]
`PROCEDURE getTTVT
(
    i_unitID IN    number, 
    o_data  OUT sys_refcursor   
);`

if I have a procedure with input is number  or nvarchar2 and the output is sys_refcursor, my function is:
`cmdText := `BEGIN    
									test.getTTVT(:1, :2); 
							END;`
	stmt := go_ora.NewStmt(cmdText, db.oracleDB)
	stmt.AddParam("1", 41, go_ora.Input)
	stmt.AddRefCursorParam("2")
	defer stmt.Close()

	// Query
	_, err := stmt.Exec(nil)
	if err != nil {
		fmt.Println("Error query")
		return nil, err
	}`

when I run I get a loop forever nonstop. Do I add input AddParam wrong? @sijms

**Comment by sijms** [comment]
```
err = rows.Next(values)
// check for error and if == io.EOF break
if err == io.EOF {
break
}
```
here add check for other errors
```
if err != nil {
    if err == io.EOF {
        break
    }
    fmt.Println(err)
    break
}
```

**Comment by sijms** [comment]
did you get correct output?

**Comment by hadeshunter** [comment]
Yes, my procedure return two column which are unitID number and unitName nvarchar2. If there only output sys_refcursor without any input condition then it work well and return correct output.

But when I add condition input such as i_unitID IN number then it just run. I think there is issue in the line

> stmt.AddParam("1", 41, 100, go_ora.Input)

When change code check error to 

```
if err != nil {
    if err == io.EOF {
        break
    }
    fmt.Println(err)
    break
}
```

There is nothing happen. It just run forever.

**Comment by sijms** [comment]
I make modification that solve the problem
please test and inform me about the result
