### ISSUE TITLE
ORA-00911: invalid character

### ISSUE THREAD

**Issue by developless** [sijms/go-ora#534]
var rows *sql.Rows
        // here will cause ORA-00911: invalid character. but the query can success exec at sqlplus.
	if rows, err = c.DB.QueryContext(ctx, "SELECT COLUMN_NAME, DATA_TYPE FROM USER_TAB_COLUMNS WHERE TABLE_NAME=?", in.TableName); err != nil {
		return
	}
	defer func() {
		_ = rows.Close()
	}()

	var columns = make([]*pb.Column, 0)
	for rows.Next() {
		var columnName, dataType string
		if err := rows.Scan(&columnName, &dataType); err != nil {
			return nil, err
		}
		columns = append(columns, &pb.Column{
			Name:     columnName,
			DataType: dataType,
		})
	}

**Comment by sijms** [comment]
Hi @developless oracle not using `?` as placeholder for parameter use `:par_name`
