### ISSUE TITLE
An EOF error is reported during ping

### ISSUE THREAD

**Issue by yudelin6014** [sijms/go-ora#537]
code :

        if ci.Args == nil {
		ci.Args = utils.JsonMap{}
	}
        connUrl := go_ora.BuildUrl(ci.Host, ci.Port, ci.ServiceName, ci.UserName, ci.PassWord, ci.Args.ToMapString())
	db, err = sql.Open("oracle", connUrl)
	if err != nil {
		err = fmt.Errorf("连接:%s,连接数据库错误:%s", ci.GetUniqueId(), err)
		return
	}
        db.SetConnMaxIdleTime(time.Second * 10)
	db.SetMaxIdleConns(5)
	db.SetMaxOpenConns(5)
	//db.SetConnMaxLifetime(time.Second*10)
	err = ci.pingWithTimeout(db)
        return err

--------
return err is EOF

**Comment by sijms** [comment]
if the connection use SSL you should specify wallet location + SSL = true

**Comment by sijms** [comment]
would you please give me more information or close the issue
