### ISSUE TITLE
Parser Error?

### ISSUE THREAD

**Issue by FrankIT60** [sijms/go-ora#55]
SQL stmt that doesn't return record.

This does not work

```
var sqlStmt = `
SELECT 
   ID_RECORD,
   DESCRIPTION,
   DEBUG_
from DEVELOPERS.MVTEST
`
```
This work

```
var sqlStmt = `SELECT ID_RECORD, DESCRIPTION, DEBUG_ from DEVELOPERS.MVTEST`
```
There is a parser problem ?

By

**Comment by sijms** [comment]
do you use the last update of the driver?

**Comment by FrankIT60** [comment]
I updated on January 5th

2021-01-14 10:04 GMT+01:00, Samy Sultan <notifications@github.com>:

**Comment by sijms** [comment]
this is my result
![code-1](https://user-images.githubusercontent.com/9641938/104776051-1aaf6780-5782-11eb-953e-e5d3e15e5d83.png)

**Comment by FrankIT60** [comment]
can you try 


```
stmt, err := conn.Prepare(`
SELECT
   ITEM_NO,
   ITEM_NAME,
   ITEM_CODE
FROM STK_ITEM_DATA`)
defer stmt.Close
....
```

**Comment by sijms** [comment]
same result

**Comment by sijms** [comment]
try to make after item_code and before FROM and see
