### ISSUE TITLE
Use struct with Select many rows query

### ISSUE THREAD

**Issue by dipeshhkc** [sijms/go-ora#551]
Hi. Thank you for this library. 

I am using struct with tag for `BEGIN SELECT id,name INTO :id,:name FROM store WHERE id:id; end` and using `ExecContext` command.
This is working fine.
```
type storeArg struct{
   Id string `db:"name=id,size=50,dir=inout"`
   Name string `db:"name=name,size=50,dir=out`
}
```

How can I use `struct` if the SELECT is returning multiple rows? LIKE
Getting all stores; `SELECT id,name FROM store`

**Comment by sijms** [comment]
database/sql doesn't support this feature
so you should try it using package directly
```golang
conn, err := go_ora.NewConnection(den)
err = conn.Open()
rows, err := conn.QueryContext(,,,)
defer rows.Close()
.
.
.
```

**Comment by dipeshhkc** [comment]
Does go_ora `QueryContext` support struct argument? Do you have an example implementation?

**Comment by sijms** [comment]
you should cast `driver.Rows` to `*DataSet` or see  [examples/query_to_struct](https://github.com/sijms/go-ora/blob/master/examples/query_to_struct/main.go)
