### ISSUE TITLE
there is a bug when data type is OCIClobLocator

### ISSUE THREAD

**Issue by skyterra** [sijms/go-ora#56]
command.go 6

if dataSize != int64(len(lobData)) {
    return errors.New("error reading lob data")
}

**Comment by sijms** [comment]
can you please explain why  bug?

**Comment by luxiaotong** [comment]
I have met the same problem.
The key difference between blob and clob is that CLOB is stored in multibyte.
So len(lobData) get the length of data bytes but dataSize is the length of characters.
if type is OCIClobLocator, the if statement should be:
`if dataSize*2 != int64(len(lobData)) {`

**Comment by sijms** [comment]
actually I do many test with different text and ```dataSize == int64(len(lobData))``` 
because what returned here is bytes not character. the character conversion is occur in next step
```
        if dataSet.Cols[x].DataType == OCIBlobLocator {
		dataSet.currentRow[x] = lobData
	} else {
		if stmt.connection.strConv.LangID != dataSet.Cols[x].CharsetID {
			tempCharset := stmt.connection.strConv.LangID
			stmt.connection.strConv.LangID = dataSet.Cols[x].CharsetID
			dataSet.currentRow[x] = stmt.connection.strConv.Decode(lobData)
			stmt.connection.strConv.LangID = tempCharset
		} else {
			dataSet.currentRow[x] = stmt.connection.strConv.Decode(lobData)
		}
	}
```

**Comment by sijms** [comment]
note if you are using Chinese charset please return to the following issue #13

**Comment by luxiaotong** [comment]
Maybe we could ignore the character conversion first.
I got this error even if the test text is "test clob".
In my environment, NLS_CHARACTERSET is AL32UTF8.
Is anything wrong with this setting?

**Comment by sijms** [comment]
ok this means if depend on database charset because my charset is one byte charset

can you tell me your oracle server version

**Comment by luxiaotong** [comment]
12.2.0.1.0

**Comment by sijms** [comment]
I make a comment that test the dataSize against the length of the string instead of length of the byte data

please test and comment

**Comment by luxiaotong** [comment]
Still not work in my test for data "test clob" with charset AL32UTF8.

**Comment by sijms** [comment]
can you explain the error comming

**Comment by luxiaotong** [comment]
The error messsage is "error reading clob data"
database charset: AL32UTF8
data in table: "test clob"
dataSize return 9
int64(len([]rune(resultClobString))) return 18
fmt.Printf("data: %#v\n", []byte(resultClobString)) output:
[]byte{0x0, 0x74, 0x0, 0x65, 0x0, 0x73, 0x0, 0x74, 0x0, 0x20, 0x0, 0x63, 0x0, 0x6c, 0x0, 0x6f, 0x0, 0x62}

**Comment by sijms** [comment]
I think it is now solved 
you can check it 

thank you for helping in solve this issue

**Comment by luxiaotong** [comment]
Yes, the problem is solved.
I have tested it with Chinese characters both in AL32UTF8 & ZHS16GBK database charset.
Both of them can be read correctly.
Appreciate your excellent work.

**Comment by sijms** [comment]
Hi luxiaotong
I add support for more charset including 852 (zhs16gbk) you can test and feedback

**Comment by luxiaotong** [comment]
> Hi luxiaotong
> I add support for more charset including 852 (zhs16gbk) you can test and feedback

clob & nclob can be read correctly in charset zhs16gbk.
