### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by qiwentaidi** [sijms/go-ora#566]
<img width="771" alt="image" src="https://github.com/sijms/go-ora/assets/104491549/304765b7-2d63-44c3-ba6d-637fe2b4732f">
<img width="995" alt="image" src="https://github.com/sijms/go-ora/assets/104491549/a7696cdb-62a2-4b22-a829-14daead22064">
Need to increase length judgment
<img width="950" alt="image" src="https://github.com/sijms/go-ora/assets/104491549/a1857e00-88c9-4460-afab-a1ac89e09006">

**Comment by sijms** [comment]
sorry for late replay and thanks for contribution 
I update the code
