### ISSUE TITLE
ORA-03137 Bad TTC Packet

### ISSUE THREAD

**Issue by BZValoche** [sijms/go-ora#57]
Hi,
Oracle logs an error in the alert_SID.log upon 1st request or ping, subsequent requests or pings do not trigger another alert.

```
2021-01-25T17:27:35.456074+01:00
Session (65,29529): Bad TTC Packet Detected: Inbound connection from client
Session (65,29529): Bad TTC Packet Detected: DB Logon User: XXXXXX, Remote Machine: XXXXXXXX, Program: testme, OS User: XXXXXX
Session (65,29529): Bad TTC Packet Detected: Client IP Address: XX.XX.XX.XX
```

Here is the code :
```
package main

import (
    "database/sql"
    "log"

    _ "github.com/sijms/go-ora" // Oracle driver
)

func main() {
    connString := "oracle://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

    conn, err := sql.Open("oracle", connString)
    if err != nil {
        log.Print(err)
        return
    }
    defer conn.Close()
    log.Print(conn.Ping())
}
``` 

The database version is Oracle 12.2, and I have no idea of what's hapening. The queries get executed correctly, there is no error other than this message.
The DBA here are ranting about it, hence this issue.

**Comment by sijms** [comment]
information in the log is not sufficient for me to know the source of error
especially if the error occur one time only (which may be related to network of any thing else)

**Comment by sijms** [comment]
the problem is related to my client version which is older than oracle 12c database
now I am upgrading the client and this problem will be solved

**Comment by sijms** [comment]
I upgrade the client to version 2 can you test again for any error in server log file

**Comment by BZValoche** [comment]
I confirm that the error has no disappeared. Many thanks for the upgrade :-)
Cheers.
