### ISSUE TITLE
No Data Found Error Skipped (ORA-01403: no data found)

### ISSUE THREAD

**Issue by HassanAbdelzaher** [sijms/go-ora#576]
cmd := `DECLARE
   nCnt            NUMBER;
BEGIN
   SELECT 1
     INTO nCnt
     FROM dual
    WHERE 1=0;
END;`

rs, err := db.Exec(cmd)
if err != nil {
       t.Fatalf("error executing cmd: %v", err)
}

the above statement should raise error ORA-01403: no data found
but actualy no errors were raised.

**Comment by sijms** [comment]
the `ORA-01403` send for all database query to indicate the end of data transmission. 
you should use Query and Rows to check for data.
