### ISSUE TITLE
BINARY_FLOAT read column bug -1.1 as -1.2

### ISSUE THREAD

**Issue by lifthelm** [sijms/go-ora#580]
go-ora v2 v2.8.19 has a bug on reading BINARY_FLOAT column.
For example table of 3 columns: `id, BINARY_FLOAT, BINARY_DOUBLE`.
Data in database:
```
ID\|COL_05_BINARY_FLOAT\|COL_06_BINARY_DOUBLE\|
\--\+-------------------\+--------------------\+
1\|                1.1\|                 1.1\|
2\|               -1.1\|                -1.1\|
3\|                   \|                    \|

```

data read by go-ora:
```
Table scan:
id, BINARY_FLOAT, BINARY_DOUBLE
1       1.100000        1.100000
2       -1.200000       -1.100000

```

as I see maybe problem is in this function:
https://github.com/sijms/go-ora/blob/78d53fdf18c31d74e7fc9e0ebe49ee1c6af0abda/v2/converters/other_types.go#L27C1-L51C2

**Comment by sijms** [comment]
fixed in next release
