### ISSUE TITLE
panic with pointers after upgrade version

### ISSUE THREAD

**Issue by Gr33dkz** [sijms/go-ora#595]
Hi!
i updated go-ora version from v2.7.17 to v2.8.19 and my old code crashes with panic if i pass pointer
example:
```
type DbResp struct {
   IntValue *int64  `db:"name=intVal,type=number,direction=out"`
}

responseDB := &DbResp{}

_, err := db.ExecContext(ctx, Query, requestDb, responseDb)
```
this code worked fine in v2.7.17 but now it crashes in v2.8.19 with 
**panic: reflect: call of reflect.Value.Type on zero Value**
how can i fix it ?

**Comment by sijms** [comment]
sorry for late:
I add fix in next release so the above code will not crash
