### ISSUE TITLE
panic with pointers after upgrade version

### ISSUE THREAD

**Issue by Gr33dkz** [sijms/go-ora#596]
Hi!
i updated go-ora version from v2.7.17 to v2.8.19 and my old code crashes with panic if i pass pointer
example:

type DbResp struct {
   Value *float64  `db:"name=value,type=number,direction=out"`
}

responseDB := &DbResp{}

_, err := db.ExecContext(ctx, Query, requestDb, responseDb)
this code worked fine in v2.7.17 but now it crashes in v2.8.19 with
panic: reflect: call of reflect.Value.Type on zero Value
how can i fix it ?

**Comment by Gr33dkz** [comment]
now I solve this problem by allocating pointer variable, but now if Db response with null in float64 type, I got error Invalid NUMBER

**Comment by sijms** [comment]
use sql.NullFloat64

**Comment by vtolstov** [comment]
i cant confirm that. my test case
```go
type STR struct {
	SS string         `db:"SS"`
	NS sql.NullString `db:"NS"`
	FF float64        `db:"FF,number"`
	NF *float64       `db:"NF,number"`
}

	if err := db.GetContext(context.TODO(), x, `select 'ss' as "SS", null as "NS", 11.11 as "FF", null as "NF" from dual`); err != nil {
		panic(err)
	}
```
response
```go
&main.STR{SS:"ss", NS:sql.NullString{String:"", Valid:false}, FF:11.11, NF:(*float64)(nil)}
```
