### ISSUE TITLE
Runtime panic due to slice out of bounds

### ISSUE THREAD

**Issue by fleshin** [sijms/go-ora#6]
Hi,

I think you already mentioned this one and probably already working on it.
Can you please take a look? Thanks!

panic: runtime error: slice bounds out of range [:292] with capacity 16
goroutine 1 [running]:
github.com/sijms/go-ora/network.newRedirectPacketFromData
        .../go/src/github.com/sijms/go-ora/network/redirect_packet.go:41 
github.com/sijms/go-ora/network.(*Session).readPacket
        .../go/src/github.com/sijms/go-ora/network/session.go:272 
github.com/sijms/go-ora/network.(*Session).Connect
        .../go/src/github.com/sijms/go-ora/network/session.go:76 
github.com/sijms/go-ora.(*Connection).Open
        .../go/src/github.com/sijms/go-ora/connection.go:234

**Comment by sijms** [comment]
Hi
in normal response from the server you will not receive redirectPacket
check the connection string
can you please send me the code that produce this packet to analyse

**Comment by fleshin** [comment]
Below is a simplified version of the code. The actual URL comes from the command line.
A wrong URL is usually properly handled (no crash)

	vendor := "oracle"
	prefix := "oracle://"
	db, err := sql.Open(vendor, prefix+url)
	if err != nil {
		log.Fatal(err)
	}

**Comment by sijms** [comment]
I am trying to make the server fire a redirect packet but cannot
can you give me the packet data you receive you can add 
    `fmt.Println(packetData)`
at line 272 in session.go

**Comment by fleshin** [comment]
Sorry, I made a mistake. The error actually happened at a different place:

rows, err := db.Query("SELECT c1, c2, c3, c4, c5, c6 FROM t1 where c2 <> 1")

**Comment by sijms** [comment]
good please close

**Comment by sijms** [comment]
if every thing is ok please close

**Comment by sijms** [comment]
I make some changes to solve the problem with redirect packet
can you test and write feedback

**Comment by fleshin** [comment]
Hi Samy,
Thanks a lot for working on this issue. This is key for me as most our projects run on rac.
Unfortunately, my rac environment is down right now and will remain like that throughout this week.
Anyway, I've seen it was successfully tested on #23 , so that's great news. I will be testing on my side as soon as I can.
Thanks again!
