### ISSUE TITLE
build error for linux_arm target

### ISSUE THREAD

**Issue by Tommi2Day** [sijms/go-ora#603]
Updated to v2.8.21 and GO1.23 and receive now an error on Linux arm target (with goreleaser)

`  ⨯ build failed after 3s                    error=failed to build for linux_arm_6: exit status 1: # github.com/sijms/go-ora/v2/converters
vendor\github.com\sijms\go-ora\v2\converters\other_types.go:81:25: 2147483648 (untyped int constant) overflows int
vendor\github.com\sijms\go-ora\v2\converters\other_types.go:102:23: 2147483648 (untyped int constant) overflows int
vendor\github.com\sijms\go-ora\v2\converters\other_types.go:108:21: 2147483648 (untyped int constant) overflows int
vendor\github.com\sijms\go-ora\v2\converters\other_types.go:116:21: 2147483648 (untyped int constant) overflows int
`

other targets(Linux arm64,windows amd64) are not affected as well as v2.8.20 also doesn't have this issue

**Comment by Ferroin** [comment]
Also seeing this with go-ora v2.8.21 and Go v1.22.8 building for ARMv6 and ARMv7 Linux systems, same set of reported errors.
