### ISSUE TITLE
slice bounds out of range during rows.Next()

### ISSUE THREAD

**Issue by arunsworld** [sijms/go-ora#62]
Please see stack trace below in *Session.GetInt64 during rows.Next(). Not yet sure if I can reproduce the issue. But perhaps looking at this error might give some ideas to the circumstance in which this happened.

panic: runtime error: slice bounds out of range [-117:]

goroutine 59 [running]:
github.com/sijms/go-ora/network.(*Session).GetInt64(0xc0004ee480, 0x7d, 0x9c0101, 0x4526af, 0xc002d9bdb0, 0x7f7d0cd03d78)
	/Users/xxx/go/src/git.dev.e2open.com/chnshp/watermill-users/vendor/github.com/sijms/go-ora/network/session.go:717 +0x229
github.com/sijms/go-ora/network.(*Session).GetInt(0xc0004ee480, 0x1, 0xc002dc0101, 0x1, 0xb97, 0x0)
	/Users/xxx/go/src/git.dev.e2open.com/chnshp/watermill-users/vendor/github.com/sijms/go-ora/network/session.go:730 +0x4b
github.com/sijms/go-ora/network.(*Session).GetClr(0xc0004ee480, 0xb, 0xc002d4cca0, 0xba2, 0xc002d9bdb0, 0xb)
	/Users/xxx/go/src/git.dev.e2open.com/chnshp/watermill-users/vendor/github.com/sijms/go-ora/network/session.go:779 +0x210
github.com/sijms/go-ora.(*defaultStmt).read(0xc002a0b040, 0xc00cef6380, 0x0, 0x10102)
	/Users/xxx/go/src/git.dev.e2open.com/chnshp/watermill-users/vendor/github.com/sijms/go-ora/command.go:584 +0x433
github.com/sijms/go-ora.(*defaultStmt).fetch(0xc002a0b040, 0xc00cef6380, 0x19, 0xc000e52780)
	/Users/xxx/go/src/git.dev.e2open.com/chnshp/watermill-users/vendor/github.com/sijms/go-ora/command.go:472 +0x1ce
github.com/sijms/go-ora.(*DataSet).Next(0xc00cef6380, 0xc001f0bc00, 0xa9, 0xa9, 0xc000151ce8, 0x40d8db)
	/Users/xxx/go/src/git.dev.e2open.com/chnshp/watermill-users/vendor/github.com/sijms/go-ora/data_set.go:122 +0x2fa
database/sql.(*Rows).nextLocked(0xc003952200, 0x0)
	/usr/local/go/src/database/sql/sql.go:2865 +0xbf
database/sql.(*Rows).Next.func1()
	/usr/local/go/src/database/sql/sql.go:2843 +0x3c

**Comment by sijms** [comment]
this usually doesn't happen in normal condition.
confirm that you call rows.Scan(&val1, &val2) **in same order of** select col1, col2... and column type is integer

and if it is ok just give me example of you code to test in my own and see the problem

**Comment by arunsworld** [comment]
Did more debugging today. It's not with rows.Scan, instead it happens on rows.Next() - what we also see in the stack trace

I have managed to reproduce it. It is data related: something in the data causes the driver code to do the wrong thing.

The database schema has a VARCHAR field - let's call it FIELD1... a simple query: SELECT FIELD1 FROM TABLE WHERE ID=1 when called with db.Query panics when the code hits rows.Next() below:

query := `SELECT FIELD1 FROM TABLE WHERE ID=1`
rows,_ := db.Query(query)
defer rows.Close()

for rows.Next() {} // panics

This happens for a very particular record - so it's data related. Due to the sensitive nature of the data I cannot share it verbatim but will dig into the code to see if I can figure it out.

Any tips you can share though, I'd appreciate it.

**Comment by sijms** [comment]
see if the column is varchar or nvarchar? if data contain unicode character or special character?

**Comment by sijms** [comment]
I find a bug related to issue #63 and fix it
may be  your problem solved also

please test and feedback

**Comment by smallfz** [comment]
Hi @sijms! Pleasure to be here again. It's a wonderful project. Thanks again for creating it!

I got into the same situation. with server version 11g. (full version: Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production).

To reproduce:

    create table tmp6 ( lt varchar(400) );
    insert into tmp6( lt) values ( 'any string longer enough, say more than 300 chars...............');

And now query with sql `select * from tmp6`. 

    Write packet:
    00000000  00 57 00 00 06 00 00 00  00 00 03 5e 00 02 80 21  |.W.........^...!|
    00000010  00 01 01 12 01 01 0d 00  00 00 01 19 04 7f ff ff  |................|
    00000020  ff 00 00 00 00 00 00 00  00 00 00 00 01 00 00 00  |................|
    00000030  00 00 12 73 65 6c 65 63  74 20 2a 20 66 72 6f 6d  |...select * from|
    00000040  20 74 6d 70 36 01 01 01  19 00 00 00 00 00 01 01  | tmp6...........|
    00000050  00 02 80 00 00 00 00                              |.......|
    2021-08-06T01:26:16.1577: 
    Read packet:
    00000000  01 fb 00 00 06 00 00 00  00 00 10 17 02 e9 9b 8b  |................|
    00000010  94 81 b8 fa 86 80 fa 61  a3 ca 04 1c 78 79 08 06  |.......a....xy..|
    00000020  01 37 19 02 01 90 01 01  51 01 80 00 00 02 01 90  |.7......Q.......|
    00000030  00 00 00 00 02 03 54 01  02 01 90 01 02 01 02 02  |......T.........|
    00000040  4c 54 00 00 00 00 01 07  07 78 79 08 06 02 1c 2c  |LT.......xy....,|
    00000050  01 01 02 3f e8 01 0a 01  0a 00 06 22 01 01 00 01  |...?......."....|
    00000060  32 00 00 00 07 03 61 62  63 07 fe ff 20 49 50 20  |2.....abc... IP |
    00000070  61 64 64 72 65 73 73 20  66 6f 72 20 64 6f 63 6b  |address for dock|
    00000080  65 72 30 3a 20 20 20 20  20 20 20 20 20 31 37 32  |er0:         172|
    00000090  2e 31 37 2e 30 2e 31 0a  20 20 49 50 20 61 64 64  |.17.0.1.  IP add|
    000000a0  72 65 73 73 20 66 6f 72  20 62 72 2d 33 30 36 62  |ress for br-306b|
    000000b0  62 61 65 62 33 35 36 30  3a 20 31 30 2e 30 2e 31  |baeb3560: 10.0.1|
    000000c0  2e 31 0a 0a 20 20 47 72  61 70 68 20 74 68 69 73  |.1..  Graph this|
    000000d0  20 64 61 74 61 20 61 6e  64 20 6d 61 6e 61 67 65  | data and manage|
    000000e0  20 74 68 69 73 20 73 79  73 74 65 6d 20 61 74 20  | this system at |
    000000f0  68 74 74 70 73 3a 2f 2f  6c 61 6e 64 73 63 61 70  |https://landscap|
    00000100  65 2e 63 61 6e 6f 6e 69  63 61 6c 2e 63 6f 6d 2f  |e.canonical.com/|
    00000110  0a 0a 4e 65 77 20 72 65  6c 65 61 73 65 20 27 31  |..New release '1|
    00000120  34 2e 30 34 2e 32 20 4c  54 53 27 20 61 76 61 69  |4.04.2 LTS' avai|
    00000130  6c 61 62 6c 65 2e 0a 52  75 6e 20 27 64 6f 2d 72  |lable..Run 'do-r|
    00000140  65 6c 65 61 73 65 2d 75  70 67 72 61 64 65 27 20  |elease-upgrade' |
    00000150  74 6f 20 75 70 67 72 61  64 65 20 74 6f 20 69 74  |to upgrade to it|
    00000160  2e 0a 0a 0a 59 6f 75 72  20 48 61 3c 72 64 77 61  |....Your Ha<rdwa|
    00000170  72 65 20 45 6e 61 62 6c  65 6d 65 6e 74 20 53 74  |re Enablement St|
    00000180  61 63 6b 20 28 48 57 45  29 20 69 73 20 73 75 70  |ack (HWE) is sup|
    00000190  70 6f 72 74 65 64 20 75  6e 74 69 6c 20 41 70 72  |ported until Apr|
    000001a0  69 6c 20 32 30 31 37 2e  00 08 01 06 04 4f 17 ac  |il 2017......O..|
    000001b0  a8 02 16 a2 01 01 00 00  00 00 00 00 04 01 01 01  |................|
    000001c0  07 01 02 02 05 7b 00 00  01 01 01 0e 03 00 00 00  |.....{..........|
    000001d0  00 00 00 00 00 00 00 00  00 00 00 01 01 00 00 00  |................|
    000001e0  00 19 4f 52 41 2d 30 31  34 30 33 3a 20 6e 6f 20  |..ORA-01403: no |
    000001f0  64 61 74 61 20 66 6f 75  6e 64 0a                 |data found.|

Then the error will popup:

    panic: runtime error: slice bounds out of range [-119:] [recovered]
	    panic: runtime error: slice bounds out of range [-119:]
    
    goroutine 6 [running]:
    testing.tRunner.func1.2(0x121a080, 0xc0000a88d0)
	    /usr/local/go/src/testing/testing.go:1143 +0x332
    testing.tRunner.func1(0xc000001b00)
	    /usr/local/go/src/testing/testing.go:1146 +0x4b6
    panic(0x121a080, 0xc0000a88d0)
	    /usr/local/go/src/runtime/panic.go:965 +0x1b9
    github.com/sijms/go-ora/v2/network.(*Session).GetInt64(0xc00012a280, 0x7f, 0x101, 0xc0000d3290, 0x4, 0xc000042900)
	    /Users/luoyun/Documents/github.com/go-ora/v2/network/session.go:771 +0x229
    github.com/sijms/go-ora/v2/network.(*Session).GetInt(0xc00012a280, 0x1, 0xc0002c0101, 0x1, 0x1a0, 0x0)
	    /Users/luoyun/Documents/github.com/go-ora/v2/network/session.go:784 +0x4b
    github.com/sijms/go-ora/v2/network.(*Session).GetClr(0xc00012a280, 0x1, 0xc0002c665f, 0x1, 0x1a1, 0x0)
	    /Users/luoyun/Documents/github.com/go-ora/v2/network/session.go:833 +0x210
    github.com/sijms/go-ora/v2.(*defaultStmt).read(0xc0000c03c0, 0xc0000d4080, 0x0, 0x0)
	    /Users/luoyun/Documents/github.com/go-ora/v2/command.go:596 +0x58e
    github.com/sijms/go-ora/v2.(*Stmt).Query(0xc0000c03c0, 0x172c570, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	    /Users/luoyun/Documents/github.com/go-ora/v2/command.go:1240 +0x445
    database/sql.ctxDriverStmtQuery(0x1272c78, 0xc000024700, 0x1272d90, 0xc0000c03c0, 0x172c570, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	    /usr/local/go/src/database/sql/ctxutil.go:94 +0x16e
    database/sql.rowsiFromStatement(0x1272c78, 0xc000024700, 0x1272830, 0xc00000c1e0, 0xc0000b2480, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	    /usr/local/go/src/database/sql/sql.go:2695 +0x16d
    database/sql.(*DB).queryDC(0xc000101380, 0x1272c78, 0xc000024700, 0x0, 0x0, 0xc0000ba090, 0xc0000a4510, 0x123477e, 0x12, 0x0, ...)
	    /usr/local/go/src/database/sql/sql.go:1680 +0x238
    database/sql.(*DB).query(0xc000101380, 0x1272c78, 0xc000024700, 0x123477e, 0x12, 0x0, 0x0, 0x0, 0x1201a01, 0x123eb01, ...)
	    /usr/local/go/src/database/sql/sql.go:1628 +0x13e
    database/sql.(*DB).QueryContext(0xc000101380, 0x1272c78, 0xc000024700, 0x123477e, 0x12, 0x0, 0x0, 0x0, 0x160e229, 0xf, ...)
	    /usr/local/go/src/database/sql/sql.go:1605 +0xd4
    github.com/sijms/go-ora/v2/tests.TestQueryLongerChars(0xc000001b00)
	    /Users/smallfz/Documents/github.com/go-ora/v2/tests/panic_test.go:78 +0x37c
    testing.tRunner(0xc000001b00, 0x123e420)
	    /usr/local/go/src/testing/testing.go:1193 +0xef
    created by testing.(*T).Run
	    /usr/local/go/src/testing/testing.go:1238 +0x2b3
    FAIL	github.com/sijms/go-ora/v2/tests	1.278s

----

It's seems like there is a missing case in reading CLR chunks. 
The clr starts with a length byte `0xfe`. So there would be chunks following.
But in this case I get the chunk size byte `0xff`  instead of a 0~64 byte.
I checked the trace log and found out the actual data following the `0xff` byte is actually a null-term string.

I made a temporary fixing and it works. But I don't have any wire protocol specification documents so I'm not sure if that can hold up for all situations.

**Comment by smallfz** [comment]
Hi @sijms! Pleasure to be here again. It's a wonderful project. Thanks again for creating it!

I got into the same situation. with server version 11g. (full version: Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production).

To reproduce:

    create table tmp6 ( lt varchar(400) );
    insert into tmp6( lt) values ( 'any string longer enough, say more than 300 chars...............');

And now query with sql `select * from tmp6`. 

    Write packet:
    00000000  00 57 00 00 06 00 00 00  00 00 03 5e 00 02 80 21  |.W.........^...!|
    00000010  00 01 01 12 01 01 0d 00  00 00 01 19 04 7f ff ff  |................|
    00000020  ff 00 00 00 00 00 00 00  00 00 00 00 01 00 00 00  |................|
    00000030  00 00 12 73 65 6c 65 63  74 20 2a 20 66 72 6f 6d  |...select * from|
    00000040  20 74 6d 70 36 01 01 01  19 00 00 00 00 00 01 01  | tmp6...........|
    00000050  00 02 80 00 00 00 00                              |.......|
    2021-08-06T01:26:16.1577: 
    Read packet:
    00000000  01 fb 00 00 06 00 00 00  00 00 10 17 02 e9 9b 8b  |................|
    00000010  94 81 b8 fa 86 80 fa 61  a3 ca 04 1c 78 79 08 06  |.......a....xy..|
    00000020  01 37 19 02 01 90 01 01  51 01 80 00 00 02 01 90  |.7......Q.......|
    00000030  00 00 00 00 02 03 54 01  02 01 90 01 02 01 02 02  |......T.........|
    00000040  4c 54 00 00 00 00 01 07  07 78 79 08 06 02 1c 2c  |LT.......xy....,|
    00000050  01 01 02 3f e8 01 0a 01  0a 00 06 22 01 01 00 01  |...?......."....|
    00000060  32 00 00 00 07 03 61 62  63 07 fe ff 20 49 50 20  |2.....abc... IP |
    00000070  61 64 64 72 65 73 73 20  66 6f 72 20 64 6f 63 6b  |address for dock|
    00000080  65 72 30 3a 20 20 20 20  20 20 20 20 20 31 37 32  |er0:         172|
    00000090  2e 31 37 2e 30 2e 31 0a  20 20 49 50 20 61 64 64  |.17.0.1.  IP add|
    000000a0  72 65 73 73 20 66 6f 72  20 62 72 2d 33 30 36 62  |ress for br-306b|
    000000b0  62 61 65 62 33 35 36 30  3a 20 31 30 2e 30 2e 31  |baeb3560: 10.0.1|
    000000c0  2e 31 0a 0a 20 20 47 72  61 70 68 20 74 68 69 73  |.1..  Graph this|
    000000d0  20 64 61 74 61 20 61 6e  64 20 6d 61 6e 61 67 65  | data and manage|
    000000e0  20 74 68 69 73 20 73 79  73 74 65 6d 20 61 74 20  | this system at |
    000000f0  68 74 74 70 73 3a 2f 2f  6c 61 6e 64 73 63 61 70  |https://landscap|
    00000100  65 2e 63 61 6e 6f 6e 69  63 61 6c 2e 63 6f 6d 2f  |e.canonical.com/|
    00000110  0a 0a 4e 65 77 20 72 65  6c 65 61 73 65 20 27 31  |..New release '1|
    00000120  34 2e 30 34 2e 32 20 4c  54 53 27 20 61 76 61 69  |4.04.2 LTS' avai|
    00000130  6c 61 62 6c 65 2e 0a 52  75 6e 20 27 64 6f 2d 72  |lable..Run 'do-r|
    00000140  65 6c 65 61 73 65 2d 75  70 67 72 61 64 65 27 20  |elease-upgrade' |
    00000150  74 6f 20 75 70 67 72 61  64 65 20 74 6f 20 69 74  |to upgrade to it|
    00000160  2e 0a 0a 0a 59 6f 75 72  20 48 61 3c 72 64 77 61  |....Your Ha<rdwa|
    00000170  72 65 20 45 6e 61 62 6c  65 6d 65 6e 74 20 53 74  |re Enablement St|
    00000180  61 63 6b 20 28 48 57 45  29 20 69 73 20 73 75 70  |ack (HWE) is sup|
    00000190  70 6f 72 74 65 64 20 75  6e 74 69 6c 20 41 70 72  |ported until Apr|
    000001a0  69 6c 20 32 30 31 37 2e  00 08 01 06 04 4f 17 ac  |il 2017......O..|
    000001b0  a8 02 16 a2 01 01 00 00  00 00 00 00 04 01 01 01  |................|
    000001c0  07 01 02 02 05 7b 00 00  01 01 01 0e 03 00 00 00  |.....{..........|
    000001d0  00 00 00 00 00 00 00 00  00 00 00 01 01 00 00 00  |................|
    000001e0  00 19 4f 52 41 2d 30 31  34 30 33 3a 20 6e 6f 20  |..ORA-01403: no |
    000001f0  64 61 74 61 20 66 6f 75  6e 64 0a                 |data found.|

Then the error will popup:

    panic: runtime error: slice bounds out of range [-119:] [recovered]
	    panic: runtime error: slice bounds out of range [-119:]
    
    goroutine 6 [running]:
    testing.tRunner.func1.2(0x121a080, 0xc0000a88d0)
	    /usr/local/go/src/testing/testing.go:1143 +0x332
    testing.tRunner.func1(0xc000001b00)
	    /usr/local/go/src/testing/testing.go:1146 +0x4b6
    panic(0x121a080, 0xc0000a88d0)
	    /usr/local/go/src/runtime/panic.go:965 +0x1b9
    github.com/sijms/go-ora/v2/network.(*Session).GetInt64(0xc00012a280, 0x7f, 0x101, 0xc0000d3290, 0x4, 0xc000042900)
	    /Users/smallfz/Documents/github.com/go-ora/v2/network/session.go:771 +0x229
    github.com/sijms/go-ora/v2/network.(*Session).GetInt(0xc00012a280, 0x1, 0xc0002c0101, 0x1, 0x1a0, 0x0)
	    /Users/smallfz/Documents/github.com/go-ora/v2/network/session.go:784 +0x4b
    github.com/sijms/go-ora/v2/network.(*Session).GetClr(0xc00012a280, 0x1, 0xc0002c665f, 0x1, 0x1a1, 0x0)
	    /Users/smallfz/Documents/github.com/go-ora/v2/network/session.go:833 +0x210
    github.com/sijms/go-ora/v2.(*defaultStmt).read(0xc0000c03c0, 0xc0000d4080, 0x0, 0x0)
	    /Users/smallfz/Documents/github.com/go-ora/v2/command.go:596 +0x58e
    github.com/sijms/go-ora/v2.(*Stmt).Query(0xc0000c03c0, 0x172c570, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	    /Users/smallfz/Documents/github.com/go-ora/v2/command.go:1240 +0x445
    database/sql.ctxDriverStmtQuery(0x1272c78, 0xc000024700, 0x1272d90, 0xc0000c03c0, 0x172c570, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	    /usr/local/go/src/database/sql/ctxutil.go:94 +0x16e
    database/sql.rowsiFromStatement(0x1272c78, 0xc000024700, 0x1272830, 0xc00000c1e0, 0xc0000b2480, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	    /usr/local/go/src/database/sql/sql.go:2695 +0x16d
    database/sql.(*DB).queryDC(0xc000101380, 0x1272c78, 0xc000024700, 0x0, 0x0, 0xc0000ba090, 0xc0000a4510, 0x123477e, 0x12, 0x0, ...)
	    /usr/local/go/src/database/sql/sql.go:1680 +0x238
    database/sql.(*DB).query(0xc000101380, 0x1272c78, 0xc000024700, 0x123477e, 0x12, 0x0, 0x0, 0x0, 0x1201a01, 0x123eb01, ...)
	    /usr/local/go/src/database/sql/sql.go:1628 +0x13e
    database/sql.(*DB).QueryContext(0xc000101380, 0x1272c78, 0xc000024700, 0x123477e, 0x12, 0x0, 0x0, 0x0, 0x160e229, 0xf, ...)
	    /usr/local/go/src/database/sql/sql.go:1605 +0xd4
    github.com/sijms/go-ora/v2/tests.TestQueryLongerChars(0xc000001b00)
	    /Users/smallfz/Documents/github.com/go-ora/v2/tests/panic_test.go:78 +0x37c
    testing.tRunner(0xc000001b00, 0x123e420)
	    /usr/local/go/src/testing/testing.go:1193 +0xef
    created by testing.(*T).Run
	    /usr/local/go/src/testing/testing.go:1238 +0x2b3
    FAIL	github.com/sijms/go-ora/v2/tests	1.278s

----

It's seems like there is a missing case in reading CLR chunks. 
The clr starts with a length byte `0xfe`. So there would be chunks following.
But in this case I get the chunk size byte `0xff`  instead of a 0~64 byte.
I checked the trace log and found out the actual data following the `0xff` byte is actually a null-term string.

I made a temporary fixing and it works. But I don't have any wire protocol specification documents so I'm not sure if that can hold up for all situations.

**Comment by smallfz** [comment]
Just tested the exact test case works fine with v1.
