### ISSUE TITLE
Is there any way to limit row number queried and returned for SQL with no ROWNUM specified?

### ISSUE THREAD

**Issue by xiaodp** [sijms/go-ora#623]
Querying without row number limitation will cause pressure to DB and applications.

e.g.:
I built an application with Golang  for users to collect and execute  their querys, and return the results. But occasionally,  users's SQL has no ROWNUM limit, e.g. `select id, name from example_table where id > 0`. It's huge work for oracle and application when example_table has 10 million records.

It's not good idea to require users to obey some rules like 'You must type in SQL with WHERE ROWNUM < 1000'.

Is there any way to set limitation to go_ora driver for a query?
when  executing `select id, name from example_table where id > 0`, driver start to get result ,where the result has 1000 rows, stop query.

I tried the following way, but didn't work.
```
	rows, err :=db.QueryContext(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var foos []*model.Foo
	for rows.Next() {
                 foo := &model.Foo{}
		err := rows.Scan(&foo.id, &foo.Name)
		if err != nil {
			return nil, err
		}
		foos = append(foos, foo)
		if len(foos) == 1000 {
                     break
                 }
	}
```

**Comment by xiaodp** [comment]
I found this issue, https://github.com/sijms/go-ora/issues/69, let me do some test

**Comment by sijms** [comment]
actually the driver fetch rows from database group by group the group size is determined by `PREFETCH_ROWS` url option.
so you can control the number of rows by this url option + using index inside for clause
