### ISSUE TITLE
ORA-00911: invalid character

### ISSUE THREAD

**Issue by smallfz** [sijms/go-ora#66]
hi! thanks for this great project.

I encounter  an error when I use chinese word as a column alias. eg.:

`select sysdate 中文 from dual`

it gets `ORA-00911: invalid character`.

I cloned the repo and made some changes to [converters/string_conversion.go](https://github.com/smallfz/go-ora/commit/1b9666f7899db90e25d07c33d68879877904845c). and it runs fine. wish that helps.

if you are willing to accept a pr I will be happy to start one. 
if not, since that commit imports an external module, I'll be still happy to work out another solution, like exposing an interface:

    type IStringConverter interface{
        Encode(string) []byte
        Decode([]byte) string
    }

to let the client code to register their own encoder/decoder.

**Comment by sijms** [comment]
sorry for late replay
I add encoding for charsets (0x33D, 0x33E, 0x33F, 0x340, 0x352, 0x353, 0x354)
now it will work properly without errors

I prefer to use IStringConverter interface I will add support for it in my code

**Comment by sijms** [comment]
I add IStringConverter interface support
now you can add custom converter by the following function
```
func (conn *Connection) SetStringConveter(conveter converters.IStringConverter) {
	conn.strConv = conveter
	conn.session.StrConv = conveter
}
```

**Comment by smallfz** [comment]
That's great. I also think keep minimum dependencies is a good idea.
I'll close the pr now.
