### ISSUE TITLE
Add support for prefetch_rows and prefetch_memory

### ISSUE THREAD

**Issue by rbretecher-fcms** [sijms/go-ora#69]
Hello,

First of all, I would like to thank you for this awesome module ! It's so nice to be able to query Oracle databases without any extra dependency :)

I'm using this module for a project and I was wondering if it could be possible to add support for `prefetch_rows` and `prefetch_memory`  options that can be usually configured on the connection string :
```
oracle://user:pass@server/service_name?prefetch_rows=500&prefetch_memory=500
```

I tried to set those options but I could not notice any difference so I guess it's just not supported (those options do not appear in the `connection_string.go` file).

I was previously using [github.com/mattn/go-oci8](https://github.com/mattn/go-oci8) module and with those two options, the performance is really better when fetching a lot of data. I think it can explain why this module can be slow sometimes.

If you don't have time to add support for this, I might be able to make a PR. Let me know :)

**Comment by sijms** [comment]
hi @rbretecher-fcms 
I add prefetch_rows option to the url you can use it now

**Comment by rbretecher-fcms** [comment]
Thank you very much for this change, this is awesome.

My code is now 50 times faster when fetching a lot of data, from 15 minutes to 20 secondes :rocket: 

I think you can close this issue. Keep up the good work :)

**Comment by gorandumic** [comment]
Could you please elaborate these parameters in details:
- what do they exactly do
- what is the recommended input for them
- in what unit is prefetch_memory: bytes, kilobytes..?
