### ISSUE TITLE
Bulk Inserts

### ISSUE THREAD

**Issue by aphsa** [sijms/go-ora#7]
Is there a equivalent of https://godoc.org/github.com/lib/pq#hdr-Bulk_imports in this driver?

**Comment by sijms** [comment]
you mean insert multiple rows with one call of insert stmt
I need to add support for binding array to the driver (till now not support binding array)
but I am working on upgrading the driver and add this feature + dealing with blobs

**Comment by sijms** [comment]
### after support of re-execute statement you can use fast insert (still not bulk insert) like this
```
conn, err := sql.Open("oracle", "oracle://user:pass@server/service_name")
// check for error
defer conn.Close()

stmt, err := conn.Prepare("INSERT INTO NAT (NAT_ID, NAT_NAME) VALUES(:1, :2)")
// check for error
defer stmt.Close()

ids := []int{1, 2, 3}
names := []string{ "nat_1", "nat_2", "nat_3"}
for x:=0; x < len(ids); x++ {
    err = stmt.Exec(ids[x], names[x])
    // check for errors
}
```
