### ISSUE TITLE
Can not fetch ROWID

### ISSUE THREAD

**Issue by inoerp** [sijms/go-ora#70]
Fetching ROWID in select statement throws below error 

`TTC error: received code 3 during stmt reading.`

Below seems to be the snippet causing the issue. 

`func (stmt *defaultStmt) read(dataSet *DataSet) error {
	loop := true
	after7 := false
	containOutputPars := false
	dataSet.parent = stmt
	session := stmt.connection.session
	for loop {
		msg, err := session.GetByte()
		if err != nil {
			return err
		}
		fmt.Println("Message ", msg)
		switch msg {`

**Comment by sijms** [comment]
fixed now 

please test and comment

**Comment by inoerp** [comment]
Yes works fine now.
Thanks for the quick fix.
