### ISSUE TITLE
Support Go Modules

### ISSUE THREAD

**Issue by jpm63** [sijms/go-ora#73]
Are there any plans to support Go modules for this package? As currently designed, it's particularly difficult to consume.

**Comment by sijms** [comment]
the package has no external dependencies and you can use it in your project go module file without any problem
is this what you mean?

**Comment by ueffel** [comment]
it basically means you run

```
go mod init "github.com/sijms/go-ora" && go mod tidy
```

and commit `go.mod` (as there are no depenencies, there will be no `go.sum` which normally should be commited as well)

This has some implications for applications that import `github.com/sijms/go-ora`. 
Mainly they won't update to the latest commit on the master/main branch but to the latest release tag. Tags should have a [semantic version](https://semver.org/). Also users of major version v1 don't automatically update to a v2.

Further reading: [Go Modules](https://blog.golang.org/using-go-modules) and [Go Modules: v2 and Beyond](https://blog.golang.org/v2-go-modules)

It's a pretty neat system to give you more control over the versions of libraries your go application use. Please think about adopting it :)

**Comment by sijms** [comment]
I make some changes

would you check and comment

**Comment by sijms** [comment]
I think now it is ok

**Comment by ueffel** [comment]
Looks good to me. Good work.
