### ISSUE TITLE
ORA-03120: two-task conversion routine: integer overflow

### ISSUE THREAD

**Issue by ding** [sijms/go-ora#8]
When I run same query second time, I got the ORA-03120 error.
ORA-03120: two-task conversion routine: integer overflow

I can get the query result first time in loop, but it went wrong in second time.

`
db, err := sql.Open("oracle", connectStr)
if err != nil {
	log.Println("ERR! Oracle open error")
	log.Fatal(err)
}
defer db.Close()

... ...

stmt, err := db.Prepare(“... some query with parameter ... ”)
// check error 

for v := range patternList {
	result, err := stmt.Query(v)
	// check error
}
`

**Comment by sijms** [comment]
### The following code is run without error connecting to oracle server 11.2
    conn, err := sql.Open("oracle", connStr)
    if err != nil {
		fmt.Println(err)
		return
    }
    defer conn.Close()    
    stmt, err := conn.Prepare("SELECT STORE_ID FROM STK_STORE WHERE STORE_ID = 1");
	if err != nil {
		fmt.Println(err)
		return
	}
	defer stmt.Close()
	results, err := stmt.Query()
	if err != nil {
		fmt.Println(err)
		return
	}
	defer results.Close()
	var storeID sql.NullInt64
	for results.Next() {
		err = results.Scan(&storeID)
		if err != nil {
			fmt.Println(err)
			return
		}
		fmt.Println("store id: ", storeID)
	}
	stmt, err = conn.Prepare("SELECT STORE_ID FROM STK_STORE WHERE STORE_ID = 8");
	if err != nil {
		fmt.Println(err)
		return
	}
	defer stmt.Close()
	results, err = stmt.Query()
	if err != nil {
		fmt.Println(err)
		return
	}
	for results.Next() {
		err = results.Scan(&storeID)
		if err != nil {
			fmt.Println(err)
			return
		}
		fmt.Println("store id: ", storeID)
	}

**Comment by sijms** [comment]
if problem solved please close

**Comment by ding** [comment]
> 
> 
> if problem solved please close

Sorry,  following code will get this error.

`	conn, err := sql.Open("oracle", connStr)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer conn.Close()
	stmt, err := conn.Prepare("SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE JOB_ID = :SA_REP")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer stmt.Close()
	results, err := stmt.Query("SA_REP")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer results.Close()
	var employeeID sql.NullInt64
	for results.Next() {
		err = results.Scan(&employeeID)
		if err != nil {
			fmt.Println(err)
			return
		}
		fmt.Println("employee id: ", employeeID)
	}

	fmt.Println("---Query again---")
	results, err = stmt.Query("SA_MAN")
	if err != nil {
		fmt.Println(err)
		return
	}
	for results.Next() {
		err = results.Scan(&employeeID)
		if err != nil {
			fmt.Println(err)
			return
		}
		fmt.Println("employee id: ", employeeID)
	}`

**Comment by ding** [comment]
- Oracle 12c 
- CentOS 8
- Go 1.15.3 @ windows10

**Comment by sijms** [comment]
sorry for late
I add support for re-execute stmt it will solve your problem
please test and tell me you feedback

thanks

**Comment by ding** [comment]
Thank you very much! It's work good!

But I got another bug, about [type_conversion.go], I will create a new issue.

**Comment by ding** [comment]
After I updated to the latest version, it doesn't seem to work.
