### ISSUE TITLE
Connection With Diffie Hellman Key Exchange Still Not Supported

### ISSUE THREAD

**Issue by aidar-darmenov** [sijms/go-ora#81]
Hello, sijms

Please can you help me

Using your driver (1.2 version)

The error "EOF" occurs where I am trying to Ping() connection to database

Connection establishes, but then Ping returns error

**This is my connection string**
oracle://my_user:mypass%231@xx.1.1.xx:1524/MyService_Name?TRACE FILE=trace.log

%23 is used instead of # sign

I telnet-ed the connection to the DB, connection appears to be accessible. Also, I am doing SQL requests with the same authorization params from DBeaver to thie DB, they also work

Error appears on this part of sql library

	db.numOpen++ // optimistically
	db.mu.Unlock()
	ci, err := db.connector.Connect(ctx)
	if err != nil { ----HERE IS THE ERROR
		db.mu.Lock()
		db.numOpen-- // correct for earlier optimism
		db.maybeOpenNewConnections()
		db.mu.Unlock()
		return nil, err
	}
	
	
Tried your v2 version of driver, error "diffie hellman key exchange still under development" appears

Looking forward for your answer,
with big hope, 
fellow developer

**Comment by sijms** [comment]
Hi @aidar-darmenov 
Sorry for late replay

the message you receive "Diffie Hellman key exchange still under development" means that server need client that support Diffie Hellman advanced negotiation.
I know there is many golang packages that support Diffie Hellman key exchange but the problem I don't have the server that ask for this advanced negotiation to test the response.

### **_note:_** 
v1 doesn't support advanced negotiation at all so it will be ok for oracle servers before 10.2

Can you tell me the server version you use and any special configuration I will make to let the server support Diffie Hellman thus I can analyze the response.

**Comment by falco467** [comment]
Can you use the oracle cloud 30 day trial, to test against a free online server? They should require advanced negotiation.

**Comment by sijms** [comment]
I push a commit to V2 that contain support:
 1-  Diffie Hellman key exchange 
 2- Encryption service using AES encryption

**Comment by calebeaires** [comment]
Version: go-ora v2.2.15
Go version: 1.16

hi @sijms, thanks to the DF support.

While using [usql](https://github.com/xo/usql) with your lib, the drive show this error

Usql command
```bash
usql or://pass:pass@localhost:1521/service
```

Returns
```bash
error: oracle: diffie hellman key exchange still under development
```

You have said that you add support to it. Could you help me understand on how to enable this feature? Do I have to set some tag at the connection string?

**Comment by sijms** [comment]
can you upgrade to latest version and test
this error message is old

**Comment by calebeaires** [comment]
@sijms,
I updated to the last version and now it works. After the update another issue came out: **A table with 18.000 rows starts to deliver only 50 rows when exporting to CSV.** 

I have tried do find out what make this happen, but I couldn't find exactly the bug.

**Comment by sijms** [comment]
when you get rows from table don't use the internal buffer of the DataSet as this buffer is used as a temporary buffer so its value is always changed
the correct way as follow:
```golang 
// create your buffer that will carry all your rows
for Next()  {
    // get the values by calling Scan
    Scan()
   // put the value in your buffer
}
// here your buffer contain 18000 rows
```

you can see examples in the package that show you how to use the driver in optimum way
