### ISSUE TITLE
large amount of .trc and .trm file generated

### ISSUE THREAD

**Issue by zhuaizhuaixi** [sijms/go-ora#82]
Once I execute a SQL with go-ora, a .trm and a .trc will be generate on Oracle's trace directory.

These files will never be deleted and disk usage will reach 100% in a short time.

Is it a bug or something wrong with my usage?

.trc file path

> /u01/app/oracle/diag/rdbms/xe/XE/trace

.trc:
> Trace file /u01/app/oracle/diag/rdbms/xe/XE/trace/XE_ora_800.trc
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
ORACLE_HOME = /u01/app/oracle/product/11.2.0/xe
System name:	Linux
Node name:	worker4
Release:	3.10.0-957.el7.x86_64
Version:	#1 SMP Thu Nov 8 23:39:32 UTC 2018
Machine:	x86_64
Instance name: XE
Redo thread mounted by this instance: 1
Oracle process number: 42
Unix process pid: 800, image: oracle@worker4
*** 2021-06-21 17:11:35.068
*** SESSION ID:(242.25843) 2021-06-21 17:11:35.068
*** CLIENT ID:() 2021-06-21 17:11:35.068
*** SERVICE NAME:(XE) 2021-06-21 17:11:35.068
*** MODULE NAME:(agent) 2021-06-21 17:11:35.068
*** ACTION NAME:() 2021-06-21 17:11:35.068
ttcdrvdmplocation: msg-0 ln-252 reporting 3137
Dumping 'Buffer dump info:' addr=0xb0a8060 size=7 bytes
Dump of memory from 0xb0a8060 to 0xb0a8068
00B0A8060 01006911 03000101                    [.i......]        
Dumping 'Buffer dump info:' addr=0xb0a8067 size=3 bytes
Dump of memory from 0xb0a8064 to 0xb0a806c
00B0A8060          03000101 CD050093               [........]    
hstflg:  0x40202d81
hstcflg: 0x00000000
hstpro:  6
hstccs:  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=xx.xx.xx.xx:1521)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=xe)(CID=(PROGRAM=./agent)(HOST=worker3)(USER=root))))

**Comment by sijms** [comment]
Hi @zhuaizhuaixi 
I test a simple select statement using oracle server 12.2 and no problem happen in the server no .trc or .trm files

are you using v2
### _**note:**_
v1 is work better for oracle server before 10.2

**Comment by zhuaizhuaixi** [comment]
Thanks for your reply. @sijms 
My Oracle server version is 11.2

After updating to v2, this problem is resolved

The version I use before is v0.0.0-20201227172957-a444fae11746
Is it a test version, and why these file will be generated?

**Comment by sijms** [comment]
yes many updates I do is for issue resolving so always use the latest version
