### ISSUE TITLE
Connection error is a bit silent

### ISSUE THREAD

**Issue by BZValoche** [sijms/go-ora#84]
Hi,
I spent like 1 hour debugging a "connection refused by the server" error. Turns out it was an incorrect service name in the connection string.
I had the enlightenment when I activated some traces in network/session.go :
Response: "\x00g\x00\x00\x04\x00\x00\x00\"\x00\x00[(DESCRIPTION=(TMP=)(VSNNUM=203424000)(ERR=12514)(ERROR_STACK=(ERROR=(CODE=12514)(EMFI=4))))"

Would it be possible to at least put the Oracle error code in the error returned by the Connect() function? it might be helpful.
Thanks!

**Comment by BZValoche** [comment]
Yes the error message is very useful. I'd suggest to keep everything on a single line, because multiple lines sort of mess up logfiles, as you can see here :

![image](https://user-images.githubusercontent.com/48053275/127128704-27664cb2-5ba4-46b8-8aa2-a13c211eb104.png)

**Comment by sijms** [comment]
I make the fixation

**Comment by BZValoche** [comment]
Yes, perfect. Thanks a bunch, keep up the excellent work :-)
