### ISSUE TITLE
ORA-01461: can bind a LONG value only for insert into a LONG column

### ISSUE THREAD

**Issue by l-we** [sijms/go-ora#86]
```
create table A ( NAME VARCHAR2(20) )
```

```
	log.Fatalln(oDB.Exec(`insert into a (name) values (:1)`, "中文"))
```

**Comment by sijms** [comment]
can you explain the problem?
you have varchar2 column and you insert string value. I test the above code and it is working well (suppose that you have a correct server charset to store Chinese text

**Comment by l-we** [comment]
V1 is normal
V2 error

**Comment by sijms** [comment]
I am using V2
```
_, err = conn.Exec(`insert into a (name) values (:1)`, "中文"))
```
execute without error.
to check the text is inserted correctly:
```
var result string
rows, err := conn.Query("select name from A")
if err != nil {
    fmt.Println(err)
    return
}
for rows.Next() {
    err = rows.Scan(&result)
    if err != nil {
       	fmt.Println(err)
	return
    }
    fmt.Println(result)
}
```

result is:
中文

**Comment by sijms** [comment]
confirm that you are using latest version 2 and your database charset is support:
version 2.1.19: support more charsets (0x33D, 0x33E, 0x33F, 0x340, 0x352, 0x353, 0x354)

**Comment by l-we** [comment]
thx, set NLS_LANG 'SIMPLIFIED CHINESE_CHINA.UTF8' is ok,

oracle server charset : SIMPLIFIED CHINESE_CHINA.ZHS16GBK
