### ISSUE TITLE
Custom objects

### ISSUE THREAD

**Issue by Marvin-TMG** [sijms/go-ora#88]
Thanks for developing this library! I am new to go, but it has been easy to reimplement our Python methods using your library.

However, I am currently still facing a problem, which is how to query custom objects stored in the database. Do you have any example how to retrieve an oracle object and convert this?

Thank you in advance.

For reference, in Python, we solved it by building an output converter which was attached to the query:
```
# this converter is used to convert Y_CUSTOM_OBJECT custom object to a list of integers
def list_out_converter(self, obj):
     return obj.aslist() 

# output type handler allows us to convert query output data types
def blob_output_type_handler(self, cursor, name, default_type, size, precision, scale):
      if default_type == cx_Oracle.DB_TYPE_OBJECT:
            return cursor.var(cx_Oracle.DB_TYPE_OBJECT, arraysize=cursor.arraysize, typename='MY_CUSTOM_OBJECT', outconverter=self.list_out_converter)

```

**Comment by sijms** [comment]
I think you need to use pl/sql and parameter to get the result in go struct

**Comment by Marvin-TMG** [comment]
Thanks, I have not tried that yet. Do you have an example perhaps?

I tried it with the godror library which implements the Oracle Object type, using this library I was able to use the following process to obtain the object and convert it to a list (BOUNDERS is the custom object representing a []int).
```

type data struct {
   Id    int
   NodeDef_Id   int
   Sent   int
   ValueRaw    byte[]
    BOUNDERS    interface{}
}

err = db.Select(&data, `SELECT t.ID, t.NODEDEF_ID, t.SENT, t.VALUERAW, t.BOUNDERS FROM table_name t WHERE t.CATEGORY_ID = :1`, input_1)

if err != nil {
	fmt.Println(err)
	close(c)
}

for i, blob := range data {
	var datatype []int64
	obj := blob.BOUNDERS.(*godror.Object)
	val, _ := obj.Collection().AsSlice(datatype)
	data[i].BOUNDERS = val
}
```

it would be great if the same/similar object type can be implemented

**Comment by sijms** [comment]
no need to convert to sql as pl/sql is also running but you need to use output parameter to get the result
see file connection.go line# 91 for example
```func (conn *Connection) GetNLS() (*NLSData, error)```

**Comment by sijms** [comment]
no problem I will investigate the issue and try to find better solution

**Comment by Marvin-TMG** [comment]
Thanks, that would be appreciated. It would be nice to have proper support for objects similar to godror. Please let me know if you have any plans for this and if you like me to test something.

**Comment by sijms** [comment]
I will leave the issue opened and when I make solution I will inform you here

**Comment by sijms** [comment]
I make a commit  contain update about the issue
I explain how to use user defined type in README.md file v2.2.6 pre-realease
I test it against oracle server 12c hope it will work with other version
please test and send me your feedback

**Comment by sijms** [comment]
I test against other oracle version and working correctly

**Comment by sijms** [comment]
I add an example for how to user user defined type UDT
