### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by lfittl** [sijms/go-ora#9]
Thank you for developing this!

Two questions:

1) This project seems to be missing a license - which license is this made available under?

2) Was this client developed using the source of an existing Oracle library? (I'm mostly curious since its rare to find a client that doesn't rely on Oracle's SDK)

**Comment by sijms** [comment]
the license is open you can you can use the client as you need in any project without limitation
you can also modify the cod.
my primary goal for this project is solving the problem of oracle with go when I start to write a go code 
using oracle I find many driver that use C code but difficult to install this drive me to start the project

the project depends mostly on network analysis, plus reverse engineering of an existing client  (especially for
authentication step)
