### ISSUE TITLE
running pl/sql statment

### ISSUE THREAD

**Issue by benor1470** [sijms/go-ora#91]
is running pl/sql statemnt work or should it work?
I'm used to running sql files using sqlcl command line tool, those files has sqlcl code like
```
sqlcl.setStmt("insert into tbl(name,timestamp,value) values ('blabla', LOCALTIMESTAMP, '1');");
sqlcl.run();
```
Is there any way of running this code using your tool?

Thank you

**Comment by sijms** [comment]
what is the issue?
do you try to run the code and get error?
you can read readme file and see example files in project to help you using the library

**Comment by sijms** [comment]
you can run sql or pl/sql stmt as as sqlcl but without ";" at the end of the stmt
```
insert into tbl(name,timestamp,value) values ('blabla', LOCALTIMESTAMP, '1')
```

**Comment by benor1470** [comment]
My full pl/sql code is a bit more complicated so I can't just convert it to normal sql.

I must use sqlcl commands as I'm also using util.executeReturnListofList to run a select statement and based on the results run a list of SQL statement

**Comment by sijms** [comment]
no need to convert to sql as pl/sql is also running but you need to use output parameter to get the result
see file connection.go line# 91 for example
```func (conn *Connection) GetNLS() (*NLSData, error)```

**Comment by benor1470** [comment]
not sure I followed, my text file contains the pl/sql code
for example this is a full pl/sql file I have
[updateToVersion6.txt](https://github.com/sijms/go-ora/files/6969708/updateToVersion6.txt)


when running using sqlcl I can give this file and a connection props and I can update to version 6 only if the current version is 5
so I need to run the same files using your library which will save me a lot of storage space

**Comment by sijms** [comment]
you will convert this code into go:
```
// you should supply dsn = "oracle://user/pass@server/service"
conn, err := sql.Open("oracle", dsn)
// check for error
defer conn.Close()
row, err := conn.QueryRow(`select count(*) from VERSION_HOLDER WHERE value = '5'`)
// check for error
if rows != nil  {
   var result sql.NullInt64
   err = row.Scan(&result)
   // check for error
   if result.Valid && result.Int64 > 0 {
      _, err = conn.Exec(`update VERSION_HOLDER set value='6'`)
     // check for error
   }
```

**Comment by sijms** [comment]
if you need to do it with pl/sql you will convert to pl/sql text
```
DECLARE
   cnt number
BEGIN
   SELECT count(*) into cnt from VERSION_HOLDER WHERE value = '5';
   IF nvl(cnt, 0) > 0 then
      update VERSION_HOLDER set value='6';
   END IF;
END
```

**Comment by benor1470** [comment]
thank you very much, it works but it will require me to change the scripts which isn't an option right now
